import {test,expect} from '@playwright/test';
const snapshot='a'.repeat(64),owner='editor-one';
const initial=()=>({workspaceId:'workspace-one',ownerId:owner,configured:true,budget:{authorized:true,reservedUSD:10,remainingUSD:20,ingestionRemainingUSD:8,note:'Bound to this fixture workspace and connection.'},status:{status:'pending',snapshotHash:null,note:'No Cloud checkpoint yet'},pending:[],localHash:'b'.repeat(64)});
test('manual Cloud checkpoint controls stage, show credit bound and publish only on explicit action',async({page})=>{
 let value=initial(),writes=0;await page.route('**/api/cloud-workspace',r=>r.fulfill({json:value}));
 await page.route('**/api/cloud-workspace/stage',r=>{value={...value,pending:[{snapshotHash:snapshot,status:'pending',forecast:{uniqueDocuments:2,fullWriteReservationUSD:.3}}]};return r.fulfill({json:{snapshotHash:snapshot,status:'pending'}});});
 await page.route('**/api/cloud-workspace/publish',r=>{writes++;value={...value,status:{status:'verified',snapshotHash:snapshot,activeOwnerId:owner,note:'Exact checkpoint verified'},pending:[]};return r.fulfill({json:{status:'verified'}});});
 await page.goto('/#connections');const panel=page.getByRole('region',{name:'Cloud workspace recovery'});await expect(panel).toContainText('No Cloud checkpoint yet');expect(writes).toBe(0);await panel.getByRole('button',{name:'Prepare Cloud checkpoint',exact:true}).click();await expect(panel).toContainText('$0.30 write reservation');expect(writes).toBe(0);await panel.getByRole('button',{name:/Publish or check checkpoint/}).click();await expect(panel).toContainText('Exact checkpoint verified');expect(writes).toBe(1);
});
test('Cloud disconnected and fork errors cannot display a verified checkpoint or retry silently',async({page})=>{
 let value={...initial(),configured:false};let calls=0;await page.route('**/api/cloud-workspace',r=>r.fulfill({json:value}));await page.route('**/api/cloud-workspace/publish',r=>{calls++;return r.fulfill({status:409,json:{error:'Competing descendant heads detected. Recover before editing.'}});});await page.goto('/#connections');const panel=page.getByRole('region',{name:'Cloud workspace recovery'});await expect(panel.getByRole('button',{name:'Prepare Cloud checkpoint',exact:true})).toBeDisabled();
 value={...initial(),pending:[{snapshotHash:snapshot,status:'pending',forecast:{uniqueDocuments:2,fullWriteReservationUSD:.3}}]};await page.reload();await panel.getByRole('button',{name:/Publish or check checkpoint/}).click();await expect(panel.getByRole('alert')).toContainText('Competing descendant');expect(calls).toBe(1);await expect(panel).toContainText('pending');
});
test('Cloud recovery previews counts and requires explicit local replacement before apply',async({page})=>{
 await page.route('**/api/cloud-workspace',r=>r.fulfill({json:initial()}));let apply=0;
 await page.route('**/api/cloud-workspace/recovery-preview',r=>r.fulfill({json:{previewId:'test-preview',expectedLocalHash:'b'.repeat(64),snapshotHash:snapshot,workspaceId:'workspace-one',activeOwnerId:owner,canEdit:false,counts:{cases:9,companies:9,articles:247,officialDocuments:5}}}));
 await page.route('**/api/cloud-workspace/recovery-apply',r=>{expect(r.request().postDataJSON().confirmReplace).toBe(true);apply++;return r.fulfill({json:{restored:true,requiresSourceReverification:true}});});
 await page.goto('/#connections');const panel=page.getByRole('region',{name:'Cloud workspace recovery'});await panel.getByText('Recover on this machine',{exact:true}).click();await panel.getByLabel('Recovery workspace ID',{exact:true}).fill('workspace-one');await panel.getByLabel('Recovery editor ID',{exact:true}).fill('new-editor');await panel.getByRole('button',{name:'Preview Cloud recovery',exact:true}).click();await expect(panel).toContainText('247 knowledge articles');await expect(panel).toContainText('read-only for this editor');await expect(panel.getByRole('button',{name:'Recover verified checkpoint',exact:true})).toBeDisabled();expect(apply).toBe(0);await panel.getByRole('checkbox').check();await panel.getByRole('button',{name:'Recover verified checkpoint',exact:true}).click();await expect(panel.getByRole('status').filter({hasText:'Knowledge sources need fresh verification'})).toBeVisible();expect(apply).toBe(1);
});

test('Cloud handoff proposal and recovered source verification use their explicit bounded routes',async({page})=>{
 const value=initial();await page.route('**/api/cloud-workspace',r=>r.fulfill({json:value}));let handoff,reads=0;await page.route('**/api/cloud-workspace/stage',r=>{handoff=r.request().postDataJSON();return r.fulfill({json:{snapshotHash:snapshot,status:'pending'}});});await page.route('**/api/official-documents',r=>r.fulfill({json:[{id:'DOC-test',cloudVerified:false}]}));await page.route('**/api/cloud-workspace/verify-sources',r=>{const input=r.request().postDataJSON();expect(input.sourceIds).toContain('DOC-test');expect(input.sourceIds.length).toBeLessThanOrEqual(32);reads++;return r.fulfill({json:{verified:input.sourceIds.length}});});
 await page.goto('/#connections');const panel=page.getByRole('region',{name:'Cloud workspace recovery'});await panel.getByLabel('Handoff to editor ID (optional)').fill('editor-two');await panel.getByRole('button',{name:'Prepare Cloud checkpoint',exact:true}).click();expect(handoff.nextOwnerId).toBe('editor-two');await expect(panel.getByRole('button',{name:/Verify recovered knowledge/})).toBeEnabled();await panel.getByRole('button',{name:/Verify recovered knowledge/}).click();await expect(panel.getByRole('status').filter({hasText:'source documents freshly verified'})).toBeVisible();expect(reads).toBe(1);
});


test('automatic checkpoint status shows whole-save estimate and only polls local status until verified',async({page})=>{
 let reads=0;const forbidden=[];const value=initial();value.status.automaticForecast={missingDocuments:2,reusedDocuments:3,totalReservationUSD:.35,note:'Two new documents plus bounded policy verification.'};
 await page.route('**/api/cloud-workspace',r=>{reads++;if(reads>=2)value.status={...value.status,status:'verified',snapshotHash:snapshot,activeOwnerId:owner,note:'Automatic save verified by readback.'};return r.fulfill({json:value});});
 await page.route('**/api/cloud-workspace/*',r=>{forbidden.push(r.request().url());return r.fulfill({status:500,json:{error:'No provider action should be triggered by the status panel'}});});
 await page.goto('/#connections');const panel=page.getByRole('region',{name:'Cloud workspace recovery'}),allowance=panel.getByRole('region',{name:'Cloud checkpoint allowance'});
 await expect(panel).toContainText('Committed saves automatically queue');await expect(allowance).toContainText('Remaining authorized credit$20.00');await expect(allowance).toContainText('Remaining ingestion allowance$8.00');await expect(allowance).toContainText('not billed charges');await expect(panel.getByRole('region',{name:'Automatic save estimate'})).toContainText('$0.35');
 await expect(panel).toContainText('Automatic save verified by readback.',{timeout:6000});const completedReads=reads;await page.waitForTimeout(3500);expect(reads).toBe(completedReads);expect(forbidden).toEqual([]);
});

test('insufficient allowance keeps the full save pending without invoking a paid route',async({page})=>{
 const value=initial(),actions=[];value.budget={authorized:true,reservedUSD:48.8,remainingUSD:.2,ingestionRemainingUSD:.1,note:'Only the existing authorized remainder is available.'};value.status.automaticForecast={missingDocuments:2,reusedDocuments:0,totalReservationUSD:.35,note:'Whole-save allowance required.'};
 await page.route('**/api/cloud-workspace',r=>r.fulfill({json:value}));await page.route('**/api/cloud-workspace/*',r=>{actions.push(r.request().url());return r.fulfill({status:409,json:{error:'Insufficient allowance'}});});
 await page.goto('/#connections');const panel=page.getByRole('region',{name:'Cloud workspace recovery'});await expect(panel.getByRole('region',{name:'Automatic save estimate'})).toContainText('This save exceeds its current authorization');await expect(panel).toContainText('Remaining authorized credit$0.20');await expect(panel).toContainText('Remaining ingestion allowance$0.10');await expect(panel).toContainText('pending');expect(actions).toEqual([]);
});

test('another active owner disables both preparing and publishing a pending checkpoint',async({page})=>{
 const value=initial(),actions=[];value.status.activeOwnerId='editor-two';value.pending=[{snapshotHash:snapshot,status:'pending',forecast:{uniqueDocuments:2,fullWriteReservationUSD:.3}}];
 await page.route('**/api/cloud-workspace',r=>r.fulfill({json:value}));await page.route('**/api/cloud-workspace/*',r=>{actions.push(r.request().url());return r.fulfill({status:409,json:{error:'Wrong owner'}});});
 await page.goto('/#connections');const panel=page.getByRole('region',{name:'Cloud workspace recovery'});await expect(panel.getByRole('button',{name:'Prepare Cloud checkpoint',exact:true})).toBeDisabled();await expect(panel.getByRole('button',{name:/Publish or check checkpoint/})).toBeDisabled();await expect(panel).toContainText('Another editor holds the active handoff');await panel.getByText('Recover on this machine',{exact:true}).click();await panel.getByLabel('Recovery workspace ID',{exact:true}).fill('workspace-one');await panel.getByLabel('Recovery editor ID',{exact:true}).fill('editor-one');await expect(panel.getByRole('button',{name:'Preview Cloud recovery',exact:true})).toBeEnabled();expect(actions).toEqual([]);
});
