import {test,expect} from '@playwright/test';
test('case → reviewed knowledge → later reuse → incompatible case',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await page.getByRole('button',{name:/^Cases/}).click();
 await expect(page.getByRole('heading',{name:'Case desk'})).toBeVisible();
 await page.getByRole('button',{name:'Prepare investigation',exact:true}).click();
 await expect(page.getByText('No approved experience recalled yet.',{exact:false})).toBeVisible();
 await expect(page.getByText('Which GitLab Runner version is installed?',{exact:true})).toBeVisible();
 await page.getByRole('tab',{name:'Overview'}).click();await page.getByRole('button',{name:'Record resolution',exact:false}).click();
 await page.getByRole('button',{name:'Reveal source outcome'}).click();
 await expect(page.locator('textarea[name="fix"]')).toHaveValue(/probeTimeoutSeconds/);
 await page.getByLabel('Confirmed by',{exact:true}).fill('Local test reviewer');await page.locator('dialog input[type="checkbox"]').check();
 await page.getByRole('button',{name:'Confirm outcome',exact:true}).click();
 await page.getByRole('button',{name:'Review knowledge draft',exact:true}).click();await page.getByLabel('Reviewed by',{exact:true}).fill('Local test reviewer');await page.locator('dialog input[type="checkbox"]').check();await page.getByRole('button',{name:'Approve article',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Shared knowledge'})).toBeVisible();await expect(page.getByText('Offline retention',{exact:true})).toBeVisible({timeout:12000});
 await page.getByRole('navigation',{name:'Workspace navigation'}).getByRole('button',{name:/^Cases/}).click();await page.locator('.case-row').filter({hasText:'CS-1043'}).click();
 await page.getByRole('button',{name:'Prepare investigation',exact:true}).click();await expect(page.getByText('Review applicability',{exact:true})).toBeVisible();
 await page.screenshot({path:'artifacts/lucid-memory-reuse.png',fullPage:true});
 await page.getByRole('button',{name:'Review reuse',exact:false}).click();await page.getByLabel('Applicability and successful outcome evidence').fill('Replayed public outcome; actual liveness behavior reviewed for this demonstration.');await page.getByLabel('Verified by',{exact:true}).fill('Local test reviewer');await page.locator('dialog input[type="checkbox"]').check();await page.getByRole('button',{name:'Link verified resolution'}).click();
 await expect(page.locator('.company-line').filter({hasText:'Anonymous public user B'})).toBeVisible();
 await page.getByRole('navigation',{name:'Workspace navigation'}).getByRole('button',{name:/^Cases/}).click();await page.locator('.case-row').filter({hasText:'CS-1044'}).click();await page.getByRole('button',{name:'Prepare investigation',exact:true}).click();await expect(page.getByText('Not applicable',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Review reuse',exact:false})).toHaveCount(0);
 const state=await (await page.request.get('/api/workspace')).json();expect(state.articles).toHaveLength(1);expect(state.outbox).toHaveLength(1);expect(state.cases.find(c=>c.id==='CS-1043').articleIds).toEqual(['KA-0001']);
 expect(errors).toEqual([]);
});
test('incident evidence, editable drafts and source links',async({page})=>{await page.goto('/');await page.getByRole('button',{name:/^Cases/}).click();await page.locator('.case-row').filter({hasText:'CS-1045'}).click();await page.getByRole('button',{name:'Prepare investigation',exact:true}).click();await page.getByRole('button',{name:'Review incident link'}).click();await page.getByLabel('Evidence supporting the link').fill('Same GitLab.com API host, service and 17:00 UTC time within the provider impact window.');await page.locator('dialog input[type="checkbox"]').check();await page.getByRole('button',{name:'Confirm incident link'}).click();await page.getByRole('tab',{name:'Drafts'}).click();await page.getByLabel('Customer reply',{exact:true}).fill('Reviewed customer draft. No message is sent.');await page.getByRole('button',{name:'Save draft changes'}).click();await page.reload();await page.getByRole('button',{name:/^Cases/}).click();await page.locator('.case-row').filter({hasText:'CS-1045'}).click();await page.getByRole('tab',{name:'Drafts'}).click();await expect(page.getByLabel('Customer reply',{exact:true})).toHaveValue('Reviewed customer draft. No message is sent.');await expect(page.locator('.evidence-rail a').first()).toHaveAttribute('href',/gitlab.com/);});
test('mobile layout and private onboarding form',async({page})=>{await page.setViewportSize({width:390,height:844});await page.goto('/');await page.getByRole('button',{name:/^Cases/}).click();await expect(page.getByRole('heading',{name:'Case desk'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.getByRole('button',{name:'New case',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);await page.screenshot({path:'artifacts/lucid-mobile.png',fullPage:true});await page.goto('/#connections');await expect(page.getByRole('heading',{name:'Connections',exact:true})).toBeVisible();await expect(page.getByLabel('Cloud API key',{exact:true})).toHaveAttribute('type','password');await expect(page.getByLabel('OpenAI API key',{exact:true})).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);});
test('new customer report retrieves references, edits evidence and supports keyboard tabs',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:/^Cases/}).click();await page.getByRole('button',{name:'New case',exact:true}).click();
 await page.getByLabel('Company',{exact:true}).fill('Example Review Team');await page.getByLabel('Contact name').fill('Local Reviewer');await page.getByLabel('Short case title').fill('Certificate verification blocks our new worker');await page.getByLabel('Customer report',{exact:true}).fill('Worker requests fail with x509 certificate signed by unknown authority. Need to identify the relevant trust store.');await page.getByRole('button',{name:'Create case',exact:true}).click();
 await expect(page.locator('.case-header h2')).toHaveText('Certificate verification blocks our new worker');await page.getByRole('button',{name:'Prepare investigation',exact:true}).click();await expect(page.getByRole('heading',{name:'Connection fails certificate verification'})).toBeVisible();
 await page.getByRole('tab',{name:'Investigation'}).focus();await page.keyboard.press('ArrowRight');await expect(page.getByRole('tab',{name:'Drafts'})).toBeFocused();await expect(page.getByLabel('Engineering brief')).toHaveValue(/tls-self-signed/);
 await page.getByRole('button',{name:'Edit',exact:true}).click();await page.getByLabel('Report and collected evidence').fill('The certificate error occurs during worker registration. The security team is checking the issuing CA.');await page.getByRole('button',{name:'Save environment'}).click();
 await page.getByRole('button',{name:'Library',exact:true}).click();await page.getByRole('button',{name:'Technical guides',exact:true}).click();await page.getByRole('textbox',{name:'Search references'}).fill('certificate');await expect(page.locator('.reference-card')).toHaveCount(1);await page.screenshot({path:'artifacts/lucid-references.png',fullPage:true});
});
test('new incident moves from proposed to confirmed and requires review after editing',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:/^Cases/}).click();await page.getByRole('button',{name:'Incidents',exact:true}).click();await page.getByRole('button',{name:'New incident',exact:true}).click();
 await page.getByLabel('Incident title',{exact:true}).fill('Local build API disruption');await page.getByLabel('Incident hosting').selectOption('Self-managed');await page.getByLabel('Affected host',{exact:true}).fill('ci.example.test');await page.getByLabel('Affected services').fill('API');await page.getByLabel('Impact start').fill('2026-09-27T09:00:00Z');await page.getByLabel('Impact end or observed through').fill('2026-09-27T10:00:00Z');await page.getByLabel('Incident evidence').fill('Monitoring and repeated requests show HTTP 503 during the recorded window.');await page.getByLabel('Incident recorded by').fill('Local reviewer');await page.locator('dialog input[type="checkbox"]').check();await page.getByRole('button',{name:'Create incident',exact:true}).click();
 await page.getByRole('navigation',{name:'Workspace navigation'}).getByRole('button',{name:/^Cases/}).click();await page.getByRole('button',{name:'New case',exact:true}).click();await page.getByLabel('Company',{exact:true}).fill('Incident Review Team');await page.getByLabel('Contact name').fill('Example Reporter');await page.getByLabel('Short case title').fill('Our local API returns 503');await page.getByLabel('Customer report',{exact:true}).fill('API requests failed during our morning deployment.');await page.getByRole('button',{name:'Create case',exact:true}).click();
 await page.getByRole('button',{name:'Edit',exact:true}).click();await page.getByLabel('Hosting',{exact:true}).selectOption('Self-managed');await page.getByLabel('Affected hostname').fill('ci.example.test');await page.getByLabel('Affected service',{exact:true}).fill('API');await page.getByLabel('Failure time (ISO 8601, with timezone)').fill('2026-09-27T09:30:00Z');await page.getByRole('button',{name:'Save environment'}).click();await page.getByRole('button',{name:'Prepare investigation',exact:true}).click();await page.getByRole('button',{name:'Review incident link'}).click();await page.getByLabel('Evidence supporting the link').fill('Same self-managed host and API service; request timestamp is inside the observed window.');await page.locator('dialog input[type="checkbox"]').check();await page.getByRole('button',{name:'Confirm incident link'}).click();
 await page.getByRole('button',{name:'Incidents',exact:true}).click();const card=page.locator('.article-card').filter({has:page.getByRole('heading',{name:'Local build API disruption'})});await expect(card.getByText('Confirmed',{exact:true})).toBeVisible();await card.getByRole('button',{name:'Edit incident'}).click();await page.getByLabel('Incident evidence').fill('Updated evidence narrows the impact to a specific maintenance event.');await page.getByLabel('Incident recorded by').fill('Second reviewer');await page.locator('dialog input[type="checkbox"]').check();await page.getByRole('button',{name:'Save incident',exact:true}).click();await expect(card.getByText('Needs review',{exact:true})).toBeVisible();await expect(card.getByText('Revision 2',{exact:true})).toBeVisible();
 const state=await (await page.request.get('/api/workspace')).json();const c=state.cases.find(c=>c.title==='Our local API returns 503');expect(c.incidentIds).toEqual([]);expect(c.incidentLinks[0].state).toBe('needs-review');await page.screenshot({path:'artifacts/lucid-incident-review.png',fullPage:true});
});

test('research catalog exposes provenance and keeps heldouts out of operational replay',async({page})=>{await page.goto('/');await page.getByRole('button',{name:/^Cases/}).click();await page.getByRole('button',{name:'Library',exact:true}).click();await page.getByText('Advanced',{exact:true}).click();await page.getByRole('button',{name:'Replay & evaluation'}).click();await expect(page.getByText('30 public reports · 7 held out')).toBeVisible();const heldout=page.locator('article').filter({hasText:'Windows PowerShell job fails parsing generated variables'});await expect(heldout.getByText('Heldout evaluation')).toBeVisible();await expect(heldout.getByRole('button',{name:'Open research replay'})).toHaveCount(0);await page.getByText('Import reviewed reports',{exact:true}).click();await expect(page.getByLabel('Reviewed report JSON')).toBeVisible();await page.getByLabel('Reviewed report JSON').fill('{"records":[]}');await page.getByRole('button',{name:'Preview import'}).click();await expect(page.getByRole('status')).toContainText('Check required fields and valid values.');});

test('service console example, company studies, guide categories and source reader are usable',async({page})=>{
 await page.goto('/');await expect(page.getByRole('heading',{name:'Case desk'})).toBeVisible();await page.getByRole('button',{name:'Example investigation'}).click();await expect(page.getByRole('heading',{name:'Follow the evidence'})).toBeVisible();await expect(page.getByRole('link',{name:/original postmortem/})).toHaveAttribute('href','https://blog.cloudflare.com/details-of-the-cloudflare-outage-on-july-2-2019/');
 await expect(page.getByRole('navigation',{name:'Workspace navigation'}).getByRole('button',{name:'Companies',exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Library',exact:true}).click();await page.getByRole('button',{name:'Incident studies · 16'}).click();await page.getByLabel('Search companies').fill('Roblox');await expect(page.locator('.company-feature')).toHaveCount(1);await expect(page.locator('.company-feature')).toContainText('HashiCorp');
 await page.getByRole('button',{name:'Library',exact:true}).click();await page.getByLabel('Search public reports').fill('certificate');await expect(page.locator('.report-row').first()).toBeVisible();const row=page.locator('.report-row').first();await row.click();await expect(page.getByRole('dialog',{name:'Public source report'})).toBeVisible();await page.getByRole('dialog').getByText('Original issue report',{exact:true}).click();await expect(page.getByRole('dialog').locator('pre').first()).not.toHaveText('Loading report…');await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);await expect(row).toBeFocused();
 await page.getByRole('button',{name:'Technical guides',exact:true}).click();await expect(page.locator('.reference-card')).toHaveCount((await (await page.request.get('/api/references')).json()).length);await page.getByRole('button',{name:'Incident studies · 16'}).click();await expect(page.locator('.company-feature')).toHaveCount(16);
});

test('selected local public evidence persists and is cited without using paid actions',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:/^Cases/}).click();await page.getByRole('button',{name:'New case',exact:true}).click();await page.getByLabel('Company',{exact:true}).fill('Evidence Review Team');await page.getByLabel('Contact name').fill('Local Reviewer');await page.getByLabel('Short case title').fill('A certificate blocks helper registration');await page.getByLabel('Customer report',{exact:true}).fill('The helper fails TLS verification with x509 certificate signed by unknown authority.');await page.getByRole('button',{name:'Create case',exact:true}).click();
 await page.getByText('Find relevant public reports',{exact:true}).click();await expect(page.locator('.evidence-suggestion').first()).toBeVisible();await page.locator('.evidence-suggestion').first().getByRole('button',{name:'Select evidence'}).click();await expect(page.locator('.selected-source')).toHaveCount(1);await expect(page.getByLabel('Use Hindsight · credit')).not.toBeChecked();await page.getByRole('button',{name:'Prepare investigation',exact:true}).click();await expect(page.getByText('Unreviewed source report',{exact:true})).toBeVisible();await page.getByRole('tab',{name:'Drafts'}).click();await expect(page.getByLabel('Engineering brief')).toHaveValue(/SRC-gitlab-runner-/);await expect(page.getByLabel('Engineering brief')).toHaveValue(/not a confirmed fix/);
 const state=await(await page.request.get('/api/workspace')).json(),c=state.cases.find(x=>x.title==='A certificate blocks helper registration');expect(c.publicEvidence).toHaveLength(1);expect(c.publicEvidence[0].summary.length).toBeLessThanOrEqual(700);expect(c.analysis.modelResult).toBeNull();expect(c.resolution).toBeNull();await page.reload();await page.getByRole('button',{name:/^Cases/}).click();await page.locator('.case-row').filter({hasText:c.id}).click();await expect(page.locator('.selected-source')).toHaveCount(1);
});

test('public report HTML is displayed as inert source text',async({page})=>{const malicious='<img src=x onerror="window.lucidInjected=true"><script>window.lucidInjected=true</script>';await page.route('**/api/evidence?*',route=>route.fulfill({json:{rows:[{id:'safe-fixture',title:malicious,excerpt:malicious,family:'Example',kind:'Bug report',review_status:'indexed',created_at:'2024-01-01',state:'closed',url:'https://gitlab.com/gitlab-org/gitlab-runner/-/issues/1'}],total:1,page:1,pages:1}}));await page.route('**/api/evidence/safe-fixture',route=>route.fulfill({json:{body:malicious}}));await page.goto('/');await page.getByRole('button',{name:'Library',exact:true}).click();await page.locator('.report-row').click();await page.getByRole('dialog').getByText('Original issue report',{exact:true}).click();await expect(page.getByRole('dialog').locator('pre').first()).toHaveText(malicious);expect(await page.evaluate(()=>window.lucidInjected)).toBeUndefined();await expect(page.getByRole('dialog').locator('img,script')).toHaveCount(0);});

test('failed local evidence requests show errors instead of endless loading',async({page})=>{await page.route('**/api/evidence?*',route=>route.fulfill({json:{rows:[{id:'error-fixture',title:'Example report',excerpt:'Local test fixture',family:'Example',kind:'Bug report',review_status:'indexed',created_at:'2024-01-01',state:'closed',url:'https://gitlab.com/gitlab-org/gitlab-runner/-/issues/1'}],total:1,page:1,pages:1}}));await page.route('**/api/evidence/error-fixture',route=>route.fulfill({status:502,json:{error:'Example unavailable report'}}));await page.route('**/api/cases/*/evidence',route=>route.fulfill({status:502,json:{error:'Example unavailable index'}}));await page.goto('/');await page.getByRole('button',{name:'Library',exact:true}).click();await page.locator('.report-row').click();await expect(page.getByRole('dialog').getByRole('alert').filter({hasText:'This local report'})).toContainText('could not be loaded');await expect(page.getByRole('dialog').getByRole('link',{name:/Open original/})).toHaveAttribute('href',/gitlab.com/);await expect(page.getByRole('dialog').locator('pre')).toHaveCount(0);await page.keyboard.press('Escape');await page.getByRole('button',{name:/^Cases/}).click();await page.getByText('Find relevant public reports',{exact:true}).click();await expect(page.locator('.case-evidence').getByRole('alert')).toContainText('could not be loaded');});

test('assignment, observed steps and public-source investigations persist without confirming knowledge',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'Library',exact:true}).click();
 await page.getByLabel('Search public reports').fill('certificate');await page.locator('.report-row').first().click();
 const sourceTitle=await page.getByRole('dialog',{name:'Public source report'}).locator('h2').textContent();
 await page.getByRole('button',{name:'Open historical investigation',exact:true}).click();
 await expect(page.locator('.case-header h2')).toHaveText(sourceTitle);
 let workspace=await(await page.request.get('/api/workspace')).json();const sourceCase=workspace.cases.find(c=>c.evidenceReportId);
 expect(sourceCase).toBeTruthy();expect(sourceCase.resolution).toBeNull();expect(sourceCase.executor).toBe('Unknown');
 const articleCount=workspace.articles.length,outboxCount=workspace.outbox.length;
 await page.getByRole('button',{name:'Edit',exact:true}).click();
 await page.getByLabel('Case owner',{exact:true}).fill('Local review owner');await page.getByLabel('Priority',{exact:true}).selectOption('High');
 await page.getByRole('button',{name:'Save environment',exact:true}).click();
 await page.getByRole('tab',{name:'Investigation',exact:true}).click();
 await page.getByLabel('Next investigation step').fill('Inspect the certificate chain from the affected helper');await page.getByRole('button',{name:'Add step',exact:true}).click();
 const step=page.locator('.task-list li').filter({hasText:'Inspect the certificate chain'});
 await step.getByRole('button',{name:'Record result',exact:true}).click();await expect(step.getByRole('button',{name:'Complete step',exact:true})).toBeDisabled();
 await page.getByLabel('Observed step result').fill('The issuing CA is absent from the helper trust store. No change has been verified.');await step.getByRole('button',{name:'Complete step',exact:true}).click();
 await expect(step.getByRole('button',{name:'Reopen',exact:true})).toBeVisible();
 await page.reload();await page.locator('.case-row').filter({hasText:sourceCase.id}).click();
 await expect(page.locator('.record-highlights')).toContainText('Local review owner');await expect(page.locator('.record-highlights')).toContainText('High');
 await page.getByRole('tab',{name:'Investigation',exact:true}).click();await expect(page.locator('.task-list')).toContainText('issuing CA is absent');
 workspace=await(await page.request.get('/api/workspace')).json();const saved=workspace.cases.find(c=>c.id===sourceCase.id);
 expect(saved.tasks[0].completed).toBe(true);expect(saved.resolution).toBeNull();expect(saved.status).toBe('Open');expect(workspace.articles).toHaveLength(articleCount);expect(workspace.outbox).toHaveLength(outboxCount);
 const repeated=await page.request.post(`/api/evidence/${sourceCase.evidenceReportId}/open`,{headers:{'x-lucid-local':'1'},data:{}});expect(repeated.status()).toBe(201);expect((await repeated.json()).id).toBe(sourceCase.id);
});

test('theme follows system initially and explicit light or dark choice persists',async({page})=>{
 await page.emulateMedia({colorScheme:'dark',reducedMotion:'reduce'});await page.goto('/');
 await expect(page.getByLabel('Color theme',{exact:true})).toHaveValue('system');await expect(page.locator('html')).toHaveAttribute('data-theme','dark');
 await page.getByLabel('Color theme',{exact:true}).selectOption('light');await expect(page.locator('html')).toHaveAttribute('data-theme','light');
 await page.reload();await expect(page.getByLabel('Color theme',{exact:true})).toHaveValue('light');await expect(page.locator('html')).toHaveAttribute('data-theme','light');
 await page.getByRole('button',{name:'Knowledge',exact:true}).click();await expect(page.locator('html')).toHaveAttribute('data-theme','light');
 await page.getByLabel('Color theme',{exact:true}).selectOption('dark');await page.reload();await expect(page.getByLabel('Color theme',{exact:true})).toHaveValue('dark');await expect(page.locator('html')).toHaveAttribute('data-theme','dark');
 await page.getByLabel('Color theme',{exact:true}).selectOption('system');await page.emulateMedia({colorScheme:'light'});await expect(page.locator('html')).toHaveAttribute('data-theme','light');
});

test('historical cases live inside the console and open one separate investigation',async({page})=>{
 const before=await(await page.request.get('/api/workspace')).json();
 await page.goto('/#cases/history?q=1059');
 await expect(page.getByRole('navigation',{name:'Case queue views'})).toContainText('Historical cases 3');
 await expect(page.locator('.history-case-row')).toHaveCount(1);
 const title=await page.locator('.history-record-header h2').textContent();
 await expect(page.getByRole('tab',{name:'Report',exact:true})).toHaveAttribute('aria-selected','true');
 await expect(page.locator('.history-report-text')).toContainText('certificate');
 await page.getByRole('tab',{name:'Evidence',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Discussion pending',exact:true})).toBeVisible();
 await page.reload();await expect(page.getByLabel('Search historical cases')).toHaveValue('1059');
 await page.locator('.history-record-actions .source-open-action button').click();
 await expect(page.locator('.case-header h2')).toHaveText(title);
 const once=await(await page.request.get('/api/workspace')).json();const selected=once.cases.find(c=>c.title===title);expect(selected.resolution).toBeNull();expect(once.articles.length).toBe(before.articles.length);expect(once.outbox.length).toBe(before.outbox.length);
 await page.getByRole('navigation',{name:'Case queue views'}).getByRole('button',{name:/Historical cases/}).click();await page.getByLabel('Search historical cases').fill('1059');await expect(page.locator('.history-case-row')).toHaveCount(1);await page.getByRole('button',{name:'Continue investigation',exact:true}).click();
 const twice=await(await page.request.get('/api/workspace')).json();expect(twice.cases.length).toBe(once.cases.length);expect(twice.articles.length).toBe(before.articles.length);
});
