import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,statSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {Store} from '../server/db.js';import {createApp} from '../server/app.js';import {configuration} from '../server/providers.js';import {CloudSettings} from '../server/settings.js';
import {isAuditQuery,auditResponseFor} from './fixtures/hindsight-audit.js';
import {officialDocumentFixture} from './fixtures/official-document.js';
async function harness(t,dependencies={},config=configuration({})){const store=new Store(':memory:');const {app,worker}=createApp(store,config,dependencies);const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const url=`http://127.0.0.1:${server.address().port}`;t.after(async()=>{await worker.run();await new Promise(r=>server.close(r));store.close();});async function request(path,body,method='POST',headers={}){const r=await fetch(url+'/api'+path,{method,headers:{'content-type':'application/json','x-lucid-local':'1',...headers},...(body!==undefined?{body:JSON.stringify(body)}:{})});return {status:r.status,body:await r.json()};}return {store,request,url};}
test('baseline excludes learned articles and hidden outcomes from drafting',async t=>{let context;const {store,request}=await harness(t,{draft:async(c,ticket,candidates,useMemory)=>{context={ticket,candidates,useMemory};return {customer:'draft',engineering:'draft',provider:'test'};}});store.update(s=>s.articles.push({id:'SECRET-ARTICLE',fix:'withheld outcome'}));const r=await request('/cases/CS-1043/analyze',{useMemory:false});assert.equal(r.status,200);assert.equal(context.candidates.length,0);assert.equal(JSON.stringify(context).includes('probeTimeoutSeconds'),false);assert.equal(context.ticket.companyId,'org-b');});
test('API validates input and CSRF origin',async t=>{const {request}=await harness(t);assert.equal((await request('/cases',{title:'x'})).status,400);assert.equal((await request('/cases',{},'POST',{'x-lucid-local':'0'})).status,403);assert.equal((await request('/cases',{},'POST',{origin:'https://attacker.example'})).status,403);assert.equal((await request('/cases/nope/analyze',{useMemory:true})).status,404);});
test('new case company association and edited drafts persist',async t=>{const {request}=await harness(t);const r=await request('/cases',{companyName:'Example Company',contact:'Test person',title:'Cannot start a job',description:'This is a locally entered test case.'});assert.equal(r.status,201);const id=r.body.id;assert.equal((await request(`/cases/${id}/drafts`,{customer:'Edited customer response',engineering:'Edited engineering brief'},'PUT')).status,200);const s=(await request('/workspace',undefined,'GET')).body;assert.equal(s.companies.find(o=>o.id===r.body.companyId).name,'Example Company');assert.equal(s.cases.find(c=>c.id===id).drafts.customer,'Edited customer response');});
test('context mutation while provider is busy invalidates stale analysis',async t=>{let release;const hold=new Promise(r=>release=r);const {store,request}=await harness(t,{draft:async()=>{await hold;return {customer:'stale',engineering:'stale'};}});const pending=request('/cases/CS-1042/analyze',{useMemory:false});await new Promise(r=>setTimeout(r,30));store.update(s=>s.cases[0].runnerVersion='changed');release();assert.equal((await pending).status,409);});
test('local credential save never exposes secrets or calls provider',async t=>{const dir=mkdtempSync(join(tmpdir(),'lucid-settings-')),file=join(dir,'secret.json'),settings=new CloudSettings(file);const {request}=await harness(t,{settings});t.after(()=>rmSync(dir,{recursive:true,force:true}));const key='fake-test-key-not-a-real-credential';const r=await request('/cloud-settings',{baseUrl:'https://api.hindsight.vectorize.io',bank:'actual-user-bank',apiKey:key},'PUT');assert.equal(r.status,200);assert.equal(statSync(file).mode&0o777,0o600);const state=await request('/cloud-settings',undefined,'GET');assert.equal(JSON.stringify(state).includes(key),false);assert.equal(state.body.bank,'actual-user-bank');assert.equal(state.body.lastResult,null);assert.equal((await request('/cloud-settings',{baseUrl:'http://127.0.0.1:1234',bank:'test',apiKey:key},'PUT')).status,400);});
test('legacy paid paths and OpenAI settings cannot dispatch provider calls',async t=>{let calls=0;const forbidden=async()=>{calls++;throw new Error('must not dispatch');};const {request}=await harness(t,{settings:{status:()=>({configured:true}),test:forbidden},openai:{status:()=>({configured:true}),test:forbidden,investigate:forbidden},cloudWorkflow:{retain:forbidden,retryRetention:forbidden,retireOlder:forbidden,reflect:forbidden}});for(const path of ['/articles/KA-0001/retain-cloud','/articles/KA-0001/retry-cloud','/articles/KA-0001/retire-cloud','/cases/CS-1042/reflection','/cloud-settings/test'])assert.equal((await request(path,{expectedRevision:1,acknowledgeCreditUse:true,confirmed:true})).status,410);assert.equal((await request('/openai-settings/test',{acknowledgeCreditUse:true})).status,404);assert.equal((await request('/openai-settings',undefined,'GET')).status,404);assert.equal(calls,0);});
test('actual Hindsight backend publishes scoped baseline drafts and hides raw requests',async t=>{
 const calls=[],reservations=[];
 const client={listDirectives:async()=>{calls.push('directives');return {total:0,items:[]};},reflect:async(bank,query,options)=>{calls.push(isAuditQuery(query)?'audit':'reflect');assert.equal(bank,'test-bank');assert.equal(options.budget,'mid');assert.equal(options.tags,undefined);assert.deepEqual(options.tagGroups[0].tags,options.tagGroups[1].not.tags);const response={text:'Internal generated draft',structured_output:{finding:'More evidence needed',customer:'Please share the exact error.',engineering:'No cause established.',citations:[],nextQuestions:['What was observed?']},based_on:{memories:[],mental_models:[],directives:[]},trace:{tool_calls:[],llm_calls:[{scope:'final',duration_ms:1}]}};return isAuditQuery(query)?auditResponseFor(query,response):response;}};
 const provider={c:{memoryMode:'hindsight',bank:'test-bank'},scope:()=> 'lucid-workspace-api-test',getClient:()=>client};
 const cloud={provider:()=>provider,connectionId:()=> 'connection-test',retentionView:a=>a.cloudRetention};
 const {request,store}=await harness(t,{settings:{status:()=>({configured:true})},cloudWorkflow:cloud,authorizeHindsight:async op=>{reservations.push(op.kind);return {complete:async()=>calls.push('complete')};}});
 assert.equal((await request('/cases/CS-1042/analyze',{useMemory:false,useHindsight:true})).status,400);assert.deepEqual(calls,[]);
 const result=await request('/cases/CS-1042/analyze',{useMemory:false,useHindsight:true,searchDepth:'mid',acknowledgeCreditUse:true});assert.equal(result.status,200);assert.match(result.body.drafts.customer,/Which component produced the recorded response/);assert.ok(!result.body.drafts.customer.includes('Please share the exact error.'));assert.match(result.body.analysis.provider,/Hindsight/);assert.equal(result.body.analysis.modelResult.searchDepth,'mid');assert.equal(result.body.resolution,null);assert.deepEqual(reservations,['investigation-metadata','investigation-reflect','investigation-audit']);assert.equal(store.read().hindsightInvestigations[0].status,'succeeded');const snapshot=(await request('/workspace',undefined,'GET')).body;assert.equal(snapshot.hindsightInvestigations,undefined);assert.equal(JSON.stringify(snapshot).includes('Case and evidence data follow'),false);assert.equal(snapshot.config.agentMode,'hindsight-on-demand');
});
test('Hindsight failure keeps prior drafts and never falls back to a local or OpenAI generator',async t=>{let fallbacks=0;const {request,store}=await harness(t,{hindsightInvestigation:{investigate:async()=>{throw new Error('provider unavailable');}},draft:async()=>{fallbacks++;},openai:{investigate:async()=>{fallbacks++;}}});store.update(s=>{s.cases[0].drafts={customer:'Keep my reply',engineering:'Keep my notes',provider:'Human-edited draft'};});const result=await request('/cases/CS-1042/analyze',{useMemory:false,useHindsight:true,acknowledgeCreditUse:true});assert.equal(result.status,502);assert.equal(fallbacks,0);assert.equal(store.read().cases[0].drafts.customer,'Keep my reply');});
test('actual mandatory audit failure preserves edited drafts and hides the candidate from API snapshots',async t=>{
 const calls=[],client={listDirectives:async()=>({total:0,items:[]}),reflect:async(_bank,query)=>{calls.push(isAuditQuery(query)?'audit':'candidate');if(isAuditQuery(query))throw new Error('Audit unavailable');return {text:'PRIVATE_FIRST_CANDIDATE',structured_output:{finding:'Unknown.',customer:'PRIVATE_CANDIDATE_ADVICE',engineering:'Private proposed explanation.',citations:[],nextQuestions:[]},based_on:{memories:[],mental_models:[],directives:[]},trace:{tool_calls:[],llm_calls:[]}};}};
 const provider={c:{memoryMode:'hindsight',bank:'test-bank'},scope:()=> 'lucid-workspace-api-test',getClient:()=>client},cloud={provider:()=>provider,connectionId:()=> 'connection-test',retentionView:a=>a.cloudRetention};
 const {request,store}=await harness(t,{settings:{status:()=>({configured:true})},cloudWorkflow:cloud,authorizeHindsight:async()=>({complete:async()=>{},fail:async()=>{}})});
 store.update(s=>{s.cases[0].drafts={customer:'Keep my reply',engineering:'Keep my notes',provider:'Human-edited draft'};});
 const response=await request('/cases/CS-1042/analyze',{useMemory:false,useHindsight:true,acknowledgeCreditUse:true});assert.equal(response.status,502);assert.deepEqual(calls,['candidate','audit']);assert.equal(store.read().cases[0].drafts.customer,'Keep my reply');assert.equal(store.read().hindsightInvestigations[0].candidate.customer,'PRIVATE_CANDIDATE_ADVICE');assert.equal(store.read().hindsightInvestigations[0].result,undefined);
 const snapshot=(await request('/workspace',undefined,'GET')).body;assert.ok(!JSON.stringify(snapshot).includes('PRIVATE_CANDIDATE'));assert.equal(snapshot.hindsightInvestigations,undefined);
});
test('read-only Cloud status also passes through the shared authorization hook',async t=>{const calls=[],cloud={connectionId:()=> 'connection-a',checkRetention:async()=>{calls.push('status');return {status:'succeeded'};}};const blocked=await harness(t,{cloudWorkflow:cloud});assert.equal((await blocked.request('/articles/KA-0001/cloud-status',{expectedRevision:1})).status,409);assert.deepEqual(calls,[]);const allowed=await harness(t,{cloudWorkflow:cloud,authorizeHindsight:async operation=>{assert.equal(operation.kind,'investigation-metadata');assert.equal(operation.request.action,'retention-status');calls.push('reserve');return {complete:()=>calls.push('complete')};}});assert.equal((await allowed.request('/articles/KA-0001/cloud-status',{expectedRevision:1})).status,200);assert.deepEqual(calls,['reserve','status','complete']);});

test('environment provider flags do not mislabel local preparation or create an active paid path',async t=>{const {request}=await harness(t,{},configuration({MEMORY_MODE:'hindsight',AGENT_MODE:'openai-compatible',ALLOW_EXTERNAL_CALLS:'true'}));const snapshot=(await request('/workspace',undefined,'GET')).body;assert.equal(snapshot.config.memoryMode,'offline');assert.equal(snapshot.config.agentMode,'offline');assert.equal(snapshot.config.externalEnabled,false);const result=await request('/cases/CS-1042/analyze',{useMemory:false});assert.equal(result.status,200);assert.match(result.body.drafts.provider,/no AI model/);});

test('official-document API exposes exact source sections and DOC contributions without retention or audit records',async t=>{
 let fixture,providerCalls=0,investigations=0;
 const cloud={connectionId:()=>fixture.connectionId,retentionView:a=>a.cloudRetention,provider:()=>{providerCalls++;throw new Error('No provider may be started by this display test.');}};
 const engine={investigate:async()=>{investigations++;return {finding:'The exact-version source supplies a check, not a confirmed diagnosis.',customer:'Inspect the complete chain.',engineering:'Review the documented conditions.',provider:'Hindsight Reflect · offline test double',evidenceIds:[fixture.document.id],citations:[fixture.document.id],nextQuestions:[],evidenceSelection:{omitted:[],rejected:[]},provenance:{readCount:1,records:[fixture.record]},trace:{tool_calls:[],llm_calls:[]}};}};
 const {request,store}=await harness(t,{cloudWorkflow:cloud,hindsightInvestigation:engine});
 store.update(s=>{s.workspaceId='official-api-isolated';});fixture=officialDocumentFixture({workspaceId:store.read().workspaceId});
 store.update(s=>{s.officialDocuments=[fixture.document];s.hindsightInvestigations=[{id:'private-test',phases:[{request:'PRIVATE_INVESTIGATION_REQUEST',response:'PRIVATE_INVESTIGATION_RESPONSE'}]}];s.hindsightDerived=[{id:'private-derived',plan:{sourceQuery:'PRIVATE_DERIVED_REQUEST'}}];const c=s.cases.find(c=>c.id==='CS-1042');c.runnerVersion='19.3.0';c.hosting='Self-managed';});
 const response=await request('/official-documents',undefined,'GET');assert.equal(response.status,200);assert.deepEqual(response.body,[fixture.publicDocument]);assert.equal(response.body[0].sectionText,fixture.document.sectionText);assert.equal(response.body[0].cloudVerified,true);
 const snapshot=(await request('/workspace',undefined,'GET')).body;assert.equal(snapshot.officialDocuments,undefined);assert.equal(snapshot.hindsightInvestigations,undefined);assert.equal(snapshot.hindsightDerived,undefined);
 for(const text of [JSON.stringify(response.body),JSON.stringify(snapshot)])for(const hidden of ['PRIVATE_','cloudRetention','cloudScope','packet_hash'])assert.ok(!text.includes(hidden));
 const analyzed=await request('/cases/CS-1042/analyze',{useMemory:true,useHindsight:true,searchDepth:'high',acknowledgeCreditUse:true});assert.equal(analyzed.status,200);
 const ref=analyzed.body.analysis.references.find(r=>r.id===fixture.document.id);assert.equal(ref.kind,'official-document');assert.equal(ref.summary,fixture.document.sectionText);assert.equal(ref.versions,'runner 19.3.0 (exact source release)');assert.equal(ref.url,fixture.document.url);assert.equal(ref.reviewBasis,undefined);
 const contribution=analyzed.body.analysis.modelResult.provenance.records[0];assert.equal(contribution.sourceId,fixture.document.id);assert.equal(contribution.articleId,undefined);assert.equal(contribution.sourceType,'official-document');assert.equal(contribution.version,'19.3.0');assert.equal(contribution.url,fixture.document.url);assert.equal(providerCalls,0);assert.equal(investigations,1);
 store.update(s=>s.officialDocuments[0].sectionText+=' Changed without a new fingerprint.');assert.equal((await request('/official-documents',undefined,'GET')).body[0].cloudVerified,false);
});
