import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {canonicalWorkspace,buildCloudWorkspaceSnapshot,inspectWorkspaceManifests,CloudWorkspaceArchive,ARCHIVE_DOCUMENT_BYTES} from '../server/cloud-workspace.js';
const sha=value=>createHash('sha256').update(value).digest('hex');
function fixture(){
 let state={workspaceId:'archive-fixture',companies:[{id:'org',name:'A fixture company'}],cases:[{id:'case',title:'A case',description:'The job failed.',timeline:[{at:'2026-09-29',text:'Prior diagnostic recorded'}],attempts:[{step:'Restart',result:'Failed',evidence:'No improvement'}],drafts:{customer:'An unsent authored draft'},analysis:{rawResponse:'private analysis excluded'}}],articles:[{id:'KA-0001',title:'A reviewed article',revision:2,fingerprint:'a'.repeat(64),fix:'Reviewed recovery',citations:[{quote:'Did not work on the other version.'}],history:[{id:'KA-0001',revision:1,fix:'Older reviewed recovery',cloudScope:{verified:true}}],cloudRetention:{status:'succeeded',connectionId:'prior'},cloudScope:{verified:true},cloudHistory:[{docId:'old-proof'}]}],officialDocuments:[{id:'DOC-EXACT',sectionText:'Full official text',cloudScope:{verified:true}}],historicalKnowledgeAssociations:[],incidents:[],events:[],outbox:[{id:'local-outbox',status:'simulated'}],credentials:{apiKey:'DO-NOT-ARCHIVE'},budgetLedger:{capUSD:50},hindsightInvestigations:[{raw:'RAW-EVALUATION'}],hiddenRubrics:{answer:'hidden'}};
 const store={read:()=>structuredClone(state),update:fn=>{const next=structuredClone(state),result=fn(next);state=next;return result;}},docs=new Map(),calls=[],controls={connection:'test-connection',delay:false,failRetain:false,hook:null,policy:{total:0,items:[]}},reservations=[];
 const transport={listDocuments:async(bank,query)=>{calls.push({kind:'list',query});await controls.hook?.('list');const items=[...docs.values()].filter(d=>d.tags.includes('kind:workspace-manifest')).map(d=>({id:d.id}));return {items,total:items.length,limit:128,offset:0};},getDocument:async(bank,id)=>{calls.push({kind:'get',id});await controls.hook?.('get');return structuredClone(docs.get(id)||null);},listMentalModels:async()=>{calls.push({kind:'policy'});return controls.policy;},retain:async(bank,content,options)=>{calls.push({kind:'retain',content,options});const pending=store.read().cloudWorkspaceSnapshots;assert.ok(Object.values(pending).some(r=>Object.values(r.documents).some(d=>d.operationId===options.operationId&&d.attempts===1)));await controls.hook?.('retain');if(controls.failRetain)throw Error('private upstream detail');const doc={id:options.documentId,bank_id:bank,original_text:content,tags:options.tags,document_metadata:options.metadata,memory_unit_count:0};if(!controls.delay)docs.set(doc.id,doc);return {async:true,operation_id:options.operationId};}};
 const service=(ownerId='owner-a')=>new CloudWorkspaceArchive(store,transport,{workspaceId:state.workspaceId,bank:'archive-bank',ownerId,connectionId:()=>controls.connection,authorize:async request=>{reservations.push(request);return {complete:async()=>{},fail:async()=>{}};},now:()=> '2026-09-29T12:00:00Z',wait:async()=>{}});
 const plan=(options={})=>buildCloudWorkspaceSnapshot(store.read(),{ownerId:'owner-a',createdAt:'2026-09-29T12:00:00Z',...options});return {store,docs,calls,controls,reservations,service,plan};
}
function cloudDocument(doc){return {id:doc.docId,bank_id:'archive-bank',original_text:doc.content,tags:doc.tags,document_metadata:doc.metadata,memory_unit_count:0};}
test('archive projection preserves canonical articles, old revisions and case history while excluding proofs and authority',()=>{
 const x=fixture(),before=x.store.read(),body=canonicalWorkspace(before);assert.deepEqual(body.cases[0].attempts,before.cases[0].attempts);assert.deepEqual(body.cases[0].timeline,before.cases[0].timeline);assert.deepEqual(body.cases[0].drafts,before.cases[0].drafts);assert.equal(body.articles[0].history[0].fix,'Older reviewed recovery');assert.equal(body.articles[0].cloudScope,undefined);assert.equal(body.articles[0].history[0].cloudScope,undefined);assert.equal(body.articles[0].cloudHistory,undefined);assert.equal(body.cases[0].analysis,undefined);assert.ok(!JSON.stringify(body).includes('DO-NOT-ARCHIVE'));assert.ok(!JSON.stringify(body).includes('RAW-EVALUATION'));assert.equal(body.budgetLedger,undefined);assert.deepEqual(x.store.read(),before);
 x.store.update(s=>{s.cases[0].credentials={apiKey:'nested-secret'};});assert.throws(()=>x.plan(),/credential/);
});
test('compressed content addresses, byte limits and conservative reservation forecasts are deterministic',()=>{
 const x=fixture(),a=x.plan(),b=x.plan();assert.deepEqual(a,b);assert.equal(a.documents.length,2);assert.equal(a.forecast.fullWriteReservationUSD,.30);for(const doc of a.documents){assert.equal(sha(doc.content),doc.hash);assert.ok(doc.bytes<=ARCHIVE_DOCUMENT_BYTES);assert.ok(!doc.tags.some(t=>t.startsWith('lucid-workspace-')||t.startsWith('lucid-source:')));assert.equal(doc.metadata.source_type,'operational-archive');}assert.equal(a.manifest.chunks.length,1);assert.equal(a.manifest.parentHash,null);
 const changed=x.plan({nextOwnerId:'owner-b'});assert.notEqual(changed.snapshotHash,a.snapshotHash);assert.equal(changed.documents[0].hash,a.documents[0].hash);
});
test('pending cache becomes verified only after chunks, immutable root and unique head readback; recovery permits zero facts',async()=>{
 const x=fixture(),before=x.store.read(),plan=x.plan(),service=x.service();assert.equal(service.stage(plan).status,'pending');assert.equal(x.store.read().cloudWorkspaceStatus.status,'pending');const result=await service.publish(plan.snapshotHash);assert.equal(result.status,'verified');assert.equal(x.store.read().cloudWorkspaceStatus.status,'verified');assert.equal(x.calls.filter(c=>c.kind==='retain').length,2);assert.equal(x.calls.filter(c=>c.kind==='policy').length,1);assert.deepEqual(x.store.read().cases,before.cases);assert.deepEqual(x.store.read().articles,before.articles);
 const readsBefore=x.calls.filter(c=>c.kind==='get').length,recovered=await x.service().recover();assert.ok(x.calls.filter(c=>c.kind==='get').length>readsBefore);assert.equal(recovered.requiresSourceReverification,true);assert.equal(recovered.canEdit,true);assert.equal(recovered.state.articles[0].cloudScope,undefined);assert.equal(recovered.state.articles[0].cloudRetention,undefined);assert.equal(recovered.state.articles[0].sync,'unverified');assert.equal(recovered.state.articles[0].fingerprint,before.articles[0].fingerprint);assert.deepEqual(recovered.state.cases[0].timeline,before.cases[0].timeline);assert.equal(recovered.state.cloudWorkspaceSnapshots,undefined);
});
test('same checkpoint is idempotent; missing asynchronous readback never causes an uncertain write retry',async()=>{
 const x=fixture(),p=x.plan(),s=x.service();s.stage(p);x.controls.delay=true;let result=await s.publish(p.snapshotHash);assert.equal(result.status,'pending');assert.equal(x.calls.filter(c=>c.kind==='retain').length,1);assert.equal(x.store.read().cloudWorkspaceStatus.status,'pending');result=await x.service().publish(p.snapshotHash);assert.equal(result.status,'pending');assert.equal(x.calls.filter(c=>c.kind==='retain').length,1);
 x.docs.set(p.documents[0].docId,cloudDocument(p.documents[0]));x.controls.delay=false;assert.equal((await x.service().publish(p.snapshotHash)).status,'verified');const n=x.calls.filter(c=>c.kind==='retain').length;await x.service().publish(p.snapshotHash);assert.equal(x.calls.filter(c=>c.kind==='retain').length,n);
});
test('bounded delayed chunk and root readback complete in one invocation with one policy read and no resent writes',async()=>{
 const x=fixture(),p=x.plan();x.service().stage(p);x.controls.delay=true;let waits=0;
 const service=new CloudWorkspaceArchive(x.store,{listDocuments:async()=>({items:[...x.docs.values()].filter(d=>d.tags.includes('kind:workspace-manifest')).map(d=>({id:d.id})),total:[...x.docs.values()].filter(d=>d.tags.includes('kind:workspace-manifest')).length,offset:0}),getDocument:async(_bank,id)=>x.docs.get(id)||null,listMentalModels:async()=>{x.calls.push({kind:'policy'});return {total:0,items:[]};},retain:async(_bank,content,options)=>{x.calls.push({kind:'retain',content,options});return {async:true};}},{workspaceId:'archive-fixture',bank:'archive-bank',ownerId:'owner-a',connectionId:()=>x.controls.connection,authorize:async()=>({}),wait:async()=>{waits++;const call=x.calls.filter(c=>c.kind==='retain').at(-1);x.docs.set(call.options.documentId,{id:call.options.documentId,bank_id:'archive-bank',original_text:call.content,tags:call.options.tags,document_metadata:call.options.metadata,memory_unit_count:0});}});
 assert.equal((await service.publish(p.snapshotHash)).status,'verified');assert.equal(waits,2);assert.equal(x.calls.filter(c=>c.kind==='retain').length,2);assert.equal(x.calls.filter(c=>c.kind==='policy').length,1);
});
test('lost response survives restart as one attempted write; later exact readback can finish without resending',async()=>{
 const x=fixture(),p=x.plan();x.service().stage(p);x.controls.failRetain=true;await assert.rejects(x.service().publish(p.snapshotHash),/could not be verified/);assert.equal(x.calls.filter(c=>c.kind==='retain').length,1);x.controls.failRetain=false;assert.equal((await x.service().publish(p.snapshotHash)).status,'pending');assert.equal(x.calls.filter(c=>c.kind==='retain').length,1);assert.ok(!JSON.stringify(x.store.read()).includes('private upstream detail'));x.docs.set(p.documents[0].docId,cloudDocument(p.documents[0]));assert.equal((await x.service().publish(p.snapshotHash)).status,'verified');
});
test('later checkpoints inherit previous chunk write identities and cannot silently recreate missing archived content',async()=>{
 const x=fixture(),first=x.plan();x.service().stage(first);await x.service().publish(first.snapshotHash);const second=x.plan({parentHash:first.snapshotHash,createdAt:'2026-09-29T12:01:00Z'});x.service().stage(second);const records=x.store.read().cloudWorkspaceSnapshots,chunk=first.documents[0];assert.equal(records[first.snapshotHash].documents[chunk.hash].operationId,records[second.snapshotHash].documents[chunk.hash].operationId);x.docs.delete(chunk.docId);const count=x.calls.filter(c=>c.kind==='retain').length;assert.equal((await x.service().publish(second.snapshotHash)).status,'pending');assert.equal(x.calls.filter(c=>c.kind==='retain').length,count);
});
test('content-address collisions, foreign tags and metadata prevent recovery and are never overwritten',async()=>{
 for(const mutation of [d=>d.original_text+='x',d=>d.tags.push('lucid-workspace-archive-fixture'),d=>d.document_metadata.content_sha256='bad',d=>d.bank_id='foreign-bank']){const x=fixture(),p=x.plan();x.service().stage(p);await x.service().publish(p.snapshotHash);mutation(x.docs.get(p.documents[0].docId));const before=x.calls.filter(c=>c.kind==='retain').length;await assert.rejects(x.service().recover());await assert.rejects(x.service().publish(p.snapshotHash));assert.equal(x.calls.filter(c=>c.kind==='retain').length,before);}
});
test('manifest DAG requires one complete root and head, authorized owner transitions and explicit handoff',async()=>{
 const x=fixture(),p=x.plan(),root=cloudDocument(p.documents.at(-1));const handoff=x.plan({parentHash:p.snapshotHash,nextOwnerId:'owner-b',createdAt:'2026-09-29T12:01:00Z'}),hdoc=cloudDocument(handoff.documents.at(-1));assert.equal(inspectWorkspaceManifests([root,hdoc],'archive-fixture',{bank:'archive-bank'}).head.manifest.nextOwnerId,'owner-b');
 const unauthorized=x.plan({parentHash:handoff.snapshotHash,ownerId:'owner-a',createdAt:'2026-09-29T12:02:00Z'});assert.throws(()=>inspectWorkspaceManifests([root,hdoc,cloudDocument(unauthorized.documents.at(-1))],'archive-fixture',{bank:'archive-bank'}),/handoff/);
 const fork=x.plan({parentHash:p.snapshotHash,createdAt:'2026-09-29T12:03:00Z'});assert.throws(()=>inspectWorkspaceManifests([root,hdoc,cloudDocument(fork.documents.at(-1))],'archive-fixture',{bank:'archive-bank'}),/competing/);assert.throws(()=>inspectWorkspaceManifests([hdoc],'archive-fixture',{bank:'archive-bank'}),/parent/);
 x.service().stage(p);await x.service().publish(p.snapshotHash);x.service().stage(handoff);await x.service().publish(handoff.snapshotHash);assert.equal((await x.service().recover()).canEdit,false);assert.equal((await x.service('owner-b').recover()).canEdit,true);
});
test('fresh discovery detects a concurrent descendant after publication; it does not claim an atomic lease',async()=>{
 const x=fixture(),p=x.plan();x.service().stage(p);await x.service().publish(p.snapshotHash);const child=x.plan({parentHash:p.snapshotHash,createdAt:'2026-09-29T12:01:00Z'}),competitor=x.plan({parentHash:p.snapshotHash,createdAt:'2026-09-29T12:02:00Z'});x.service().stage(child);let injected=false;x.controls.hook=async phase=>{if(phase==='list'&&x.docs.has(child.documents.at(-1).docId)&&!injected){injected=true;x.docs.set(competitor.documents.at(-1).docId,cloudDocument(competitor.documents.at(-1)));}};await assert.rejects(x.service().publish(child.snapshotHash),/competing/);assert.equal(x.store.read().cloudWorkspaceStatus.status,'pending');assert.ok(x.docs.has(child.documents.at(-1).docId));assert.ok(x.docs.has(competitor.documents.at(-1).docId));
});
test('read-only bound and connection drift fail before any unauthorized write; newer local edits remain pending',async()=>{
 const x=fixture(),p=x.plan();x.service().stage(p);assert.equal((await x.service().publish(p.snapshotHash,{maxWrites:0})).status,'pending');assert.equal(x.calls.filter(c=>c.kind==='retain').length,0);await assert.rejects(x.service().publish(p.snapshotHash,{maxWrites:33}),/bounded/);x.controls.hook=async phase=>{if(phase==='retain')x.controls.connection='changed';};await assert.rejects(x.service().publish(p.snapshotHash),/connection changed/);assert.equal(x.store.read().cloudWorkspaceStatus.status,'pending');
 const y=fixture(),plan=y.plan();y.service().stage(plan);y.store.update(s=>s.cases[0].timeline.push({text:'A newer local edit'}));assert.equal((await y.service().publish(plan.snapshotHash)).status,'verified');assert.equal(y.store.read().cloudWorkspaceStatus.status,'pending');
});

test('learning closeout journals survive recovery without rebinding operation identities or restoring source proofs',async()=>{
 const x=fixture();const journal={key:'KA-0001:r2:opaque-hash',articleId:'KA-0001',revision:2,articleHash:'a'.repeat(64),caseId:'case',resolutionHash:'b'.repeat(64),workspaceId:'archive-fixture',scope:'lucid-workspace-archive-fixture',connectionId:'original-connection',bank:'original-bank',plan:{docId:'immutable-lesson-document',packet:{content:'Frozen generalized lesson',metadata:{article_id:'KA-0001'}}},planHash:'c'.repeat(64),operationId:'durable-operation',providerOperationId:'provider-operation',status:'unverified',attempts:1,checks:2};
 x.store.update(s=>{s.learningCloseouts={[journal.key]:journal};});const plan=x.plan(),service=x.service();service.stage(plan);await service.publish(plan.snapshotHash);const paid=x.calls.filter(c=>c.kind==='retain').length;
 const recovered=await service.recover();assert.deepEqual(recovered.state.learningCloseouts,{[journal.key]:journal});assert.equal(recovered.state.articles[0].cloudRetention,undefined);assert.equal(recovered.state.articles[0].cloudScope,undefined);assert.equal(x.calls.filter(c=>c.kind==='retain').length,paid);assert.ok(x.calls.filter(c=>c.kind==='retain').every(c=>c.options.metadata.source_type==='operational-archive'));
});
