import test from 'node:test';
import assert from 'node:assert/strict';
import express from 'express';
import {mountCloudWorkspaceRoutes} from '../server/cloud-workspace-routes.js';
import {buildCloudWorkspaceSnapshot} from '../server/cloud-workspace.js';
import {MemoryProvider} from '../server/providers.js';

async function fixture(t){
 let state={workspaceId:'route-local',companies:[{id:'org',name:'Current local company'}],cases:[{id:'current-case',description:'Current local data',timeline:[],attempts:[]}],articles:[],officialDocuments:[],historicalKnowledgeAssociations:[],incidents:[],events:[],outbox:[],memories:[]};const store={read:()=>structuredClone(state),update:fn=>{const copy=structuredClone(state),out=fn(copy);state=copy;return out;}},documents=new Map(),calls=[],backups=[],controls={connection:'connection-a',onRead:null,onBackup:null};
 const transport={listDocuments:async(bank,query)=>{calls.push({kind:'list',query});const items=[...documents.values()].filter(d=>query.tags.every(tag=>d.tags.includes(tag))).map(d=>({id:d.id}));return {items,total:items.length,offset:0};},getDocument:async(bank,id)=>{calls.push({kind:'get',id});await controls.onRead?.();return structuredClone(documents.get(id)||null);},listMentalModels:async()=>{calls.push({kind:'policy'});return {items:[],total:0};},retain:async(bank,content,options)=>{calls.push({kind:'retain'});documents.set(options.documentId,{id:options.documentId,bank_id:bank,original_text:content,tags:options.tags,document_metadata:options.metadata,memory_unit_count:0});return {async:true};}};
 const cloud={connectionId:()=>controls.connection,provider:()=>controls.provider||({c:{bank:'route-bank'}})},app=express();app.use(express.json());const hooks=mountCloudWorkspaceRoutes(app,store,{cloud,authorize:async()=>({}),transportFactory:()=>transport,wait:async()=>{},backupState:async previous=>{backups.push(previous);await controls.onBackup?.();return {path:'private-fixture-backup'};}});app.use((error,_req,res,_next)=>res.status(error.status||400).json({error:error.message}));const server=app.listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));t.after(()=>new Promise(resolve=>server.close(resolve)));const base=`http://127.0.0.1:${server.address().port}/api/cloud-workspace`;
 const request=async(path='',body)=>{const response=await fetch(base+path,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});return {status:response.status,body:await response.json()};};
 const addArchive=(input,owner='remote-owner')=>{const plan=buildCloudWorkspaceSnapshot(input,{ownerId:owner,createdAt:'2026-09-29T00:00:00Z'});for(const d of plan.documents)documents.set(d.docId,{id:d.docId,bank_id:'route-bank',original_text:d.content,tags:d.tags,document_metadata:d.metadata,memory_unit_count:0});return plan;};
 return {store,documents,calls,backups,controls,hooks,request,addArchive,transport};
}
test('local status and dirty hooks do not call Cloud; explicit stage/publish use the bounded reviewed plan',async t=>{
 const x=await fixture(t),before=x.store.read();let status=await x.request();assert.equal(status.status,200);assert.equal(status.body.workspaceId,'route-local');assert.equal(status.body.configured,true);assert.match(status.body.ownerId,/^[a-f0-9-]{36}$/);assert.equal(x.calls.length,0);x.hooks.queue();assert.equal(x.calls.length,0);
 const staged=await x.request('/stage',{expectedParentHash:null});assert.equal(staged.status,200);assert.ok(staged.body.forecast.uniqueDocuments>0);status=await x.request();assert.equal(status.body.pending.length,1);assert.ok(!JSON.stringify(status.body).includes('gzip-base64-fragment'));assert.equal(x.calls.filter(c=>c.kind==='retain').length,0);
 assert.equal((await x.request('/publish',{snapshotHash:staged.body.snapshotHash,maxWrites:33})).status,400);const published=await x.request('/publish',{snapshotHash:staged.body.snapshotHash,maxWrites:32});assert.equal(published.body.status,'verified');assert.deepEqual(x.store.read().cases,before.cases);
});
test('recovery preview never changes local data and apply repeats fresh reads, backs up first and excludes cached proofs',async t=>{
 const x=await fixture(t),original=x.store.read(),remote={...original,workspaceId:'route-remote',cases:[{id:'remote-case',description:'Recovered data',timeline:[{text:'Preserved history'}],attempts:[]}],articles:[{id:'KA-0001',fix:'Reviewed source body',fingerprint:'a'.repeat(64),cloudScope:{verified:true},cloudRetention:{status:'succeeded'}}]};x.addArchive(remote);const preview=await x.request('/recovery-preview',{workspaceId:'route-remote',ownerId:'remote-owner'});assert.equal(preview.status,200);assert.equal(preview.body.counts.cases,1);assert.equal(preview.body.canEdit,true);assert.deepEqual(x.store.read().cases,original.cases);assert.equal(x.backups.length,0);const reads=x.calls.length;
 const applied=await x.request('/recovery-apply',{previewId:preview.body.previewId,expectedLocalHash:preview.body.expectedLocalHash,snapshotHash:preview.body.snapshotHash,confirmReplace:true});assert.equal(applied.status,200);assert.equal(applied.body.requiresSourceReverification,true);assert.ok(x.calls.length>reads);assert.equal(x.backups.length,1);assert.deepEqual(x.backups[0].cases,original.cases);assert.equal(x.store.read().workspaceId,'route-remote');assert.equal(x.store.read().cases[0].id,'remote-case');assert.equal(x.store.read().articles[0].cloudScope,undefined);assert.equal(x.store.read().articles[0].cloudRetention,undefined);assert.equal(x.store.read().cloudWorkspaceLocal.ownerId,'remote-owner');assert.equal((await x.request()).body.status.status,'verified');
});
test('changed local state, changed connection and changed Cloud head invalidate the preview before replacement',async t=>{
 for(const kind of ['local','connection','head']){const x=await fixture(t),remote={...x.store.read(),workspaceId:'route-remote'};const first=x.addArchive(remote),preview=await x.request('/recovery-preview',{workspaceId:'route-remote',ownerId:'remote-owner'});if(kind==='local')x.store.update(s=>s.cases[0].description='New local edit');if(kind==='connection')x.controls.connection='another-key';if(kind==='head'){const next=buildCloudWorkspaceSnapshot(remote,{ownerId:'remote-owner',parentHash:first.snapshotHash,createdAt:'2026-09-29T01:00:00Z'});for(const d of next.documents)x.documents.set(d.docId,{id:d.docId,bank_id:'route-bank',original_text:d.content,tags:d.tags,document_metadata:d.metadata});}
 const result=await x.request('/recovery-apply',{previewId:preview.body.previewId,expectedLocalHash:preview.body.expectedLocalHash,snapshotHash:preview.body.snapshotHash,confirmReplace:true});assert.equal(result.status,409,kind);assert.equal(x.store.read().workspaceId,'route-local');assert.equal(x.backups.length,0,kind);}
});
test('backup failure or edits during backup preserve current cache; explicit replacement confirmation is mandatory',async t=>{
 const x=await fixture(t);x.addArchive({...x.store.read(),workspaceId:'route-remote'});const preview=(await x.request('/recovery-preview',{workspaceId:'route-remote',ownerId:'remote-owner'})).body;const body={previewId:preview.previewId,expectedLocalHash:preview.expectedLocalHash,snapshotHash:preview.snapshotHash};assert.equal((await x.request('/recovery-apply',body)).status,400);x.controls.onBackup=async()=>x.store.update(s=>s.cases[0].description='Edit during backup');assert.equal((await x.request('/recovery-apply',{...body,confirmReplace:true})).status,409);assert.equal(x.store.read().workspaceId,'route-local');assert.equal(x.store.read().cases[0].description,'Edit during backup');
});
test('handoff commits the next owner and exposes a cooperative edit gate, never an atomic Cloud lock',async t=>{
 const x=await fixture(t),staged=(await x.request('/stage',{expectedParentHash:null,nextOwnerId:'next-owner'})).body;assert.equal((await x.request('/publish',{snapshotHash:staged.snapshotHash,maxWrites:32})).body.status,'verified');assert.throws(()=>x.hooks.assertCanEdit(),/handoff/);assert.throws(()=>x.hooks.markPending(),/handoff/);assert.equal((await x.request()).body.status.activeOwnerId,'next-owner');assert.equal((await x.request('/stage',{expectedParentHash:staged.snapshotHash})).status,409);
});

test('source verification route is bounded, read-only toward Cloud, and leaves the canonical cache hash unchanged',async t=>{
 const x=await fixture(t);
 x.store.update(s=>s.articles.push({id:'KA-0001',revision:1,fingerprint:'a'.repeat(64),title:'Reviewed outcome',fix:'Reported earlier recovery',cause:'Unknown',verification:'Source report',limitations:'Original episode only',executor:'Docker',hosting:'Self-managed',updatedAt:'2026-09-29T00:00:00Z',sourceCases:[],citations:[],sync:'unverified'}));
 const provider=new MemoryProvider(x.store,{memoryMode:'hindsight',allowExternal:true,workspaceScope:'lucid-workspace-route-local',bank:'route-bank',hindsightUrl:'https://example.invalid'},{getDocument:x.transport.getDocument});x.controls.provider=provider;
 const article=x.store.read().articles[0],plan=provider.prepareRetention(article);
 x.documents.set(plan.docId,{id:plan.docId,bank_id:'route-bank',original_text:plan.packet.content,tags:plan.packet.tags,document_metadata:plan.packet.metadata,memory_unit_count:2});
 const before=(await x.request()).body.localHash;
 assert.equal((await x.request('/verify-sources',{sourceIds:Array.from({length:33},(_,i)=>`KA-${i}`)})).status,400);
 assert.equal((await x.request('/verify-sources',{sourceIds:['KA-0001','KA-0001']})).status,409);assert.equal(x.calls.length,0);
 const result=await x.request('/verify-sources',{sourceIds:['KA-0001']});assert.equal(result.status,200);assert.equal(result.body.verified,1);assert.equal(result.body.readOnlyProvider,true);assert.equal(x.calls.length,1);assert.equal(x.calls[0].kind,'get');assert.equal((await x.request()).body.localHash,before);assert.ok(x.store.read().articles[0].cloudScope.verifiedAt);assert.equal(x.store.read().articles[0].cloudRetention.status,'succeeded');
});
