import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,rmSync}from'node:fs';import{tmpdir}from'node:os';import{join}from'node:path';
import{Store}from'../server/db.js';import{hash}from'../server/domain.js';import{CloudWorkspaceArchive,buildCloudWorkspaceSnapshot,canonicalWorkspace}from'../server/cloud-workspace.js';import{createInvestigationAuthorizer}from'../server/hindsight-budget.js';import{createCloudReadAuthorizer}from'../server/cloud-read-budget.js';import{HindsightCreditBudget}from'../scripts/lib/hindsight-credit-budget.js';
test('archive uses locked staged-document authority and fresh metadata reads with exact recovery',async()=>{
 const dir=mkdtempSync(join(tmpdir(),'archive-budget-')),store=new Store(':memory:');try{store.update(s=>s.workspaceId='archive-budget');const original=store.read(),secret={baseUrl:'https://example.test',bank:'test-bank',apiKey:'fake'},settings={read:()=>secret},connectionId=()=>hash([secret.baseUrl,secret.bank,hash(secret.apiKey)]),ledgerPath=join(dir,'ledger.json'),ledger=new HindsightCreditBudget(ledgerPath);ledger.initialize();ledger.update(l=>Object.assign(l,{workspaceId:original.workspaceId,connectionId:connectionId()}));
 const paid=createInvestigationAuthorizer({store,settings,ledgerPath}),reads=createCloudReadAuthorizer({settings,ledgerPath}),authorize=request=>request.kind==='workspace-read'?reads(request):paid(request),documents=new Map();
 const transport={listDocuments:async()=>{const items=[...documents.values()].filter(d=>d.id.includes('-manifest-'));return {items,total:items.length,offset:0};},getDocument:async(_b,id)=>{if(!documents.has(id))throw Object.assign(Error('missing'),{status:404});return documents.get(id);},listMentalModels:async()=>({items:[],total:0}),retain:async(bank,content,options)=>{assert.equal(ledger.read().calls.at(-1).operation,'workspace-retain');documents.set(options.documentId,{id:options.documentId,bank_id:bank,original_text:content,tags:options.tags,document_metadata:options.metadata,memory_unit_count:0});return {operation_id:options.operationId};}};
 const service=new CloudWorkspaceArchive(store,transport,{workspaceId:original.workspaceId,ownerId:'editor-one',bank:secret.bank,connectionId,authorize}),plan=buildCloudWorkspaceSnapshot(original,{ownerId:'editor-one'});service.stage(plan);assert.equal((await service.publish(plan.snapshotHash,{maxWrites:32})).status,'verified');assert.equal(ledger.summary().byCategory.ingestion.reservedUSD,plan.documents.length*.15+.05);
 const recovery=await service.recover();assert.deepEqual(canonicalWorkspace(recovery.state),canonicalWorkspace(original));assert.equal(recovery.requiresSourceReverification,true);
 const doc=plan.documents[0];assert.throws(()=>ledger.reserve({id:'duplicate',operation:'workspace-retain',category:'ingestion',reservedUSD:.15,limits:{documentId:doc.docId}}),/already reserved/);
 }finally{store.close();rmSync(dir,{recursive:true,force:true});}
});
