import test from 'node:test';
import assert from 'node:assert/strict';
import {Store} from '../server/db.js';
import {hash,publicSnapshot} from '../server/domain.js';
import {MemoryProvider} from '../server/providers.js';
import {CloudWorkflow} from '../server/cloud-workflow.js';
import {buildCuratedRetentionManifest,CuratedRetentionWorkflow,curatedBatchRequest} from '../server/curated-retention.js';
function setup(count=2){
 const store=new Store(':memory:');store.update(s=>{s.workspaceId='batch-test';for(let i=0;i<count;i++)s.articles.push({id:'KA-'+String(i+1).padStart(4,'0'),revision:1,fingerprint:hash({i}),title:'Source article '+i,symptom:'Historical narrative',executor:'Unknown',hosting:'Unknown',runnerVersion:'',serverVersion:'',chartVersion:'',fix:'A source reported recovery after a configuration change.',cause:'',verification:'Source claim; no independent reproduction.',limitations:'Historical scope only.',sourceCases:[],sourceReports:[],citations:[],sourceIds:[],history:[],reviewer:'AI source reviewer',updatedAt:'2026-09-28T00:00:00Z',curation:{immutable:true,method:'assistant-source-inspection',reviewer:'AI source reviewer',reviewedAt:'2026-09-28T00:00:00Z'}});});
 const calls=[],reservations=[],documents=new Map();let connectionId='connection-a';
 const client={listMentalModels:async()=>{calls.push('models');return {total:0};},retainBatch:async(bank,items,options)=>{calls.push('retain');assert.equal(bank,'test-bank');assert.equal(options.async,true);for(const item of items){const state=store.read(),a=state.articles.find(a=>a.id===item.metadata.article_id);assert.equal(a.cloudRetention.status,'dispatched');assert.equal(a.cloudRetention.operationId,options.operationId);documents.set(item.document_id,{id:item.document_id,original_text:item.content,tags:item.tags,memory_unit_count:1});}return {async:true,operation_id:'provider-op'};},getDocument:async(_bank,id)=>{calls.push('document');return documents.get(id);}};
 const provider=new MemoryProvider(store,{memoryMode:'hindsight',allowExternal:true,hindsightUrl:'https://example.invalid',bank:'test-bank',workspaceScope:'lucid-workspace-batch-test'},client);provider.operation=async action=>{assert.equal(action,'status');calls.push('status');return {status:'completed'};};
 const reserve=async entry=>{reservations.push(entry);},workflow=new CuratedRetentionWorkflow(store,provider,{connectionId:()=>connectionId,reserve});
 const plan=buildCuratedRetentionManifest(store.read(),{connectionId,bank:'test-bank',scope:provider.scope()});
 return {store,provider,client,workflow,plan,calls,reservations,documents,setConnection:value=>{connectionId=value;}};
}
const dispatch=(x,index=0)=>x.workflow.dispatch(x.plan.id,x.plan.batches[index].id,{expectedPlanHash:x.plan.manifestHash,acknowledgeCreditUse:true});
test('dry run and staging are local, bounded, immutable and omit payloads from public snapshot',()=>{const x=setup(43),before=x.store.read();assert.equal(x.plan.totalArticles,43);assert.equal(x.plan.batches.length,9);for(const b of x.plan.batches){assert.ok(b.items.length<=5);assert.equal(b.bytes,Buffer.byteLength(JSON.stringify(curatedBatchRequest(b))));assert.ok(b.bytes<=40000);}assert.equal(x.store.read().cloudOperations,undefined);x.workflow.stage(x.plan);x.workflow.stage(x.plan);assert.deepEqual(x.calls,[]);assert.deepEqual(x.store.read().cases,before.cases);assert.deepEqual(x.store.read().outbox,before.outbox);assert.deepEqual(x.store.read().articles,before.articles);assert.equal(publicSnapshot(x.store.read(),{}).curatedRetentionPlans,undefined);const altered=structuredClone(x.plan);altered.batches[0].items[0].packet.content+=' changed';assert.throws(()=>x.workflow.stage(altered),/hash/);x.store.close();});
test('dispatch persists identities before SDK and status verifies every exact document',async()=>{const x=setup();x.workflow.stage(x.plan);await dispatch(x);assert.equal(x.store.read().articles[0].cloudRetention.status,'processing');assert.equal(x.calls.filter(c=>c==='retain').length,1);const result=await x.workflow.check(x.plan.id,x.plan.batches[0].id);assert.equal(result.status,'succeeded');assert.ok(x.store.read().articles.every(a=>a.cloudRetention.status==='succeeded'&&a.cloudRetention.retryable===false));assert.deepEqual(x.reservations.map(r=>r.kind),['retain-batch','batch-status']);await assert.rejects(dispatch(x),/already had/);assert.equal(x.calls.filter(c=>c==='retain').length,1);x.store.close();});
test('uncertain dispatch consumes its identity; restart can only read status',async()=>{const x=setup();x.workflow.stage(x.plan);const original=x.client.retainBatch;x.client.retainBatch=async(...args)=>{await original(...args);throw new Error('secret upstream body');};await assert.rejects(dispatch(x),error=>/No retry/.test(error.message)&&!error.message.includes('secret'));assert.equal(x.store.read().articles[0].cloudRetention.status,'unverified');const resumed=new CuratedRetentionWorkflow(x.store,x.provider,{connectionId:()=> 'connection-a',reserve:async()=>{}});const result=await resumed.check(x.plan.id,x.plan.batches[0].id);assert.equal(result.status,'succeeded');await assert.rejects(dispatch(x),/already had/);assert.equal(x.calls.filter(c=>c==='retain').length,1);x.store.close();});
test('wrong content, scope or zero retained facts prevents complete verification',async()=>{for(const mode of ['content','scope','facts']){const x=setup();x.workflow.stage(x.plan);await dispatch(x);const doc=x.documents.get(x.plan.batches[0].items[1].docId);if(mode==='content')doc.original_text+='changed';if(mode==='scope')doc.tags=[];if(mode==='facts')doc.memory_unit_count=0;const result=await x.workflow.check(x.plan.id,x.plan.batches[0].id);assert.equal(result.status,'unverified');assert.equal(x.store.read().articles[0].cloudRetention.status,'succeeded');assert.equal(x.store.read().articles[1].cloudRetention.status,'unverified');assert.equal(x.calls.filter(c=>c==='retain').length,1);x.store.close();}});
test('connection or article changes before and after calls fail closed',async()=>{const x=setup();x.workflow.stage(x.plan);x.setConnection('other');await assert.rejects(dispatch(x),/Connection/);assert.deepEqual(x.calls,[]);x.setConnection('connection-a');x.client.retainBatch=async()=>{x.calls.push('retain');x.setConnection('other');return {async:true};};await assert.rejects(dispatch(x),/Connection/);assert.equal(x.store.read().articles[0].cloudRetention.status,'unverified');assert.equal(x.calls.filter(c=>c==='retain').length,1);x.store.close();const y=setup();y.workflow.stage(y.plan);y.store.update(s=>s.articles[0].fix='Changed after freeze');await assert.rejects(dispatch(y),/evidence changed/);assert.deepEqual(y.calls,[]);y.store.close();});
test('existing models stop before retain, unreserved access stops before metadata, and staged status never dispatches',async()=>{const x=setup();x.workflow.stage(x.plan);await assert.rejects(x.workflow.check(x.plan.id,x.plan.batches[0].id),/not been dispatched/);x.workflow.reserve=undefined;await assert.rejects(dispatch(x),/budget reservation/);assert.deepEqual(x.calls,[]);x.workflow.reserve=async()=>{};x.client.listMentalModels=async()=>({total:1});await assert.rejects(dispatch(x),/refresh-policy/);assert.ok(!x.calls.includes('retain'));x.store.close();});
test('current retained and uncertain articles are skipped; normal article-level retry cannot resend a batch',async()=>{const x=setup();x.store.update(s=>{s.articles[0].cloudRetention={revision:1,connectionId:'connection-a',status:'succeeded'};s.articles[1].cloudRetention={revision:1,connectionId:'connection-a',status:'unverified',batchManaged:true};});const plan=buildCuratedRetentionManifest(x.store.read(),{connectionId:'connection-a',bank:'test-bank',scope:x.provider.scope()});assert.equal(plan.totalArticles,0);assert.deepEqual(plan.skipped.map(x=>x.reason),['already-verified','existing-retention-requires-status-review']);const cloud=Object.create(CloudWorkflow.prototype);cloud.store=x.store;cloud.checkRetention=async()=>{throw new Error('must not make status call');};await assert.rejects(cloud.retryRetention('KA-0002',1),/Batch retention permits status checks only/);x.store.close();});
test('serialized40KB bound splits even when fewer than five articles fit',()=>{const x=setup(5);x.store.update(s=>{for(const a of s.articles)a.fix='q'.repeat(8000);});const plan=buildCuratedRetentionManifest(x.store.read(),{connectionId:'connection-a',bank:'test-bank',scope:x.provider.scope()});assert.ok(plan.batches.length>1);assert.equal(plan.totalArticles,5);assert.ok(plan.batches.every(b=>b.bytes<=40000&&b.items.length<=5));x.store.close();});
test('status never marks success after connection changes during a read or overwrites replacement provenance',async()=>{const x=setup();x.workflow.stage(x.plan);await dispatch(x);const get=x.client.getDocument;x.client.getDocument=async(...args)=>{const doc=await get(...args);x.setConnection('other');return doc;};await assert.rejects(x.workflow.check(x.plan.id,x.plan.batches[0].id),/Connection/);assert.ok(x.store.read().articles.every(a=>a.cloudRetention.status!=='succeeded'));assert.equal(x.calls.filter(c=>c==='retain').length,1);x.store.close();const y=setup();y.workflow.stage(y.plan);await dispatch(y);const read=y.client.getDocument;y.client.getDocument=async(...args)=>{const doc=await read(...args);y.store.update(s=>{s.articles[0].cloudRetention={operationId:'replacement',status:'processing'};});return doc;};await assert.rejects(y.workflow.check(y.plan.id,y.plan.batches[0].id),/retention changed/);assert.deepEqual(y.store.read().articles[0].cloudRetention,{operationId:'replacement',status:'processing'});y.store.close();});
