import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {Store} from '../server/db.js';import {approveKnowledge,reuseArticle,applicability,incidentMatch,requireCase} from '../server/domain.js';import {MemoryProvider,RetentionWorker,configuration,resolveRecall} from '../server/providers.js';
function setup(){const store=new Store(':memory:');const config=configuration({});const memory=new MemoryProvider(store,config);const worker=new RetentionWorker(store,memory);return {store,memory,worker};}
const input={title:'Liveness probe timeout workaround',fix:'Increase the probe timeout after validating liveness events.',cause:'',verification:'Support confirmed that unexpected restarts stopped.',limitations:'Historical environment only. Version range not established.',reviewer:'Test reviewer',reviewed:true};
function approve(store,id='CS-1042',data=input){return store.update(s=>{requireCase(s,id).resolution={fix:data.fix};return approveKnowledge(s,id,data);});}
test('only confirmed outcomes become approved knowledge',()=>{const {store}=setup();assert.throws(()=>store.update(s=>approveKnowledge(s,'CS-1042',input)),/confirmed/);assert.equal(store.read().articles.length,0);store.close();});
test('approved experience is recalled in a different case; repeat links without retention',async()=>{const {store,memory,worker}=setup();const a=approve(store);await worker.run();const recalled=resolveRecall(store.read(),await memory.recall('runner'));assert.equal(recalled[0].id,a.id);store.update(s=>reuseArticle(s,'CS-1043',{articleId:a.id,reviewed:true,evidence:'Validated probe behavior and successful outcome.',engineer:'Reviewer'}));const state=store.read();assert.equal(state.articles.length,1);assert.equal(state.outbox.length,1);assert.deepEqual(state.cases[1].articleIds,[a.id]);assert.equal(state.cases[0].articleIds.length,1);assert.equal(state.cases[2].articleIds.length,0);store.close();});
test('duplicate approvals are idempotent',()=>{const {store}=setup();const a=approve(store),b=approve(store);assert.equal(a.id,b.id);assert.equal(store.read().outbox.length,1);store.close();});
test('incompatible stage, executor and known versions are rejected',()=>{const {store}=setup(),a=approve(store);const s=store.read();assert.equal(applicability(s.cases[2],a).status,'incompatible');assert.equal(applicability({...s.cases[1],executor:'Shell'},a).status,'incompatible');assert.equal(applicability({...s.cases[1],runnerVersion:'18.0'},{...a,runnerVersion:'16.9'}).status,'incompatible');assert.throws(()=>store.update(s=>reuseArticle(s,'CS-1044',{articleId:a.id,reviewed:true,evidence:'test',engineer:'reviewer'})),/incompatible/);store.close();});
test('failed guidance is not suggested again and unknown versions require review',()=>{const {store}=setup(),a=approve(store),c=store.read().cases[1];assert.equal(applicability(c,a).status,'review');c.attempts.push({articleId:a.id,result:'Failed'});assert.equal(applicability(c,a).status,'incompatible');store.close();});
test('incident link requires exact host, service and historical window',()=>{const {store}=setup(),s=store.read(),i=s.incidents[0],c=s.cases[3];assert.equal(incidentMatch(c,i),true);assert.equal(incidentMatch({...c,hosting:'Self-managed'},i),false);assert.equal(incidentMatch({...c,occurredAt:'2026-01-01T00:00:00Z'},i),false);assert.equal(incidentMatch({...c,service:'Registry'},i),false);assert.equal(incidentMatch({...c,host:'notgitlab.com'},i),false);store.close();});
test('revision conflict cannot overwrite newer evidence; stale recalls are discarded',async()=>{const {store,memory,worker}=setup(),a=approve(store);await worker.run();const old=await memory.recall('runner');approve(store,'CS-1042',{...input,targetArticleId:a.id,expectedRevision:1,limitations:'Exclude chart versions with a changed liveness script.'});assert.throws(()=>approve(store,'CS-1042',{...input,targetArticleId:a.id,expectedRevision:1}),/changed/);assert.equal(resolveRecall(store.read(),old).length,0);await worker.run();assert.equal(resolveRecall(store.read(),await memory.recall('runner'))[0].revision,2);assert.equal(store.read().articles[0].history.length,1);store.close();});
test('queued obsolete revisions are superseded',async()=>{const {store,worker}=setup(),a=approve(store);approve(store,'CS-1042',{...input,targetArticleId:a.id,expectedRevision:1,limitations:'Revision with narrower applicability.'});await worker.run();assert.deepEqual(store.read().outbox.map(j=>j.status),['superseded','simulated']);store.close();});
test('provider failure remains visible, without falling back to offline memory',async()=>{const {store}=setup();approve(store);const worker=new RetentionWorker(store,{retain:async()=>{throw new Error('secret upstream failure');}});await worker.run();const s=store.read();assert.equal(s.outbox[0].status,'failed');assert.equal(s.memories.length,0);assert.ok(!s.outbox[0].error.includes('secret'));store.close();});
test('uncertain accepted write retries the same immutable document identity',async()=>{const {store}=setup();approve(store);const writes=[];let first=true;const worker=new RetentionWorker(store,{retain:async a=>{writes.push(`${a.id}:${a.revision}:${a.fingerprint}`);if(first){first=false;throw new Error('timeout after accepted');}return {provider:'hindsight',docId:writes.at(-1)};}});await worker.run();store.update(s=>s.outbox[0].status='pending');await worker.run();assert.equal(writes[0],writes[1]);assert.equal(store.read().outbox[0].status,'succeeded');store.close();});
test('restart recovers processing jobs and SQLite persists cases',()=>{const dir=mkdtempSync(join(tmpdir(),'lucid-')),file=join(dir,'db.sqlite');let store=new Store(file);approve(store);store.update(s=>s.outbox[0].status='processing');store.close();store=new Store(file);new RetentionWorker(store,{});assert.equal(store.read().articles.length,1);assert.equal(store.read().outbox[0].status,'pending');store.close();rmSync(dir,{recursive:true,force:true});});
test('private identifiers do not enter generalized article content',()=>{const {store}=setup();store.update(s=>s.companies.find(o=>o.id==='org-a').name='Company A');const a=approve(store,'CS-1042',{...input,fix:'Company A contacted hello@example.com from 10.0.0.1 with glpat-abc123secret.'});assert.ok(!JSON.stringify(a).includes('hello@example.com'));assert.ok(!a.fix.includes('Company A'));assert.ok(!a.fix.includes('glpat-'));store.close();});
test('live provider is gated without external-call authorization',async()=>{const {store}=setup();const memory=new MemoryProvider(store,configuration({MEMORY_MODE:'hindsight'}));await assert.rejects(()=>memory.recall('anything'),/disabled/);store.close();});
test('same fix with new case evidence links existing knowledge without another retention',()=>{const {store}=setup();const a=approve(store);const b=approve(store,'CS-1043',{...input,verification:'A different customer confirmed the same reviewed outcome.'});assert.equal(a.id,b.id);assert.equal(store.read().outbox.length,1);store.close();});
test('unclassified new cases can review relevant guidance without claiming applicability',()=>{const {store}=setup(),a=approve(store);assert.equal(applicability({...store.read().cases[1],symptom:'unclassified',hosting:'Unknown',executor:'Unknown'},a).status,'review');store.close();});
test('expanded historical cases retain separate sources and failed-step evidence',()=>{const {store}=setup();const s=store.read();assert.equal(s.cases.length,9);assert.equal(s.cases.find(c=>c.id==='CS-2004').attempts[0].result,'Failed');assert.equal(s.cases.find(c=>c.id==='CS-2004').runnerVersion,'17.3.1');assert.equal(s.articles.length,0);assert.equal(s.memories.length,0);store.close();});
test('historical corpus migration preserves user cases and does not duplicate seeds',()=>{const dir=mkdtempSync(join(tmpdir(),'lucid-migrate-')),file=join(dir,'db.sqlite');let store=new Store(file);store.update(s=>{s.migrations=[];s.cases[0].description='User-edited evidence must survive';s.cases.push({...structuredClone(s.cases[0]),id:'CS-2500',reconstructed:false,sourceId:null,title:'User case'});});store.close();store=new Store(file);assert.equal(store.read().cases.length,10);assert.equal(store.read().cases[0].description,'User-edited evidence must survive');store.close();rmSync(dir,{recursive:true,force:true});});
