import {test} from 'node:test';
import assert from 'node:assert/strict';
import {EvidenceStore} from '../server/evidence-store.js';
import {seedEnrichment,saveNotePage,finishEnrichment,reextract,normalizeLinkKinds} from '../server/enrichment-store.js';
import {PublicGitlabClient,PublicSourceError,enrichReport,collectLinkedEvidence} from '../server/enrichment-collector.js';
import {extractEnrichment,EXTRACTION_VERSION} from '../server/enrichment-extract.js';
const report={id:'gitlab-runner-123',url:'https://gitlab.com/gitlab-org/gitlab-runner/-/issues/123',title:'Runner cache fails',body:'GitLab Runner version 17.0.1 on Docker. Cache unavailable.',author:'Public user',createdAt:'2025-01-01',updatedAt:'2025-01-02',state:'closed',family:'Caching',labels:['type::bug'],source:'GitLab Runner public issues'};
function setup(){const s=new EvidenceStore(':memory:');s.upsert(report);seedEnrichment(s.db);return s;}
const note=(id,body,extra={})=>({id:'gid://gitlab/Note/'+id,body,system:false,createdAt:'2025-01-02T01:00:00Z',updatedAt:'2025-01-02T01:00:00Z',discussion:{id:'gid://gitlab/Discussion/a'},...extra});
const page=(nodes,cursor=null)=>({notes:{nodes,pageInfo:{hasNextPage:!!cursor,endCursor:cursor}}});
test('collects every cursor page with idempotent notes and direct source citations',async()=>{const s=setup();const calls=[];const client={notes:async(iid,cursor)=>{calls.push(cursor);return cursor?page([note(2,'Upgrading to runner 17.1.2 fixed the issue. I can confirm it works now.',{createdAt:'2025-01-03T01:00:00Z'})]):page([note(1,'Tried clearing cache, but still fails.')],'cursor-2');},mergeRequest:async()=>null};const r=await enrichReport(s.db,s.get(report.id),client);assert.equal(r.status,'completed');assert.deepEqual(calls,[null,'cursor-2']);assert.equal(s.enrichmentStats().total,1);assert.equal(s.enrichmentStats().completed,1);assert.equal(s.enrichmentStats().notes,2);const e=s.getEnrichment(report.id);assert.equal(e.outcome.category,'source-reported-resolution');assert.equal(e.outcome.confirmed,false);assert.equal(e.humanReviewed,false);assert.match(e.resolutions[0].url,/#note_2$/);assert.equal(e.attempts[0].result,'reported-unsuccessful');assert.ok(e.versions.some(v=>v.value==='17.1.2'));await enrichReport(s.db,s.get(report.id),client);assert.equal(calls.length,2);assert.equal(s.discussion(report.id,{limit:1,page:2}).rows[0].id,'gid://gitlab/Note/2');s.close();});
test('partial failure preserves a committed page and resumes exact next cursor',async()=>{const s=setup();let calls=0;await enrichReport(s.db,s.get(report.id),{notes:async()=>{if(calls++)throw new PublicSourceError('temporary',{retryable:true});return page([note(1,'First diagnostic')],'next');}});assert.equal(s.getEnrichment(report.id).status,'failed');assert.equal(s.getEnrichment(report.id).nextCursor,'next');const cursors=[];await enrichReport(s.db,s.get(report.id),{notes:async(i,c)=>{cursors.push(c);return page([note(2,'Second diagnostic')]);}});assert.deepEqual(cursors,['next']);assert.equal(s.discussion(report.id).total,2);assert.equal(s.enrichmentStats().completed,1);s.close();});
test('repeated/missing cursor and malformed notes cannot falsely complete collection',async()=>{const s=setup();const result=await enrichReport(s.db,s.get(report.id),{notes:async()=>page([note(1,'Body')],'same')});assert.equal(result.status,'failed');assert.equal(s.enrichmentStats().completed,0);assert.equal(s.discussion(report.id).total,1);assert.throws(()=>saveNotePage(s.db,s.get(report.id),[note(2,'valid'),{id:'bad',body:'bad'}],'next'));assert.equal(s.discussion(report.id).total,1);s.close();});
test('private or deleted sources are reconciled as unavailable, never empty completed',async()=>{const s=setup();await enrichReport(s.db,s.get(report.id),{notes:async()=>{throw new PublicSourceError('not public',{status:404});}});const stats=s.enrichmentStats();assert.equal(stats.unavailable,1);assert.equal(stats.completed,0);assert.equal(stats.total,stats.pending+stats.collecting+stats.completed+stats.unavailable+stats.failed);s.close();});
test('backoff honors Retry-After and network retries stop at a finite bound',async()=>{let calls=0;const pauses=[];const c=new PublicGitlabClient({minInterval:0,now:()=>0,pause:async ms=>pauses.push(ms),maxRetries:2,fetchFn:async()=>{calls++;return calls===1?new Response('{}',{status:429,headers:{'retry-after':'3'}}):new Response('{"data":{"ok":true}}');}});await c.request('https://gitlab.com/api/graphql');assert.equal(calls,2);assert.ok(pauses[0]>=3000);let n=0;const fail=new PublicGitlabClient({minInterval:0,pause:async()=>{},maxRetries:2,fetchFn:async()=>{n++;throw new Error('offline');}});await assert.rejects(()=>fail.request('https://gitlab.com/api/graphql'));assert.equal(n,3);});
test('authentication failures are not retried and GraphQL errors are not empty success',async()=>{let n=0;const c=new PublicGitlabClient({minInterval:0,pause:async()=>{},fetchFn:async()=>{n++;return new Response('{}',{status:401});}});await assert.rejects(()=>c.request('https://gitlab.com/api/graphql'));assert.equal(n,1);const gql=new PublicGitlabClient({minInterval:0,fetchFn:async()=>new Response('{"errors":[{"message":"Query too complex"}]}')});await assert.rejects(()=>gql.notes('123'),/rejected query/);});
test('closed status, closure activity and proposed fixes do not establish success',()=>{const r={...report,labels:JSON.stringify(report.labels)};assert.equal(extractEnrichment(r,[]).outcome.category,'insufficient-evidence');assert.equal(extractEnrichment(r,[note(1,'closed via merge request !25',{system:true})]).outcome.category,'insufficient-evidence');assert.equal(extractEnrichment(r,[note(1,'Try upgrading to 17.2.0; it should fix the issue.')]).outcome.category,'proposed-resolution');assert.notEqual(extractEnrichment(r,[note(1,'Upgrading to 17.2.0 did not fix the issue. It does not work.')]).outcome.category,'source-reported-resolution');});
test('later unsuccessful observations prevent presenting conflicting reports as resolved',()=>{const r={...report,labels:JSON.stringify(report.labels)};const x=extractEnrichment(r,[note(1,'I upgraded to 17.2.0 and it works now.'),note(2,'Same issue, it still fails.',{createdAt:'2025-02-01'})]);assert.equal(x.outcome.category,'conflicting');assert.equal(extractEnrichment(r,[note(1,'Marked this issue as duplicate of #4')]).outcome.category,'duplicate');assert.equal(extractEnrichment(r,[note(1,'Closing this as stale')]).outcome.category,'obsolete');});
test('comment retrieval and selected evidence exclude heldout sources and cross-links',()=>{const s=setup();saveNotePage(s.db,s.get(report.id),[note(1,'x509 certificate failure. Upgrading to runner 17.2.0 fixed the issue. More at https://gitlab.com/gitlab-org/gitlab-runner/-/work_items/999')],'__COMPLETE__');s.reserveSources(['https://gitlab.com/gitlab-org/gitlab-runner/-/issues/999']);finishEnrichment(s.db,s.get(report.id),[...s.reserved]);assert.equal(s.getEnrichment(report.id).resolutions.length,0);assert.ok(!s.selectedReference(report.id).summary.includes('fixed the issue'));assert.equal(s.suggest('x509 certificate').length,0);s.reserveSources(['https://gitlab.com/gitlab-org/gitlab-runner/-/work_items/123#note_1']);assert.equal(s.selectedReference(report.id),null);s.close();});
test('note-only search returns source-linked evidence without auto-approving it',()=>{const s=setup();saveNotePage(s.db,s.get(report.id),[note(1,'Kubernetes artifact permission denied. Upgrading to runner 17.2.0 fixed the issue.')],'__COMPLETE__');finishEnrichment(s.db,s.get(report.id));assert.equal(s.search({q:'artifact permission'}).total,1);assert.equal(s.search({outcome:'source-reported-resolution'}).total,1);assert.equal(s.suggest('artifact permission')[0].id,report.id);const ref=s.selectedReference(report.id);assert.match(ref.url,/#note_1$/);assert.ok(ref.summary.length<=700);assert.match(ref.status,/machine extraction/);assert.equal(s.stats().confirmed,0);assert.equal(s.stats().reviewed,0);s.close();});
test('redaction and note truncation are explicit, page replay deduplicates search rows',()=>{const s=setup();const n=note(1,'password=pretend123 hello@example.com '+ 'x'.repeat(25000));saveNotePage(s.db,s.get(report.id),[n],'a');saveNotePage(s.db,s.get(report.id),[n],'b');const d=s.discussion(report.id);assert.equal(d.total,1);assert.equal(d.rows[0].truncated,false);assert.ok(d.rows[0].body.length>24000);assert.ok(!d.rows[0].body.includes('pretend123'));assert.equal(s.db.prepare('select count(*) n from note_search').get().n,1);s.close();});

test('GitLab threaded DiscussionNote and DiffNote identities are preserved',()=>{const s=setup();saveNotePage(s.db,s.get(report.id),[note(1,'Thread reply',{id:'gid://gitlab/DiscussionNote/1'}),note(2,'Diff context',{id:'gid://gitlab/DiffNote/2'})],'__COMPLETE__');assert.equal(s.discussion(report.id).total,2);assert.ok(s.discussion(report.id).rows.some(n=>n.id==='gid://gitlab/DiscussionNote/1'));s.close();});

test('questions, negation, quotations, hearsay and working-with text cannot claim success',()=>{const r={...report,labels:JSON.stringify(report.labels)};for(const body of [
 'I cannot confirm whether upgrading to 17.2 fixed the issue.',
 'I suspect upgrading to 17.2 fixed the issue.',
 'Try upgrading to 17.2 and everything works again.',
 'Upgrading to 17.2 has not fixed the issue.',
 'Has upgrading to 17.2 fixed the issue?',
 'Someone said: "Upgrading to 17.2 fixed the issue." I have not tested it.',
 'I’m working with a customer running version 17.2.',
 'The changelog says the bug was fixed in 1.35.1.',
 '> Upgrading to 17.2 fixed the issue.',
 'Upgrading to 17.2 should fix the issue.',
 'I never upgraded to 17.2. Someone reported the issue was fixed.',
 'I upgraded to 17.2, but this did not fix the issue.'
 ])assert.notEqual(extractEnrichment(r,[note(1,body)]).outcome.category,'source-reported-resolution',body);});
test('link associations commit atomically with page cursor and recover on end-cursor resume',async()=>{const s=setup();const r=s.get(report.id);saveNotePage(s.db,r,[note(1,'Fix discussion https://gitlab.com/gitlab-org/gitlab-runner/-/merge_requests/42')],'__COMPLETE__');assert.equal(s.db.prepare('SELECT count(*) n FROM evidence_report_links').get().n,1);s.db.exec('DELETE FROM evidence_report_links');let notesCalls=0,linksCalls=0;await enrichReport(s.db,r,{notes:async()=>{notesCalls++;throw Error('should not refetch');},mergeRequest:async()=>{linksCalls++;return {title:'Public patch',state:'merged',merged_at:'2025-01-03',description:'Source diff'};}});assert.equal(notesCalls,0);assert.equal(linksCalls,1);assert.equal(s.getEnrichment(r.id).linkedEvidence[0].state,'merged');assert.equal(s.getEnrichment(r.id).outcome.confirmed,false);s.close();});
test('failed linked fetch remains explicit and can retry independently of completed notes',async()=>{const s=setup(),r=s.get(report.id);saveNotePage(s.db,r,[note(1,'Fix !42')],'__COMPLETE__');await enrichReport(s.db,r,{mergeRequest:async()=>{throw new PublicSourceError('temporary',{status:503});}});assert.equal(s.getEnrichment(r.id).collectionComplete,true);assert.equal(s.getEnrichment(r.id).linkedEvidenceStatus,'partial');assert.equal(s.enrichmentStats().linkedFailed,1);await collectLinkedEvidence(s.db,r,{mergeRequest:async()=>({title:'Patch',state:'merged'})},{retryOnly:true});assert.equal(s.getEnrichment(r.id).linkedEvidenceStatus,'complete');assert.equal(s.enrichmentStats().linkedFailed,0);s.close();});

test('known Kubernetes context ranks relevant pod restarts above generic Windows service restarts',()=>{const s=setup();s.upsert({...report,id:'gitlab-runner-124',url:report.url.replace('123','124'),title:'Windows runner restart readiness timeout',body:'Windows service restarts unexpectedly during readiness timeout on Windows Server.'});s.upsert({...report,id:'gitlab-runner-125',url:report.url.replace('123','125'),title:'Runner restarts during readiness timeout',body:'Kubernetes pod runner restart with liveness readiness timeout. Runner version 17.2.0.'});const rows=s.suggest('runner restart readiness timeout',{executor:'Kubernetes',runnerVersion:'17.2.0'});assert.equal(rows[0].id,'gitlab-runner-125');assert.match(rows[0].applicability.executor,/verify exact/);assert.ok(!JSON.stringify(rows).includes('incompatible'));s.close();});

test('resolution-linked recent version mentions survive long historical threads',()=>{const r={...report,labels:JSON.stringify(report.labels)};const notes=Array.from({length:45},(_,i)=>note(i+1,`Runner version 12.${i}.0 failed`,{createdAt:'2020-01-01'}));notes.push(note(99,'Upgrading to runner version 17.7.1 fixed the issue.',{createdAt:'2025-01-01'}));const e=extractEnrichment(r,notes);assert.equal(e.versions[0].value,'17.7.1');assert.match(e.versions[0].url||'',/#note_99$|^$/);});
test('page receipts preserve returned count and stable ID digest separately from unique note count',()=>{const s=setup();saveNotePage(s.db,s.get(report.id),[note(1,'one'),note(2,'two')],'cursor');saveNotePage(s.db,s.get(report.id),[note(2,'two'),note(3,'three')],'__COMPLETE__');const e=s.getEnrichment(report.id);assert.equal(e.notesCount,3);assert.equal(e.pageReceipts.reduce((n,p)=>n+p.returnedNotes,0),4);assert.equal(e.pageReceipts[0].idsSha256.length,64);assert.equal(e.receiptCoverage,'all-collected-pages');s.close();});

test('public GraphQL request is unauthenticated and missing data never becomes completed',async()=>{let options;const valid=new PublicGitlabClient({minInterval:0,fetchFn:async(url,opts)=>{options=opts;return new Response(JSON.stringify({data:{project:{issue:page([])}}}));}});await valid.notes('123','next');assert.equal(options.headers.Authorization,undefined);assert.equal(options.headers.Cookie,undefined);assert.equal(JSON.parse(options.body).variables.after,'next');for(const payload of [{data:{project:null}},{data:{project:{issue:null}}},{data:{project:{issue:{}}}}]){const client=new PublicGitlabClient({minInterval:0,fetchFn:async()=>new Response(JSON.stringify(payload))});await assert.rejects(()=>client.notes('123'));}});
test('remaining quota causes proactive wait until source reset before next request',async()=>{let time=1000;const sleeps=[];let calls=0;const c=new PublicGitlabClient({minInterval:0,now:()=>time,pause:async ms=>{sleeps.push(ms);time+=ms;},fetchFn:async()=>{calls++;return new Response('{}',{headers:calls===1?{'ratelimit-remaining':'2','ratelimit-reset':'10'}:{}});}});await c.request('https://gitlab.com/api/graphql');await c.request('https://gitlab.com/api/graphql');assert.deepEqual(sleeps,[9000]);});
test('interruption before first page is retryable with no false completion',async()=>{const s=setup();let calls=0;const r=await enrichReport(s.db,s.get(report.id),{notes:async()=>{calls++;return page([]);}},{shouldStop:()=>true});assert.equal(r.status,'failed');assert.equal(r.errorType,'public-source');assert.equal(calls,0);assert.equal(s.enrichmentStats().completed,0);assert.equal(s.discussion(report.id).total,0);s.close();});
test('linked access failure and unsupported project remain explicit without private fetch',async()=>{const s=setup(),r=s.get(report.id);saveNotePage(s.db,r,[note(1,'Fix https://gitlab.com/gitlab-org/gitlab-runner/-/merge_requests/42 and https://gitlab.com/other/private/-/merge_requests/77')],'__COMPLETE__');await collectLinkedEvidence(s.db,r,{mergeRequest:async url=>{if(url.includes('other/'))return null;throw new PublicSourceError('No access',{status:403});}});const statuses=s.db.prepare('SELECT status FROM evidence_links').all().map(r=>r.status);assert.ok(statuses.includes('unavailable'));assert.ok(statuses.includes('outside-collector-scope'));const client=new PublicGitlabClient({fetchFn:async()=>{throw new Error('must not contact arbitrary host');}});assert.equal(await client.mergeRequest('https://gitlab.com/other/private/-/merge_requests/77'),null);assert.equal(await client.mergeRequest('https://evil.example/gitlab-org/gitlab-runner/-/merge_requests/1'),null);s.close();});
test('feature requests and unresolved records retain non-solution categories and cited follow-ups',()=>{const r={...report,state:'opened',labels:'[]'};assert.equal(extractEnrichment(r,[note(1,'TODO: investigate this failure and verify cache permissions.')]).outcome.category,'unresolved');const e=extractEnrichment({...r,labels:'["type::feature"]'},[note(1,'- [ ] Investigate cache permissions')]);assert.equal(e.outcome.category,'feature-request');assert.equal(e.tasks.length,1);assert.equal(e.tasks[0].kind,'follow-up');});

test('selected evidence prefers an exact mentioned case version without claiming an affected range',()=>{const s=setup(),r=s.get(report.id);saveNotePage(s.db,r,[note(1,'Upgrading to runner 17.1.2 fixed the issue.',{createdAt:'2025-01-01'}),note(2,'Upgrading to runner 18.0.1 fixed the issue.',{createdAt:'2025-03-01'})],'__COMPLETE__');finishEnrichment(s.db,r);const selected=s.selectedReference(r.id,{runnerVersion:'17.1.2'});assert.match(selected.url,/#note_1$/);assert.match(selected.status,/verify applicability/);assert.match(s.selectedReference(r.id).url,/#note_2$/);s.close();});

test('bounded resolution display retains the evidence behind its source-success label',()=>{const r={...report,labels:JSON.stringify(report.labels)};const notes=[note(1,'Upgrading to runner 17.1.2 fixed the issue.')];for(let i=0;i<20;i++)notes.push(note(i+2,'Try disabling cache as a workaround.',{createdAt:'2025-03-01'}));const e=extractEnrichment(r,notes);assert.equal(e.outcome.category,'source-reported-resolution');assert.equal(e.resolutions.length,12);assert.ok(e.resolutions.some(x=>x.kind==='source-reported-resolution'));});

test('affirmative quote preserves exact original wording including quoted configuration values',()=>{const r={...report,labels:JSON.stringify(report.labels)},body='Changing the helper image to "ubuntu" fixed the issue.';const e=extractEnrichment(r,[note(1,body)]);assert.equal(e.outcome.category,'source-reported-resolution');assert.equal(e.resolutions.find(x=>x.kind==='source-reported-resolution').quote,body);});

test('re-extraction preserves raw source rows and original collection timestamp',()=>{const s=setup(),r=s.get(report.id);saveNotePage(s.db,r,[note(1,'Changing image to "ubuntu" fixed the issue.')],'__COMPLETE__');finishEnrichment(s.db,r);const old=JSON.parse(s.db.prepare('SELECT extraction FROM enrichment_jobs WHERE report_id=?').get(r.id).extraction);old.extractionVersion='4';s.db.prepare('UPDATE enrichment_jobs SET completed_at=?,extraction=? WHERE report_id=?').run('2025-02-03T04:05:06Z',JSON.stringify(old),r.id);const rawBefore=s.db.prepare('SELECT * FROM evidence_notes').all(),reportsBefore=s.db.prepare('SELECT * FROM reports').all();reextract(s.db);assert.deepEqual(s.db.prepare('SELECT * FROM evidence_notes').all(),rawBefore);assert.deepEqual(s.db.prepare('SELECT * FROM reports').all(),reportsBefore);assert.equal(s.getEnrichment(r.id).completedAt,'2025-02-03T04:05:06Z');assert.equal(s.getEnrichment(r.id).extractionVersion,EXTRACTION_VERSION);s.close();});


test('legacy heldout issue aliases and subpaths cannot enter suggested evidence',()=>{const s=setup();const target='https://gitlab.com/gitlab-org/gitlab-runner/issues/999/designs#note_1';s.reserveSources(['https://gitlab.com/gitlab-org/gitlab-runner/-/work_items/999']);assert.equal(s.isReserved(target),true);saveNotePage(s.db,s.get(report.id),[note(1,'Legacyneedle failure. Upgrading to runner 17.2.0 fixed the issue. '+target)],'__COMPLETE__');finishEnrichment(s.db,s.get(report.id),[...s.reserved]);assert.equal(s.getEnrichment(report.id).resolutions.length,0);assert.equal(s.suggest('Legacyneedle').length,0);assert.ok(!s.selectedReference(report.id).summary.includes('fixed the issue'));s.close();});
test('legacy and modern MR aliases share one request while original citations survive',async()=>{const s=setup();const legacy='https://gitlab.com/gitlab-org/gitlab-runner/merge_requests/877#note_81090067',modern='https://gitlab.com/gitlab-org/gitlab-runner/-/merge_requests/877/diffs?version_id=2';saveNotePage(s.db,s.get(report.id),[note(1,legacy+' '+modern)],'__COMPLETE__');s.db.prepare("UPDATE evidence_links SET kind='related-issue'").run();normalizeLinkKinds(s.db);let calls=0;const client={mergeRequest:async url=>{calls++;assert.equal(url,'https://gitlab.com/gitlab-org/gitlab-runner/-/merge_requests/877');return {title:'Public fix',state:'merged'};}};await Promise.all([collectLinkedEvidence(s.db,s.get(report.id),client),collectLinkedEvidence(s.db,s.get(report.id),client)]);assert.equal(calls,1);const rows=s.db.prepare('SELECT * FROM evidence_links').all();assert.equal(rows.length,2);assert.equal(s.enrichmentStats().linkedEvidence,1);assert.equal(s.enrichmentStats().linkedEvidenceReferences,2);assert.ok(rows.every(r=>r.status==='fetched'));assert.ok(rows.some(r=>r.url===legacy));assert.ok(rows.some(r=>r.url===modern));finishEnrichment(s.db,s.get(report.id));assert.ok(s.getEnrichment(report.id).linkedEvidence.every(l=>l.canonicalUrl==='https://gitlab.com/gitlab-org/gitlab-runner/-/merge_requests/877'));s.close();});
test('imperative reproduction recipes are not successful remediation claims',()=>{const x=extractEnrichment({...report,body:'Set up a test project. Move it, watch the failure, set it back and it works again.'},[]);assert.notEqual(x.outcome.category,'source-reported-resolution');assert.equal(x.resolutions.filter(r=>r.kind==='source-reported-resolution').length,0);});

test('selected references preserve decisive quote and cited failed attempts for evidence packets',()=>{const s=setup();saveNotePage(s.db,s.get(report.id),[note(1,'Tried the workaround but it still fails.'),note(2,'Upgrading to runner 17.2.0 fixed the issue.',{createdAt:'2025-02-01'})],'__COMPLETE__');finishEnrichment(s.db,s.get(report.id));const ref=s.selectedReference(report.id);assert.equal(ref.quote,'Upgrading to runner 17.2.0 fixed the issue.');assert.equal(ref.sourceDate,'2025-02-01');assert.equal(ref.contradictions.length,1);assert.match(ref.contradictions[0].url,/#note_1$/);assert.equal(ref.contradictions[0].sourceDate,'2025-01-02T01:00:00Z');s.close();});

test('linked collector propagates internal storage or validation defects instead of assigning source failure',async()=>{const s=setup();saveNotePage(s.db,s.get(report.id),[note(1,'Fix !42')],'__COMPLETE__');await assert.rejects(()=>collectLinkedEvidence(s.db,s.get(report.id),{mergeRequest:async()=>{throw new Error('internal schema defect');}}),/internal schema defect/);assert.equal(s.enrichmentStats().linkedFailed,0);s.close();});

test('numeric GitLab identities ignore prose punctuation without losing heldout protection',async()=>{const s=setup();s.reserveSources(['https://gitlab.com/gitlab-org/gitlab-runner/-/issues/999']);assert.equal(s.isReserved('https://gitlab.com/gitlab-org/gitlab-runner/issues/999+'),true);const calls=[];const c=new PublicGitlabClient({minInterval:0,fetchFn:async url=>{calls.push(url);return new Response('{"title":"Public fix"}');}});await c.mergeRequest("https://gitlab.com/gitlab-org/gitlab-runner/-/merge_requests/6902's");await c.mergeRequest('https://gitlab.com/gitlab-org/gitlab-runner/-/merge_requests/3916+');assert.ok(calls[0].endsWith('/merge_requests/6902'));assert.ok(calls[1].endsWith('/merge_requests/3916'));assert.equal(await c.mergeRequest('https://gitlab.com/gitlab-org/gitlab-runner/-/merge_requests/3916abc'),null);s.close();});
