import {test} from 'node:test';import assert from 'node:assert/strict';
import {EvidenceStore} from '../server/evidence-store.js';import {cleanPublicText,retrievalTerms} from '../server/evidence-text.js';import {studySearch,studies} from '../server/study-library.js';import {investigationInput} from '../server/openai.js';import {Store} from '../server/db.js';
const report=(id,title,body)=>({id,url:'https://gitlab.com/gitlab-org/gitlab-runner/-/issues/'+id,title,body,author:'Example public name',createdAt:'2024-01-01',updatedAt:'2024-01-02',state:'closed',family:'Network & DNS',labels:['type::bug'],source:'GitLab Runner public issues'});
test('evidence index deduplicates, updates search and keeps closed reports unverified',()=>{const s=new EvidenceStore(':memory:');assert.equal(s.upsert(report('1','Certificate failure','x509 unknown authority in helper')),true);assert.equal(s.upsert(report('1','DNS lookup failure','dns resolver failure on alpine')),false);assert.equal(s.stats().indexed,1);assert.equal(s.stats().confirmed,0);assert.equal(s.search({q:'certificate'}).total,0);assert.equal(s.search({q:'dns'}).total,1);assert.equal(s.get('1').author,'Public user');assert.equal(s.get('1').review_status,'indexed');s.close();});
test('search is parameterized, paginated and family constrained',()=>{const s=new EvidenceStore(':memory:');for(let i=0;i<30;i++)s.upsert(report(String(i),'DNS lookup '+i,'Resolver problem observed'));assert.equal(s.search().rows.length,24);assert.equal(s.search({page:2}).rows.length,6);assert.equal(s.search({page:1.9}).page,1);assert.equal(s.search({family:"' OR 1=1 --"}).total,0);assert.doesNotThrow(()=>s.search({q:'" OR * : ( )'}));assert.equal(s.stats().indexed,30);s.close();});
test('technical retrieval returns bounded evidence and no irrelevant default matches',()=>{const s=new EvidenceStore(':memory:');s.upsert(report('1','x509 certificate unknown authority','TLS helper trust store'));s.upsert(report('2','Cache permission denied','cache ownership user'));assert.equal(s.suggest('my certificate has unknown authority')[0].id,'1');assert.equal(s.suggest('help with our earlier unrelated issue').length,0);assert.deepEqual(retrievalTerms('make me a sandwich'),[]);assert.equal(s.selectedReference('1').kind,'unreviewed-public-report');assert.equal(s.selectedReference('missing'),null);s.close();});
test('public credentials and contact details are redacted; text stays inert',()=>{const raw='api_key=notasecretforproduction password=pretend123 hello@example.com glpat-1234567890abcdefghijkl <script>alert(1)</script>';const clean=cleanPublicText(raw);assert.ok(!clean.includes('pretend123'));assert.ok(!clean.includes('hello@example.com'));assert.ok(!clean.includes('glpat-'));assert.ok(clean.includes('<script>'));const s=new EvidenceStore(':memory:');s.upsert(report('1','Example',raw));assert.equal(s.get('1').body,clean);s.close();});
test('first-party studies have distinct operator, publisher and technical context',()=>{assert.ok(studies.length>=16);assert.equal(new Set(studies.map(s=>s.url)).size,studies.length);for(const s of studies){assert.ok(s.company&&s.affectedOrganization&&s.sourcePublisher&&s.vendor&&s.learning);assert.equal(s.reviewStatus,'source-reviewed');assert.equal(s.outcomeStatus,'publisher-reported');assert.ok(s.url.startsWith('https://'));}assert.equal(studySearch('calico kubernetes labels upgrade')[0].id,'STUDY-reddit-2023');assert.equal(studySearch('sandwich unicorn').length,0);});
test('selected public evidence retains trust labels and whole text within the model budget',()=>{const store=new Store(':memory:'),c=store.read().cases[0];const refs=[{id:'SRC-one',title:'Public report',summary:'z'.repeat(3000),question:'Verify independently',url:'https://gitlab.com/example',versions:'unknown',kind:'unreviewed-public-report',status:'Outcome unverified'}];const input=investigationInput(c,[],refs);assert.equal(input.evidence[0].summary.length,3000);assert.equal(input.evidence[0].status,'Outcome unverified');assert.equal(input.evidence[0].kind,'unreviewed-public-report');assert.ok(!JSON.stringify(input).includes('Contact not public'));store.close();});

test('reserved source threads are excluded from suggestions and selected model evidence',()=>{const s=new EvidenceStore(':memory:');s.upsert(report('1','Certificate failure','x509 certificate'));s.reserveSources(['https://gitlab.com/gitlab-org/gitlab-runner/-/issues/1#note_5']);assert.equal(s.suggest('certificate').length,0);assert.equal(s.selectedReference('1'),null);assert.equal(s.search({q:'certificate'}).rows[0].reserved,true);s.close();});

test('historical case search finds issue IDs and combines source status with content and family',()=>{
 const s=new EvidenceStore(':memory:');
 s.upsert({...report('gitlab-runner-37242','Runner restarts unexpectedly','Kubernetes liveness symptoms only'),state:'opened',family:'Runner lifecycle'});
 s.upsert({...report('gitlab-runner-39039','Runner restarts while caching','Kubernetes helper symptoms only'),state:'closed',family:'Caching'});
 assert.equal(s.search({q:'#37242'}).rows[0].id,'gitlab-runner-37242');
 assert.equal(s.search({q:'gitlab-runner-39039'}).rows[0].id,'gitlab-runner-39039');
 assert.equal(s.search({q:'Runner',state:'opened'}).total,1);
 assert.equal(s.search({q:'Runner',state:'closed',family:'Caching',kind:'Bug report'}).rows[0].id,'gitlab-runner-39039');
 assert.equal(s.search({q:'37242',state:'closed'}).total,0);
 s.reserveSources(['https://gitlab.com/gitlab-org/gitlab-runner/-/issues/gitlab-runner-37242']);assert.equal(s.get('gitlab-runner-37242').reserved,true);
 assert.equal(s.stats().confirmed,0);s.close();
});
