import test from 'node:test';
import assert from 'node:assert/strict';
import {approveKnowledge,hash} from '../server/domain.js';
import {LearningCloseout,assertManualLearningPolicies} from '../server/learning-closeout.js';
import {verifiedArticleScope,investigationTagGroups} from '../server/hindsight-scope.js';

function fixture(){
 let state={workspaceId:'isolated-learning-test',companies:[],articles:[],cases:[{id:'CASE-NEW',contact:'Public reporter',host:'',title:'Reported connection failure',description:'A failed job',symptom:'Connection failure',executor:'Docker',hosting:'Self-managed',runnerVersion:'19.3.0',serverVersion:'',chartVersion:'',sourceId:null,sourceDate:null,occurredAt:null,reconstructed:false,articleIds:[],timeline:[],attempts:[{step:'Restart the service',result:'Failed',evidence:'The same error remained.',at:'2026-09-29T10:00:00Z'}],resolution:{fix:'Corrected the reviewed connection configuration.',cause:'A wrong configured endpoint.',evidence:'The same failing job passed after the reviewed correction.',limitations:'Only this confirmed deployment.',engineer:'Reviewer'}}],outbox:[],memories:[],events:[]};
 const store={read:()=>structuredClone(state),update:fn=>{const next=structuredClone(state),result=fn(next);state=next;return result;}};
 const input={reviewed:true,reviewer:'Reviewer',title:'Reviewed connection correction',fix:state.cases[0].resolution.fix,cause:state.cases[0].resolution.cause,verification:state.cases[0].resolution.evidence,limitations:'Only matching deployment conditions.',runnerVersion:'19.3.0',serverVersion:'',chartVersion:''};
 const article=store.update(s=>approveKnowledge(s,'CASE-NEW',input)),controls={connection:'connection-one',authorized:true,retainError:null,status:'completed',document:null,policy:{total:1,items:[{id:'manual-model',trigger:{refresh_after_consolidation:false,refresh_cron:null}}]},hook:null},calls=[],reservations=[];
 const provider={c:{memoryMode:'hindsight',allowExternal:true,bank:'isolated-bank'},scope:()=>`lucid-workspace-${state.workspaceId}`,getClient:()=>({listMentalModels:async(bank,options)=>{calls.push({kind:'policies',bank,options});assert.equal(options.detail,'content');assert.equal(options.limit,20);await controls.hook?.('policies');return controls.policy;},getDocument:async(bank,docId)=>{calls.push({kind:'document',bank,docId});await controls.hook?.('document');if(!controls.document)throw Object.assign(new Error('not found'),{status:404});return structuredClone(controls.document);}}),operation:async(action,id)=>{calls.push({kind:'status',action,id});await controls.hook?.('status');return {status:controls.status};},retain:async(a,{plan,operationId,async})=>{calls.push({kind:'retain',plan:structuredClone(plan),operationId,async});const persisted=store.read();assert.equal(persisted.learningCloseouts[Object.keys(persisted.learningCloseouts)[0]].attempts,1);assert.equal(persisted.articles[0].cloudRetention.status,'dispatched');assert.deepEqual(persisted.cloudPackets[`connection-one:${a.id}:${a.revision}`],plan);assert.equal(async,true);await controls.hook?.('retain');if(controls.retainError)throw controls.retainError;controls.document={id:plan.docId,original_text:plan.packet.content,tags:plan.packet.tags,memory_unit_count:2,document_metadata:plan.packet.metadata};return {provider:'hindsight',docId:plan.docId,result:{async:true,operation_id:operationId}};}};
 const authorize=async request=>{reservations.push(structuredClone(request));if(!controls.authorized)throw Error('private budget denial');return {complete:async()=>{calls.push({kind:'ledger-complete',operation:request.request.operation});},fail:async()=>{calls.push({kind:'ledger-fail',operation:request.request.operation});}};};const service=()=>new LearningCloseout(store,()=>provider,{connectionId:()=>controls.connection,authorize,now:()=> '2026-09-29T11:00:00Z'});
 return {store,article,input,controls,calls,reservations,provider,service};
}
const queue=x=>x.service().enqueue(x.article.id,{caseId:'CASE-NEW',expectedRevision:1});
test('explicitly approved lesson queues one immutable packet then retains, verifies and becomes exactly retrievable',async()=>{
 const x=fixture(),before=x.store.read(),queued=queue(x);assert.equal(queued.status,'pending');assert.equal(x.calls.length,0);assert.equal(queued.plan,undefined);const frozen=x.store.read().learningCloseouts[queued.key],packet=JSON.parse(frozen.plan.packet.content);assert.equal(packet.failedOrInconclusiveAttempts[0].result,'Failed');assert.equal(packet.failedOrInconclusiveAttempts[0].evidence,'The same error remained.');
 const result=await x.service().run(queued.key);assert.equal(result.status,'succeeded');const state=x.store.read(),article=state.articles[0];assert.equal(verifiedArticleScope(article,{connectionId:x.controls.connection,scope:frozen.scope}),true);assert.deepEqual(investigationTagGroups([article],frozen.scope)[0].or[0].tags,frozen.plan.packet.tags);assert.equal(article.cloudRetention.retryable,false);assert.equal(article.cloudScope.policyVersion,2);assert.equal(article.cloudScope.contentHash,hash(frozen.plan.packet.content));
 assert.deepEqual(state.cases,before.cases);assert.deepEqual(state.outbox,before.outbox);assert.deepEqual(state.companies,before.companies);assert.deepEqual(state.learningCloseouts[queued.key].plan,frozen.plan);assert.equal(article.fingerprint,before.articles[0].fingerprint);assert.deepEqual(x.reservations.map(r=>r.kind),['learning-policy-read','learning-retain','learning-metadata','learning-metadata']);assert.equal(x.calls.filter(c=>c.kind==='retain').length,1);
 await x.service().run(queued.key);assert.equal(queue(x).key,queued.key);assert.equal(x.calls.filter(c=>c.kind==='retain').length,1);
});
test('unconfigured and unauthorized learning stays pending without retaining or changing operational outbox',async()=>{
 const x=fixture();x.controls.connection=null;const q=queue(x),before=x.store.read().outbox;assert.equal((await x.service().run(q.key)).status,'pending');assert.equal(x.calls.length,0);assert.equal(x.reservations.length,0);x.controls.connection='connection-one';x.controls.authorized=false;assert.equal((await x.service().run(q.key)).status,'pending');assert.equal(x.calls.length,0);assert.equal(x.store.read().articles[0].cloudRetention,undefined);assert.deepEqual(x.store.read().outbox,before);assert.ok(!JSON.stringify(x.store.read().learningCloseouts).includes('private budget denial'));
});
test('drafts, unconfirmed outcomes, unreviewed articles and immutable corpus articles cannot queue',()=>{
 for(const change of [s=>{s.cases[0].resolution=null;},s=>{s.cases[0].resolution.evidence='';},s=>{s.articles[0].reviewer='';},s=>{s.articles[0].curation={immutable:true};},s=>{s.cases[0].articleIds=[];}]){const x=fixture();x.store.update(change);assert.throws(()=>queue(x),/explicitly reviewed/);assert.equal(x.calls.length,0);}
 const x=fixture();assert.throws(()=>x.service().enqueue(x.article.id,{caseId:'CASE-NEW',expectedRevision:2}),/explicitly reviewed/);
});
test('uncertain write is durable across restart and is reconciled by reads without a replacement or retry',async()=>{
 const x=fixture(),q=queue(x);x.controls.retainError=Error('secret provider request detail');let result=await x.service().run(q.key);assert.equal(result.status,'unverified');assert.equal(x.store.read().learningCloseouts[q.key].attempts,1);assert.equal(x.calls.filter(c=>c.kind==='retain').length,1);result=await x.service().run(q.key);assert.equal(result.status,'unverified');assert.equal(x.calls.filter(c=>c.kind==='retain').length,1);assert.ok(!JSON.stringify(x.store.read()).includes('secret provider request detail'));
 const frozen=x.store.read().learningCloseouts[q.key];x.controls.document={id:frozen.plan.docId,original_text:frozen.plan.packet.content,tags:frozen.plan.packet.tags,memory_unit_count:1,document_metadata:frozen.plan.packet.metadata};assert.equal((await x.service().check(q.key)).status,'succeeded');assert.equal(x.calls.filter(c=>c.kind==='retain').length,1);
});
test('bounded checks never equate accepted or completed operation with verified source facts',async()=>{
 const x=fixture(),q=queue(x);x.controls.status='processing';x.controls.hook=async phase=>{if(phase==='document')x.controls.document=null;};let result=await x.service().run(q.key,{maxChecks:3});assert.equal(result.status,'processing');assert.equal(result.checks,3);assert.equal(x.calls.filter(c=>c.kind==='status').length,3);assert.equal(x.store.read().articles[0].cloudScope,undefined);
 x.controls.status='failed';result=await x.service().check(q.key);assert.equal(result.status,'failed');assert.equal(result.attempts,1);assert.equal(x.calls.filter(c=>c.kind==='retain').length,1);await assert.rejects(x.service().run(q.key,{maxChecks:4}),/zero to three/);
});
test('whole content, exact tags, packet metadata and nonzero facts are all required for eligibility',async()=>{
 const mutations=[d=>d.original_text+=' altered',d=>d.tags.push('foreign-source'),d=>d.tags.pop(),d=>d.memory_unit_count=0,d=>d.document_metadata.hash='wrong',d=>delete d.document_metadata.packet_hash,d=>delete d.original_text];
 for(const mutation of mutations){const x=fixture(),q=queue(x);await x.service().run(q.key,{maxChecks:0});mutation(x.controls.document);const result=await x.service().check(q.key);assert.equal(result.status,'unverified');assert.equal(x.store.read().articles[0].cloudScope,undefined);assert.equal(x.calls.filter(c=>c.kind==='retain').length,1);}
});
test('changed source, connection or workspace fails closed before or after network without a second write',async()=>{
 for(const phase of ['policies','retain','document']){const x=fixture(),q=queue(x);x.controls.hook=async where=>{if(where===phase)x.controls.connection='different-connection';};const result=await x.service().run(q.key);assert.equal(result.status,phase==='policies'?'pending':'unverified');assert.equal(x.store.read().articles[0].cloudScope,undefined);assert.ok(x.calls.filter(c=>c.kind==='retain').length<=1);}
 for(const change of [s=>s.articles[0].fix='unreviewed edit',s=>s.cases[0].resolution.evidence='changed outcome',s=>s.workspaceId='different-workspace',s=>s.learningCloseouts[Object.keys(s.learningCloseouts)[0]].plan.packet.content+='tampered']){const x=fixture(),q=queue(x);x.store.update(change);assert.equal((await x.service().run(q.key)).status,'pending');assert.equal(x.calls.length,0);}
});
test('manual-refresh policy check rejects automatic, unknown, incomplete and duplicate model inventories',async()=>{
 for(const response of [{total:21,items:[]},{total:1,items:[{id:'one',trigger:null}]},{total:1,items:[{id:'one',trigger:{refresh_after_consolidation:true,refresh_cron:null}}]},{total:1,items:[{id:'one',trigger:{refresh_after_consolidation:false,refresh_cron:'0 * * * *'}}]},{total:0,items:[],has_more:true},{total:2,items:[{id:'same',trigger:{refresh_after_consolidation:false,refresh_cron:null}},{id:'same',trigger:{refresh_after_consolidation:false,refresh_cron:null}}]}]){assert.throws(()=>assertManualLearningPolicies(response));const x=fixture(),q=queue(x);x.controls.policy=response;assert.equal((await x.service().run(q.key)).status,'pending');assert.equal(x.calls.filter(c=>c.kind==='retain').length,0);}
 assert.deepEqual(assertManualLearningPolicies({total:0,items:[]}),{modelCount:0,automaticRefresh:false});
});
test('two independent workers cannot both dispatch the same queued revision',async()=>{
 const x=fixture(),q=queue(x);let release;const pending=new Promise(resolve=>{release=resolve;});x.controls.hook=async phase=>{if(phase==='policies')await pending;};const first=x.service().run(q.key,{maxChecks:0});await new Promise(resolve=>setImmediate(resolve));const second=await x.service().run(q.key,{maxChecks:0});assert.equal(second.status,'preparing');release();assert.equal((await first).status,'processing');assert.equal(x.calls.filter(c=>c.kind==='retain').length,1);
});

test('real SQLite closeout guards never open nested write transactions',async()=>{
 const {Store}=await import('../server/db.js');const x=fixture(),store=new Store(':memory:');
 try{store.update(s=>{for(const key of Object.keys(s))delete s[key];Object.assign(s,x.store.read());});const service=new LearningCloseout(store,()=>x.provider,{connectionId:()=>x.controls.connection,authorize:x.reservations.push.bind(x.reservations)});const queued=service.enqueue(x.article.id,{caseId:'CASE-NEW',expectedRevision:1});store.update(s=>service.guard(s.learningCloseouts[queued.key]));assert.equal(store.read().learningCloseouts[queued.key].status,'pending');}finally{store.close();}
});
