// Distinct first-person historical reports, never pre-approved shared articles.
export const additionalSources=[
 {id:'GL-6144',title:'Required job outputs expire before the next stage · Aug 2018',url:'https://gitlab.com/gitlab-org/gitlab/-/work_items/6144#note_96403947',type:'Public issue report',verification:'Rendered public report verified 27 Sep 2026. Edited 23 Aug 2018 to confirm the workaround; independently echoed by another reporter on 25 Sep 2018.',summary:'Explicit artifact lifetime reportedly resolved a missing-dependency failure. Exact versions for this episode are not established.'},
 {id:'FORUM-92388',title:'Windows hosted workers lose container DNS · Sep 2023',url:'https://forum.gitlab.com/t/docker-containers-on-shared-windows-runners-lost-internet-connection/92388/6',type:'Public forum report',verification:'Indexed primary discussion reviewed 27 Sep 2026. Maintainer remediation followed by reporter confirmation on 21 Sep 2023.',summary:'DNS failed inside Windows containers. Reported recovery is specific to this hosted-worker episode; no universal DNS setting is inferred.'},
 {id:'FORUM-105511',title:'Cache unavailable to concurrent Docker jobs · Jan 2026',url:'https://forum.gitlab.com/t/trouble-with-concurrent-pipelines-and-caching/105511/3',type:'Public forum report',verification:'Indexed first-person follow-up by the reporter, 20 Jan 2026; self-reported success, not independently reproduced.',summary:'Explicit shared cache mapping reportedly restored visibility across four concurrent jobs. Product versions and broader isolation requirements are unknown.'},
 {id:'FORUM-81117',title:'Container build regression after image update · Feb 2023',url:'https://forum.gitlab.com/t/the-ci-cd-pipeline-suddenly-fails-without-any-changes-done-to-the-repository/81117/3',type:'Public forum report',verification:'Indexed primary discussion: workaround by one participant and confirmation by another, 3 Feb 2023.',summary:'Pinning the build and service images reportedly restored builds. Historical workaround only; the exact root cause and current-safe image are not established.'},
 {id:'REDDIT-KUBECONFIG',title:'Worker still fails after cluster certificate renewal · Feb 2025',url:'https://www.reddit.com/r/gitlab/comments/1iylc3e/',type:'First-person community report',verification:'Indexed original poster update and follow-up reviewed 27 Sep 2026. Self-reported resolution, lower confidence than independent reproduction.',summary:'Host-installed Kubernetes executor continued using stale client configuration after renewal. Re-registering the worker had failed.'},
];
export const additionalOutcomes={
 'CS-2005':{sourceId:'GL-6144',fix:'Set an explicit artifacts:expire_in value long enough for the downstream job to consume the output.',cause:'',verification:'The reporter edited the public report on 23 August 2018 to state that this resolved the failure. A separate reporter later confirmed the same workaround.',limitations:'Historical artifact-lifetime behavior. Inspect actual expiry and dependencies; the report does not establish whether this was a product defect or configuration issue.'},
 'CS-2001':{sourceId:'FORUM-92388',fix:'The hosting team restored container DNS resolution by configuring external DNS servers; the affected reporter confirmed recovery.',cause:'',verification:'Maintainer update at post 5 followed by the reporter confirming success at post 6, 21 September 2023.',limitations:'Historical hosted Windows worker episode. Do not change organization DNS or infer a shared incident without matching host, time and service evidence.'},
 'CS-2002':{sourceId:'FORUM-105511',fix:'The reporter configured an explicit host cache directory and mapped it to /cache for the Docker workers.',cause:'',verification:'The reporter reported that all four concurrent jobs could then access the cache, 20 January 2026.',limitations:'Self-reported Docker configuration, versions unknown. Review cache isolation and ownership; sharing a directory across untrusted projects can be inappropriate.'},
 'CS-2003':{sourceId:'FORUM-81117',fix:'The team temporarily pinned both the build image and Docker service image to the previously working image digest.',cause:'',verification:'A second participant confirmed that the proposed pin addressed their failure on 3 February 2023.',limitations:'Historical rollback workaround, not a recommendation to deploy obsolete images today. Check current supported versions and identify the regression before reuse.'},
 'CS-2004':{sourceId:'REDDIT-KUBECONFIG',fix:'The reporter refreshed the host-installed worker’s stale Kubernetes client configuration after certificate renewal and restarted the worker service.',cause:'',verification:'Original poster reported successful recovery on 26–27 February 2025 after re-registration had not helped.',limitations:'GitLab server 17.3.3 and Runner 17.3.1 were reported. This worker ran on a host, not in a pod. Do not copy administrator credentials to workers; have the cluster owner provision appropriately scoped credentials.'},
};
export function additionalCases(base){return [
 {...base,id:'CS-2005',companyId:'org-i',contact:'Reconstructed contact',title:'The next pipeline stage cannot retrieve its required output',description:'After adding a test report, a later job fails with a missing-dependency error. The report files appear to disappear before they can be consumed.',hosting:'Unknown',executor:'Unknown',symptom:'artifact-expiry',stage:'Artifact download',sourceId:'GL-6144',sourceDate:'2018-08-23',reconstructed:true},
 {...base,id:'CS-2001',companyId:'org-e',contact:'Reconstructed contact',title:'Windows build containers cannot resolve package hosts',description:'Network access fails inside build containers on hosted Windows workers, while the same container works locally.',hosting:'GitLab.com',executor:'Unknown',symptom:'container-dns',stage:'Build network',sourceId:'FORUM-92388',sourceDate:'2023-09-11',reconstructed:true},
 {...base,id:'CS-2002',companyId:'org-f',contact:'Reconstructed contact',title:'Only the first concurrent job can find its cache',description:'With four jobs running concurrently, only one worker can access the expected cache. Other jobs miss it.',hosting:'Unknown',executor:'Docker',symptom:'concurrent-cache',stage:'Cache',sourceId:'FORUM-105511',sourceDate:'2026-01-20',reconstructed:true},
 {...base,id:'CS-2003',companyId:'org-g',contact:'Reconstructed contact',title:'Container builds fail without a repository change',description:'Previously working builds started failing even though the project configuration did not change. The build uses a moving container image tag.',hosting:'GitLab.com',executor:'Unknown',symptom:'image-regression',stage:'Image build',sourceId:'FORUM-81117',sourceDate:'2023-02-03',reconstructed:true},
 {...base,id:'CS-2004',companyId:'org-h',contact:'Reconstructed contact',title:'Jobs still fail after renewing cluster certificates',description:'The cluster certificates were renewed, but the host-installed worker still fails while preparing credentials. Re-registering the worker did not help.',hosting:'Self-managed',executor:'Kubernetes',serverVersion:'17.3.3',runnerVersion:'17.3.1',symptom:'cluster-client-credentials',stage:'Environment setup',sourceId:'REDDIT-KUBECONFIG',sourceDate:'2025-02-26',reconstructed:true,attempts:[{id:'historical-register-failed',step:'Re-register the worker',result:'Failed',evidence:'The original poster explicitly reported that re-registration did not help.',at:'2025-02-26T00:00:00Z'}]},
].map(c=>structuredClone(c));}
export const additionalCompanies=['E','F','G','H','I'].map((name)=>({id:`org-${name.toLowerCase()}`,name:`Anonymous public user ${name}`,note:'Public report · company affiliation unknown'}));
