import {z} from 'zod';
import {readFileSync} from 'node:fs';
import {initialState,sources,hiddenOutcomes} from './fixtures.js';
import {DomainError,event,hash} from './domain.js';
const short=z.string().trim().min(1).max(200),body=z.string().trim().min(3).max(3000);
export const corpusRecord=z.object({partition:z.enum(['reference','holdout']).default('reference'),id:z.string().regex(/^[a-zA-Z0-9_-]{3,80}$/),title:short,report:body,failureType:short,executor:z.enum(['Kubernetes','Docker','Shell','Unknown']),hosting:z.enum(['Self-managed','GitLab.com','Dedicated','Unknown']),versions:z.object({server:z.string().max(80),runner:z.string().max(80),chart:z.string().max(80)}).strict(),source:z.object({url:z.string().url().refine(v=>new URL(v).protocol==='https:'),date:z.string().date(),reviewedAt:z.string().date(),reviewer:short,inspection:z.enum(['rendered','indexed']),confidence:z.enum(['reporter-confirmed','maintainer-confirmed','provider-confirmed','unresolved']),note:body}).strict(),unsuccessfulSteps:z.array(z.object({step:body,evidence:body}).strict()).max(12),outcome:z.object({type:z.enum(['workaround','reported-resolution','provider-recovery','unresolved']),fix:z.string().max(3000),cause:z.string().max(3000),verification:body,limitations:body}).strict()}).strict().refine(r=>r.outcome.type==='unresolved'||r.outcome.fix.trim().length>=3,{message:'A reported outcome needs a fix or recovery description.',path:['outcome','fix']});
export const corpusBatch=z.object({records:z.array(corpusRecord).min(1).max(30)}).strict();
const sourceKey=r=>`${new URL(r.source.url).href.replace(/\/$/,'')}|${r.source.date}`;
export function publicRecord(r){const {outcome,...safe}=r;return {...safe,outcomeType:outcome.type,hasOutcome:outcome.type!=='unresolved',knownVersions:Object.values(r.versions).some(Boolean)};}
export function reviewImport(s,records){const additions=[],duplicates=[];const seen=[...(s.corpus||[])];for(const r of records){const existing=seen.find(x=>x.id===r.id||sourceKey(x)===sourceKey(r));if(existing){if(existing.id===r.id&&hash(existing)!==hash(r))throw new DomainError(`Record ${r.id} already exists with different content. Use a new source episode ID; existing evidence is never overwritten.`,409);duplicates.push(r.id);}else{additions.push(r);seen.push(r);}}return {additions,duplicates};}
export function importCorpus(s,records){const plan=reviewImport(s,records);s.corpus??=[];s.corpus.push(...structuredClone(plan.additions));return {added:plan.additions.length,duplicates:plan.duplicates};}
export const coverageTypes=['Runner health','Artifact upload','Artifact download','Provider availability','DNS','Cache','Image build','Cluster credentials','Shell initialization','Proxy / TLS routing','Runner registration','Upgrade','Service volumes','Network transport','Pod scheduling','Image pull','Cluster authorization','SSH authentication','Observability','TLS trust','Image compatibility','Registry authentication','Storage exhaustion'];
export function coverage(records){return [...new Set([...coverageTypes,...records.map(r=>r.failureType)])].map(type=>{const rows=records.filter(r=>r.failureType===type);return {type,total:rows.length,executors:Object.fromEntries(['Kubernetes','Docker','Shell','Unknown'].map(e=>[e,rows.filter(r=>r.executor===e).length])),knownVersions:rows.filter(r=>Object.values(r.versions).some(Boolean)).length,failedSteps:rows.filter(r=>r.unsuccessfulSteps.length).length,rendered:rows.filter(r=>r.source.inspection==='rendered').length,reportedOutcomes:rows.filter(r=>r.outcome.type!=='unresolved').length};});}
export function corpusSnapshot(s){const records=s.corpus||[];return {records:records.map(publicRecord),coverage:coverage(records),totals:{reports:records.length,outcomes:records.filter(r=>r.outcome.type!=='unresolved').length,holdout:records.filter(r=>r.partition==='holdout').length,confirmedCauses:records.filter(r=>r.outcome.cause.trim()).length,knownVersions:records.filter(r=>Object.values(r.versions).some(Boolean)).length,withFailedSteps:records.filter(r=>r.unsuccessfulSteps.length).length,rendered:records.filter(r=>r.source.inspection==='rendered').length}};}
export function seedCorpus(s){
 const seed=initialState();const types={'runner-restarts':'Runner health','artifact-upload':'Artifact upload','service-unavailable':'Provider availability','container-dns':'DNS','concurrent-cache':'Cache','image-regression':'Image build','cluster-client-credentials':'Cluster credentials','artifact-expiry':'Artifact download'};
 const initial=seed.cases.map(c=>{const source=sources.find(x=>x.id===c.sourceId),out=hiddenOutcomes[c.id];return {id:`seed-${c.id}`,title:c.title,report:c.description,failureType:types[c.symptom],executor:c.executor,hosting:c.hosting,versions:{server:c.serverVersion,runner:c.runnerVersion,chart:c.chartVersion},source:{url:source.url,date:c.sourceDate,reviewedAt:'2026-09-27',reviewer:'Local evidence review',inspection:['GL-37242','GL-26869','GL-6144'].includes(c.sourceId)?'rendered':'indexed',confidence:c.sourceId==='INC-15997'?'provider-confirmed':'reporter-confirmed',note:source.verification},unsuccessfulSteps:c.attempts.filter(a=>a.result==='Failed').map(a=>({step:a.step,evidence:a.evidence})),outcome:out?{type:'workaround',fix:out.fix,cause:out.cause,verification:out.verification,limitations:out.limitations}:{type:'provider-recovery',fix:'Provider restored the affected service.',cause:'',verification:source.summary,limitations:'Historical incident only. Match the exact host, time and affected service.'}};});
 const expansion=JSON.parse(readFileSync(new URL('../data/corpus-expansion.json',import.meta.url),'utf8'));
 importCorpus(s,corpusBatch.parse({records:[...initial,...expansion.records.map((r,i)=>({...r,partition:r.partition||(i>=4&&i<6?'holdout':'reference')}))]}).records);
}
export function openReplay(s,id){
 const r=(s.corpus||[]).find(x=>x.id===id);if(!r)throw new DomainError('Research record not found.',404);
 if(r.partition==='holdout')throw new DomainError('Heldout cases are reserved for separate evaluation and cannot be opened as operational cases.',409);
 const existing=s.cases.find(c=>c.corpusId===id);if(existing)return existing;
 const legacy=id.startsWith('seed-')?s.cases.find(c=>c.id===id.slice(5)&&c.reconstructed):null;if(legacy)return legacy;
 const companyId='research-replay';if(!s.companies.some(c=>c.id===companyId))s.companies.push({id:companyId,name:'Anonymous public reports',kind:'public-source',note:'Historical research exercises; no company affiliation established'});
 const caseId=`CS-${Math.max(...s.cases.map(c=>Number(c.id.slice(3))))+1}`,sourceId=`CORPUS-${r.id}`;
 const c={...structuredClone(initialState().cases[0]),id:caseId,corpusId:id,companyId,contact:'Public source · historical exercise',title:r.title,description:r.report,hosting:r.hosting,executor:r.executor,serverVersion:r.versions.server,runnerVersion:r.versions.runner,chartVersion:r.versions.chart,stage:r.failureType,symptom:r.failureType.toLowerCase().replace(/[^a-z0-9]+/g,'-'),sourceId,sourceDate:r.source.date,reconstructed:true,attempts:r.unsuccessfulSteps.map((a,i)=>({...a,id:`${caseId}-attempt-${i}`,result:'Failed',at:r.source.date})),incidentLinks:[]};
 s.corpusSources??=[];s.corpusSources.push({id:sourceId,title:r.title,url:r.source.url,type:'Public research report',verification:r.source.note,summary:'A source-reviewed historical episode. Outcome is withheld until explicit replay review.'});
 s.replayOutcomes??={};if(r.outcome.type!=='unresolved')s.replayOutcomes[caseId]={sourceId,...r.outcome};s.cases.unshift(c);event(s,c,'Research replay opened. Source outcome withheld; no shared knowledge or Cloud memory created.');return c;
}
