import {createHash} from 'node:crypto';
import {cleanPublicText,canonicalPublicUrl} from './evidence-text.js';
import {EXTRACTION_VERSION,extractEnrichment,publicLinks} from './enrichment-extract.js';
export function initEnrichment(db){db.exec(`
 CREATE TABLE IF NOT EXISTS enrichment_jobs(report_id TEXT PRIMARY KEY,status TEXT NOT NULL DEFAULT 'pending',cursor TEXT,pages INTEGER NOT NULL DEFAULT 0,attempts INTEGER NOT NULL DEFAULT 0,started_at TEXT,updated_at TEXT,completed_at TEXT,error TEXT,retry_at TEXT,extraction TEXT);
 CREATE TABLE IF NOT EXISTS enrichment_pages(report_id TEXT,request_cursor TEXT,next_cursor TEXT,returned_notes INTEGER,ids_sha256 TEXT,fetched_at TEXT,PRIMARY KEY(report_id,request_cursor));
 CREATE TABLE IF NOT EXISTS evidence_notes(id TEXT PRIMARY KEY,report_id TEXT NOT NULL,discussion_id TEXT,body TEXT,url TEXT,created_at TEXT,updated_at TEXT,system INTEGER NOT NULL DEFAULT 0,truncated INTEGER NOT NULL DEFAULT 0,fetched_at TEXT);
 CREATE INDEX IF NOT EXISTS evidence_notes_report ON evidence_notes(report_id,created_at,id);
 CREATE VIRTUAL TABLE IF NOT EXISTS note_search USING fts5(id UNINDEXED,report_id UNINDEXED,body);
 CREATE TABLE IF NOT EXISTS evidence_links(url TEXT PRIMARY KEY,kind TEXT,status TEXT,title TEXT,state TEXT,merged_at TEXT,description TEXT,fetched_at TEXT,error TEXT);
 CREATE TABLE IF NOT EXISTS evidence_report_links(report_id TEXT,url TEXT,source_url TEXT,PRIMARY KEY(report_id,url,source_url));
 CREATE TABLE IF NOT EXISTS enrichment_runs(id INTEGER PRIMARY KEY,started_at TEXT,finished_at TEXT,status TEXT,pid INTEGER,heartbeat_at TEXT,processed INTEGER DEFAULT 0,error TEXT);
 `);}
export function seedEnrichment(db){return db.prepare('INSERT OR IGNORE INTO enrichment_jobs(report_id) SELECT id FROM reports').run().changes;}
export function enrichmentStats(db){
 const counts={pending:0,collecting:0,completed:0,unavailable:0,failed:0};for(const r of db.prepare('SELECT status,count(*) n FROM enrichment_jobs GROUP BY status').all())counts[r.status]=r.n;
 const total=db.prepare('SELECT count(*) n FROM reports').get().n;const tracked=Object.values(counts).reduce((a,b)=>a+b,0);counts.pending+=Math.max(0,total-tracked);
 const notes=db.prepare('SELECT count(*) total,coalesce(sum(CASE WHEN system=0 THEN 1 ELSE 0 END),0) comments,coalesce(sum(truncated),0) truncated FROM evidence_notes').get();
 const outcomes=db.prepare("SELECT json_extract(extraction,'$.outcome.category') category,count(*) count FROM enrichment_jobs WHERE extraction IS NOT NULL AND status='completed' GROUP BY category").all();
 const linkedRows=db.prepare("SELECT url,status FROM evidence_links WHERE kind='merge-request'").all(),linkStates=new Map(),priority={fetched:3,failed:2,'linked-not-fetched':1};for(const l of linkedRows){const key=canonicalPublicUrl(l.url),previous=linkStates.get(key);if(!previous||(priority[l.status]||0)>(priority[previous]||0))linkStates.set(key,l.status);}const linkedCount=status=>[...linkStates.values()].filter(s=>s===status).length;
 return {total,...counts,notes:notes.total,discussionNotes:notes.comments,truncatedNotes:notes.truncated,sourceSupportedCandidates:outcomes.find(r=>r.category==='source-reported-resolution')?.count||0,humanReviewed:0,confirmed:0,outcomes,linkedEvidence:linkedCount('fetched'),linkedEvidenceReferences:linkedRows.filter(l=>l.status==='fetched').length,linkedPending:linkedCount('linked-not-fetched'),linkedFailed:linkedCount('failed'),latestRun:db.prepare('SELECT * FROM enrichment_runs ORDER BY id DESC LIMIT 1').get()||null};
}
export function getEnrichment(db,id){const r=db.prepare('SELECT * FROM enrichment_jobs WHERE report_id=?').get(id);if(!r)return {status:'pending',collectionComplete:false,notesCount:0,discussionNotes:0,humanReviewed:false,outcome:{category:'insufficient-evidence',label:'Discussion not collected',confirmed:false,humanReviewed:false},versions:[],environment:[],attempts:[],resolutions:[],tasks:[],linkedEvidence:[]};const linkCounts=db.prepare("SELECT l.status,count(DISTINCT l.url) n FROM evidence_report_links r JOIN evidence_links l ON l.url=r.url WHERE r.report_id=? AND l.kind='merge-request' GROUP BY l.status").all(id);const linkedPending=linkCounts.filter(x=>['failed','linked-not-fetched'].includes(x.status)).reduce((n,x)=>n+x.n,0);const n=db.prepare('SELECT count(*) total,coalesce(sum(CASE WHEN system=0 THEN 1 ELSE 0 END),0) comments FROM evidence_notes WHERE report_id=?').get(id);const receipts=db.prepare('SELECT request_cursor requestCursor,next_cursor nextCursor,returned_notes returnedNotes,ids_sha256 idsSha256,fetched_at fetchedAt FROM enrichment_pages WHERE report_id=? ORDER BY fetched_at').all(id);return {...(r.extraction?JSON.parse(r.extraction):{}),pageReceipts:receipts,receiptCoverage:receipts.length===r.pages?'all-collected-pages':'partial-legacy-pages',status:r.status,collectionComplete:r.status==='completed',linkedEvidenceStatus:linkedPending?'partial':'complete',linkedPending,notesCount:n.total,discussionNotes:n.comments,pages:r.pages,nextCursor:r.cursor,updatedAt:r.updated_at,completedAt:r.completed_at,collectedAt:r.completed_at,extractedAt:r.updated_at,error:r.error||null,retryAt:r.retry_at||null,humanReviewed:false};}
export function enrichmentSummary(db,id){const x=getEnrichment(db,id);return {status:x.status,collectionComplete:x.collectionComplete,notesCount:x.notesCount,discussionNotes:x.discussionNotes,outcome:x.outcome||{category:'insufficient-evidence',label:'Discussion collection incomplete',confirmed:false,humanReviewed:false},humanReviewed:false};}
export function discussion(db,id,{page=1,limit=50}={}){page=Math.max(1,Math.floor(Number(page)||1));limit=Math.min(100,Math.max(1,Math.floor(Number(limit)||50)));const total=db.prepare('SELECT count(*) n FROM evidence_notes WHERE report_id=?').get(id).n;return {rows:db.prepare('SELECT id,discussion_id discussionId,body,url,created_at createdAt,updated_at updatedAt,system,truncated FROM evidence_notes WHERE report_id=? ORDER BY created_at,id LIMIT ? OFFSET ?').all(id,limit,(page-1)*limit).map(n=>({...n,system:!!n.system,truncated:!!n.truncated,author:n.system?'Source activity':'Public participant'})),total,page,pages:Math.ceil(total/limit),limit};}
export function saveNotePage(db,report,nodes,nextCursor){const now=new Date().toISOString();const requestCursor=db.prepare('SELECT cursor FROM enrichment_jobs WHERE report_id=?').get(report.id)?.cursor||'__FIRST__';db.exec('BEGIN');try{for(const n of nodes){if(!n||!/^gid:\/\/gitlab\/(?:Note|DiscussionNote|DiffNote)\/\d+$/.test(n.id)||typeof n.body!=='string')throw new Error('Invalid public note data; page not committed');const body=cleanPublicText(n.body,1_000_000);const url=`${report.url.split('#')[0]}#note_${n.id.split('/').at(-1)}`;db.prepare(`INSERT INTO evidence_notes(id,report_id,discussion_id,body,url,created_at,updated_at,system,truncated,fetched_at) VALUES(?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET body=excluded.body,url=excluded.url,updated_at=excluded.updated_at,system=excluded.system,truncated=excluded.truncated,fetched_at=excluded.fetched_at`).run(n.id,report.id,n.discussion?.id||'',body,url,n.createdAt||'',n.updatedAt||'',Number(!!n.system),Number(n.body.length>1_000_000),now);db.prepare('DELETE FROM note_search WHERE id=?').run(n.id);if(!n.system)db.prepare('INSERT INTO note_search(id,report_id,body) VALUES(?,?,?)').run(n.id,report.id,body);rememberSourceLinks(db,report.id,body,url);}
 rememberSourceLinks(db,report.id,report.body,report.url);
 db.prepare('INSERT OR REPLACE INTO enrichment_pages VALUES(?,?,?,?,?,?)').run(report.id,requestCursor,nextCursor,nodes.length,createHash('sha256').update(nodes.map(n=>n.id).join('\n')).digest('hex'),now);
 db.prepare('UPDATE enrichment_jobs SET cursor=?,pages=pages+1,updated_at=?,error=NULL WHERE report_id=?').run(nextCursor,now,report.id);db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}}
export function finishEnrichment(db,report,reservedUrls=[]){const notes=db.prepare('SELECT * FROM evidence_notes WHERE report_id=? ORDER BY created_at,id').all(report.id);const links=db.prepare('SELECT l.*,r.source_url sourceUrl FROM evidence_report_links r JOIN evidence_links l ON l.url=r.url WHERE r.report_id=?').all(report.id);const extraction=extractEnrichment(report,notes,links,{reservedUrls});const now=new Date().toISOString();db.prepare("UPDATE enrichment_jobs SET status='completed',cursor=NULL,completed_at=coalesce(completed_at,?),updated_at=?,error=NULL,retry_at=NULL,extraction=? WHERE report_id=?").run(now,now,JSON.stringify(extraction),report.id);return extraction;}
export function reextract(db,reservedUrls=[],{force=false}={}){for(const r of db.prepare("SELECT r.* FROM reports r JOIN enrichment_jobs j ON j.report_id=r.id WHERE j.status='completed' AND (? OR j.extraction IS NULL OR json_extract(j.extraction,'$.extractionVersion') != ?)").all(Number(force),EXTRACTION_VERSION))finishEnrichment(db,r,reservedUrls);}

export function rememberSourceLinks(db,reportId,body,sourceUrl){for(const link of publicLinks(body,sourceUrl)){db.prepare('INSERT OR IGNORE INTO evidence_links(url,kind,status) VALUES(?,?,?)').run(link.url,link.kind,link.status);db.prepare('INSERT OR IGNORE INTO evidence_report_links VALUES(?,?,?)').run(reportId,link.url,sourceUrl);}}

// Preserve original URL/anchor associations while recovering the kind of legacy links.
export function normalizeLinkKinds(db){
 for(const row of db.prepare('SELECT url,kind,status FROM evidence_links').all()){const canonical=canonicalPublicUrl(row.url);if(canonical.includes('/-/merge_requests/')){const retrySupported=row.status==='outside-collector-scope'&&/^https:\/\/gitlab\.com\/gitlab-org\/(?:gitlab-runner|gitlab)\/-\/merge_requests\/\d+$/.test(canonical);db.prepare("UPDATE evidence_links SET kind='merge-request',status=? WHERE url=?").run(retrySupported?'linked-not-fetched':row.status,row.url);}}
}
