import {canonicalPublicUrl} from './evidence-text.js';
import {EXTRACTION_VERSION} from './enrichment-extract.js';
// Local structural and provenance audit. This does not claim human validation of extracted solutions.
export function auditEnrichment(evidence){
 const db=evidence.db,stats=evidence.enrichmentStats(),scalar=sql=>db.prepare(sql).get().n;
 const integrity=db.prepare('PRAGMA integrity_check').all().map(r=>r.integrity_check);
 const consistency={reports:scalar('SELECT count(*) n FROM reports'),reportSearchRows:scalar('SELECT count(*) n FROM report_search'),duplicateReportSearchRows:scalar('SELECT count(*)-count(DISTINCT id) n FROM report_search'),missingReportSearch:scalar('SELECT count(*) n FROM reports r WHERE r.id NOT IN (SELECT id FROM report_search)'),orphanReportSearch:scalar('SELECT count(*) n FROM report_search f WHERE NOT EXISTS(SELECT 1 FROM reports r WHERE r.id=f.id)'),participantNotes:scalar('SELECT count(*) n FROM evidence_notes WHERE system=0'),noteSearchRows:scalar('SELECT count(*) n FROM note_search'),duplicateNoteSearchRows:scalar('SELECT count(*)-count(DISTINCT id) n FROM note_search'),missingNoteSearch:scalar('SELECT count(*) n FROM evidence_notes n WHERE n.system=0 AND n.id NOT IN (SELECT id FROM note_search)'),orphanNoteSearch:scalar('SELECT count(*) n FROM note_search f WHERE NOT EXISTS(SELECT 1 FROM evidence_notes n WHERE n.id=f.id AND n.system=0)'),mismatchedNoteSearch:scalar('SELECT count(*) n FROM note_search f JOIN evidence_notes n ON n.id=f.id WHERE n.body!=f.body OR n.report_id!=f.report_id'),orphanNotes:scalar('SELECT count(*) n FROM evidence_notes n WHERE NOT EXISTS(SELECT 1 FROM reports r WHERE r.id=n.report_id)'),orphanJobs:scalar('SELECT count(*) n FROM enrichment_jobs j WHERE NOT EXISTS(SELECT 1 FROM reports r WHERE r.id=j.report_id)'),truncatedNotes:stats.truncatedNotes};
 const citations={checked:0,missingSource:0,incorrectUrl:0,nonVerbatim:0,examples:[]};
 for(const row of db.prepare("SELECT r.id,r.url,r.body,j.extraction FROM reports r JOIN enrichment_jobs j ON j.report_id=r.id WHERE j.status='completed'").iterate()){
  const extraction=JSON.parse(row.extraction);const sources=new Map([[row.id+'-body',{body:row.body,url:row.url}],...db.prepare('SELECT id,body,url FROM evidence_notes WHERE report_id=?').all(row.id).map(n=>[n.id,n])]);
  for(const section of ['environment','attempts','resolutions','tasks'])for(const item of extraction[section]||[]){citations.checked++;const source=sources.get(item.id);let issue='';if(!source){citations.missingSource++;issue='missing source';}else if(source.url!==item.url){citations.incorrectUrl++;issue='incorrect URL';}else if(!source.body.includes(item.quote)){citations.nonVerbatim++;issue='quote not found verbatim in sanitized source';}if(issue&&citations.examples.length<20)citations.examples.push({reportId:row.id,sourceId:item.id,section,issue});}
 }
 const links=db.prepare('SELECT kind,status,count(*) count FROM evidence_links GROUP BY kind,status ORDER BY kind,status').all();
 const canonicalMRs=new Map();for(const r of db.prepare("SELECT url,status FROM evidence_links WHERE kind='merge-request'").all()){const key=canonicalPublicUrl(r.url);if(!canonicalMRs.has(key)||r.status==='fetched')canonicalMRs.set(key,r.status);}
 const family=db.prepare("SELECT r.family,count(*) reports,sum(CASE WHEN j.status='completed' THEN 1 ELSE 0 END) completed FROM reports r LEFT JOIN enrichment_jobs j ON j.report_id=r.id GROUP BY r.family ORDER BY r.family").all();
 const versions=db.prepare("SELECT json_extract(extraction,'$.extractionVersion') version,count(*) reports FROM enrichment_jobs WHERE status='completed' GROUP BY version").all();
 const receipts={pages:scalar('SELECT count(*) n FROM enrichment_pages'),returnedNoteRecords:scalar('SELECT coalesce(sum(returned_notes),0) n FROM enrichment_pages'),threadsWithReceipts:scalar('SELECT count(DISTINCT report_id) n FROM enrichment_pages'),completeThreadsWithSavedCursor:scalar("SELECT count(*) n FROM enrichment_jobs WHERE status='completed' AND cursor IS NOT NULL"),incompleteThreadsWithSavedCursor:scalar("SELECT count(*) n FROM enrichment_jobs WHERE status!='completed' AND cursor IS NOT NULL"),oldPageReceiptsUnavailable:true,note:'Receipts were added after collection began. They cover only recorded responses, not every earlier page; repeated note IDs across pages are deduplicated.'};
 const equation=stats.pending+stats.collecting+stats.completed+stats.unavailable+stats.failed;
 const structuralPass=integrity.length===1&&integrity[0]==='ok'&&equation===stats.total&&consistency.reports===consistency.reportSearchRows&&consistency.participantNotes===consistency.noteSearchRows&&Object.entries(consistency).filter(([k])=>/^(duplicate|missing|orphan|mismatched)/.test(k)).every(([,n])=>n===0)&&citations.missingSource===0&&citations.incorrectUrl===0&&citations.nonVerbatim===0&&receipts.completeThreadsWithSavedCursor===0;
 return {generatedAt:new Date().toISOString(),pass:structuralPass,collectionFinished:stats.pending===0&&stats.collecting===0&&stats.failed===0,totalEquation:{total:stats.total,pending:stats.pending,collecting:stats.collecting,completed:stats.completed,unavailable:stats.unavailable,failed:stats.failed,sum:equation,reconciles:equation===stats.total},stats,integrity,consistency,citations,outcomes:stats.outcomes,families:family,extractionVersions:versions,expectedExtractionVersion:EXTRACTION_VERSION,versionsCurrent:versions.every(v=>v.version===EXTRACTION_VERSION),linkedEvidenceStates:links,linkedCollectionFinished:stats.linkedPending===0&&stats.linkedFailed===0,canonicalMergeRequests:{total:canonicalMRs.size,statuses:Object.fromEntries([...new Set(canonicalMRs.values())].sort().map(status=>[status,[...canonicalMRs.values()].filter(x=>x===status).length])),fetched:[...canonicalMRs.values()].filter(x=>x==='fetched').length,note:'Canonical count folds query strings, fragments and MR subpaths; raw link rows can contain several references to one change.'},receipts,runs:db.prepare('SELECT * FROM enrichment_runs ORDER BY id').all(),limitations:['Machine extraction is not human review or independent resolution confirmation.','The crawl is a per-thread public-source snapshot, not a single atomic snapshot of the tracker.','A source-side userNotesCount may differ from publicly accessible note rows; only returned cursor pages are collected.','Refresh of already completed source discussions is not automatic.','Secret/contact masking is best effort. Source text remains untrusted evidence.']};
}
