import {initEnrichment,enrichmentStats,getEnrichment,enrichmentSummary,discussion} from './enrichment-store.js';
import {publicLinks} from './enrichment-extract.js';
import {cleanPublicText,reportKind,retrievalTerms,canonicalPublicUrl} from './evidence-text.js';
import {DatabaseSync} from 'node:sqlite';
import {mkdirSync} from 'node:fs';import {dirname} from 'node:path';
export class EvidenceStore{
 reserveSources(urls){this.reserved=new Set(urls.map(canonicalPublicUrl));}
 isReserved(url){return this.reserved?.has(canonicalPublicUrl(url))||false;}
 constructor(path){if(path!==':memory:')mkdirSync(dirname(path),{recursive:true});this.db=new DatabaseSync(path);this.db.exec(`PRAGMA busy_timeout=10000;PRAGMA journal_mode=WAL;CREATE TABLE IF NOT EXISTS reports(id TEXT PRIMARY KEY,url TEXT UNIQUE,title TEXT,body TEXT,author TEXT,created_at TEXT,updated_at TEXT,state TEXT,family TEXT,labels TEXT,source TEXT,review_status TEXT DEFAULT 'indexed');CREATE VIRTUAL TABLE IF NOT EXISTS report_search USING fts5(id UNINDEXED,title,body,family);CREATE TABLE IF NOT EXISTS ingestion_runs(id INTEGER PRIMARY KEY,started_at TEXT,finished_at TEXT,status TEXT,source TEXT,first_page INTEGER,last_page INTEGER,fetched INTEGER,added INTEGER,error TEXT);CREATE TABLE IF NOT EXISTS checkpoints(source TEXT PRIMARY KEY,page INTEGER,updated_at TEXT,seen INTEGER);`);initEnrichment(this.db);}
 upsert(r){r={...r,title:cleanPublicText(r.title),body:cleanPublicText(r.body),author:'Public user'};const existing=this.db.prepare('SELECT id FROM reports WHERE id=?').get(r.id);this.db.exec('BEGIN');try{this.db.prepare('INSERT INTO reports(id,url,title,body,author,created_at,updated_at,state,family,labels,source) VALUES(?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET title=excluded.title,body=excluded.body,updated_at=excluded.updated_at,state=excluded.state,author=excluded.author,family=excluded.family,labels=excluded.labels').run(r.id,r.url,r.title,r.body,r.author,r.createdAt,r.updatedAt,r.state,r.family,JSON.stringify(r.labels),r.source);this.db.prepare('DELETE FROM report_search WHERE id=?').run(r.id);this.db.prepare('INSERT INTO report_search(id,title,body,family) VALUES(?,?,?,?)').run(r.id,r.title,r.body,r.family);this.db.exec('COMMIT');return !existing;}catch(e){this.db.exec('ROLLBACK');throw e;}}
 enrichmentStats(){return enrichmentStats(this.db);}
 getEnrichment(id){const x=getEnrichment(this.db,id);for(const key of ['environment','attempts','resolutions','tasks','linkedEvidence'])if(x[key])x[key]=x[key].filter(e=>!this.isReserved(e.url)&&!this.containsReserved(e.quote||e.description||''));return x;}
 discussion(id,options){return discussion(this.db,id,options);}
 containsReserved(text){return publicLinks(text,'').some(x=>this.isReserved(x.url));}
 stats(){return {enrichment:this.enrichmentStats(),indexed:this.db.prepare('SELECT count(*) n FROM reports').get().n,reviewed:this.db.prepare("SELECT count(*) n FROM reports WHERE review_status='reviewed'").get().n,confirmed:0,kinds:this.db.prepare(`SELECT CASE WHEN labels LIKE '%type::bug%' OR labels LIKE '%bug::%' OR labels LIKE '%"bug"%' THEN 'Bug report' WHEN labels LIKE '%type::feature%' OR labels LIKE '%feature proposal%' OR labels LIKE '%enhancement%' THEN 'Feature request' WHEN labels LIKE '%support request%' OR labels LIKE '%support_backlog%' THEN 'Support request' ELSE 'Unclassified report' END kind,count(*) count FROM reports GROUP BY kind ORDER BY count DESC`).all(),latestRun:this.db.prepare('SELECT * FROM ingestion_runs ORDER BY id DESC LIMIT 1').get()||null,families:this.db.prepare('SELECT family,count(*) count FROM reports GROUP BY family ORDER BY count DESC').all(),sources:this.db.prepare('SELECT source,count(*) count FROM reports GROUP BY source').all(),checkpoints:this.db.prepare('SELECT * FROM checkpoints').all()};}
 search({q='',family='',kind='',outcome='',state='',page=1}={}){page=Math.min(1000,Math.max(1,Math.floor(Number(page)||1)));const terms=String(q).match(/[\p{L}\p{N}_-]+/gu)?.slice(0,12)||[];const match=terms.map(t=>'"'+t.replaceAll('"','')+'"').join(' AND ');const issueNumber=/^(?:gitlab-runner-|#)?(\d+)$/.exec(String(q).trim())?.[1];const sourceState=['opened','closed'].includes(state)?state:'';const filter=[...(match?[issueNumber?'(r.id IN (?,?) OR r.id IN (SELECT id FROM report_search WHERE report_search MATCH ? UNION SELECT report_id FROM note_search WHERE note_search MATCH ?))':'r.id IN (SELECT id FROM report_search WHERE report_search MATCH ? UNION SELECT report_id FROM note_search WHERE note_search MATCH ?)']:[]),...(sourceState?['r.state=?']:[]),...(family?['r.family=?']:[]),...(outcome?["r.id IN (SELECT report_id FROM enrichment_jobs WHERE status='completed' AND json_extract(extraction,'$.outcome.category')=?)"]:[]),...(kind?[`CASE WHEN r.labels LIKE '%type::bug%' OR r.labels LIKE '%bug::%' OR r.labels LIKE '%"bug"%' THEN 'Bug report' WHEN r.labels LIKE '%type::feature%' OR r.labels LIKE '%feature proposal%' OR r.labels LIKE '%enhancement%' THEN 'Feature request' WHEN r.labels LIKE '%support request%' OR r.labels LIKE '%support_backlog%' THEN 'Support request' ELSE 'Unclassified report' END = ?`]:[])];const values=[...(match?[...(issueNumber?[issueNumber,'gitlab-runner-'+issueNumber]:[]),match,match]:[]),...(sourceState?[sourceState]:[]),...(family?[family]:[]),...(outcome?[outcome]:[]),...(kind?[kind]:[])];const where=filter.length?' WHERE '+filter.join(' AND '):'';const total=this.db.prepare('SELECT count(*) n FROM reports r'+where).get(...values).n;const rows=this.db.prepare('SELECT id,url,title,substr(body,1,420) excerpt,author,created_at,updated_at,state,family,review_status,labels FROM reports r'+where+' ORDER BY updated_at DESC LIMIT 24 OFFSET ?').all(...values,(page-1)*24);return {rows:rows.map(r=>({...r,enrichment:enrichmentSummary(this.db,r.id),author:'Public user',reserved:this.isReserved(r.url),kind:reportKind(JSON.parse(r.labels)),excerpt:cleanPublicText(r.excerpt),title:cleanPublicText(r.title)})),total,page,pages:Math.ceil(total/24)};}
 get(id){const r=this.db.prepare('SELECT * FROM reports WHERE id=?').get(id);return r?{...r,reserved:this.isReserved(r.url),enrichment:enrichmentSummary(this.db,r.id),title:cleanPublicText(r.title),body:cleanPublicText(r.body),author:'Public user',kind:reportKind(JSON.parse(r.labels))}:null;}
 suggest(query,context={},options={}){
  const excludedIds=new Set(options.excludeIds||[]),excludedUrls=new Set((options.excludeUrls||[]).map(canonicalPublicUrl));
  // Resolve the source independently of the bounded retrieval window so exact
  // copies are excluded even when the original is not a top search candidate.
  if(excludedUrls.size)for(const r of this.db.prepare('SELECT id,url FROM reports').all())if(excludedUrls.has(canonicalPublicUrl(r.url)))excludedIds.add(r.id);
  const terms=retrievalTerms(query);if(!terms.length)return [];
  const stems=[...new Set(terms.map(t=>({artifacts:'artifact',uploading:'upload',uploads:'upload',downloads:'download',downloading:'download',restarts:'restart',restarting:'restart',permissions:'permission',retries:'retry'}[t]||t)))];
  const priorityStems=[...new Set((options.priorityTerms||[]).map(t=>({artifacts:'artifact',uploading:'upload',uploads:'upload',downloads:'download',downloading:'download',restarts:'restart',restarting:'restart',permissions:'permission',retries:'retry'}[t]||t)))];
  const match=stems.map(t=>'"'+t+'"*').join(' OR ');
  const rows=this.db.prepare(`SELECT r.id,r.url,r.title,r.body,snippet(report_search,2,'','', ' … ',40) excerpt,r.family,r.state,r.labels,j.extraction,bm25(report_search,0,8,1,2) rank FROM report_search JOIN reports r ON r.id=report_search.id LEFT JOIN enrichment_jobs j ON j.report_id=r.id WHERE report_search MATCH ? ORDER BY rank LIMIT 100`).all(match);
  const noteRows=this.db.prepare(`SELECT r.id,n.url,r.url reportUrl,r.title,r.body,n.body noteBody,snippet(note_search,2,'','', ' … ',40) excerpt,r.family,r.state,r.labels,j.extraction,bm25(note_search) rank FROM note_search JOIN evidence_notes n ON n.id=note_search.id JOIN reports r ON r.id=note_search.report_id LEFT JOIN enrichment_jobs j ON j.report_id=r.id WHERE note_search MATCH ? ORDER BY rank LIMIT 80`).all(match);
  const executor=String(context.executor||''),runnerVersion=String(context.runnerVersion||'').trim();
  const executorPattern=executor==='Kubernetes'?/\bkubernetes|\bk8s\b|\bpods?\b/i:executor==='Docker'?/docker executor|docker containers?|docker image/i:executor==='Shell'?/shell executor|\bbash\b|\bpowershell\b/i:null;
  const scored=[...rows,...noteRows].filter(r=>!excludedIds.has(r.id)&&!excludedUrls.has(canonicalPublicUrl(r.reportUrl||r.url))&&!this.isReserved(r.reportUrl||r.url)&&!this.isReserved(r.url)&&!this.containsReserved(r.body)&&!this.containsReserved(r.noteBody||'')&&(options.includeFeatures||reportKind(JSON.parse(r.labels))!=='Feature request')).map(r=>{
   const sourceText=r.title+' '+r.body+' '+(r.noteBody||''),lower=sourceText.toLowerCase(),x=r.extraction?JSON.parse(r.extraction):null;
   const executorMention=executorPattern?.test(sourceText)||false;
   const genericWindows=executor==='Kubernetes'&&!executorMention&&/\bwindows|powershell|windows service/i.test(sourceText);
   const versions=x?.versions?.map(v=>v.value)||[];const versionMention=runnerVersion&&versions.includes(runnerVersion);
   const outcome=x?.outcome?.category||'insufficient-evidence';
   const score=stems.filter(t=>lower.includes(t)).length*3+stems.filter(t=>r.title.toLowerCase().includes(t)).length*5+priorityStems.filter(t=>r.title.toLowerCase().includes(t)).length*40+Math.min(1,Math.abs(r.rank))+(executorMention?22:0)-(genericWindows?18:0)+(versionMention?7:0)-(runnerVersion&&versions.length&&!versionMention?3:0)+({'source-reported-resolution':5,'proposed-resolution':2,conflicting:-3,obsolete:-12,duplicate:-8,'invalid-report':-20}[outcome]||0)-(/^(follow[- ]up|make |enable |add |support for |improve |refactor |remove |update |bump |implement |document )/i.test(r.title)?12:0);
   return {...r,score,kind:reportKind(JSON.parse(r.labels)),duplicate:outcome==='duplicate',applicability:{executor:executorPattern?(executorMention?`Source mentions ${executor}; verify exact configuration`:`${executor} applicability not established`):'Executor not specified',version:versionMention?'Requested version is mentioned; affected/fixed range not established':versions.length?(runnerVersion?'Requested version not among extracted mentions; verify original source':'Source versions mentioned; applicability not established'):'Version applicability unknown'}};
  }).sort((a,b)=>b.score-a.score);
  const seenIds=new Set(),seenUrls=new Set(),seenContent=new Set();
  const fingerprint=r=>`${r.title}\n${r.body}`.toLowerCase().replace(/\s+/g,' ').trim();
  for(const id of excludedIds){const r=this.db.prepare('SELECT title,body FROM reports WHERE id=?').get(id);if(r)seenContent.add(fingerprint(r));}
  for(const r of [...rows,...noteRows])if(excludedUrls.has(canonicalPublicUrl(r.reportUrl||r.url)))seenContent.add(fingerprint(r));
  return scored.filter(r=>{const url=canonicalPublicUrl(r.reportUrl||r.url),content=fingerprint(r);if(seenIds.has(r.id)||seenUrls.has(url)||(options.deduplicate&&(r.duplicate||seenContent.has(content))))return false;seenIds.add(r.id);seenUrls.add(url);seenContent.add(content);return true;}).slice(0,4).map(({body:_body,noteBody:_noteBody,labels:_labels,rank:_rank,score:_score,extraction:_extraction,duplicate:_duplicate,...r})=>({...r,title:cleanPublicText(r.title),excerpt:cleanPublicText(r.excerpt),enrichment:enrichmentSummary(this.db,r.id),status:enrichmentSummary(this.db,r.id).outcome.label}));
 }

 selectedReference(id,context={}){const r=this.get(id);if(!r||this.isReserved(r.url)||this.containsReserved(r.body))return null;const x=this.getEnrichment(id);const matchingIds=new Set((x.versions||[]).filter(v=>context.runnerVersion&&v.value===context.runnerVersion).map(v=>v.sourceId));const candidates=[...(x.resolutions||[])].sort((a,b)=>Number(matchingIds.has(b.id))-Number(matchingIds.has(a.id))||Number(b.kind==='source-reported-resolution')-Number(a.kind==='source-reported-resolution')||String(b.createdAt||'').localeCompare(String(a.createdAt||'')));const quote=candidates[0];const summary=quote?`${quote.support}\n${quote.quote}`:r.body;return {id:'SRC-'+r.id,sourceId:r.id,title:r.title,url:quote?.url||r.url,reportUrl:r.url,summary:summary.slice(0,700),quote:quote?.quote,sourceDate:quote?.createdAt||r.created_at||null,contradictions:(x.attempts||[]).filter(a=>a.result==='reported-unsuccessful').map(a=>({quote:a.quote,url:a.url,sourceDate:a.createdAt||null})),kind:quote?'machine-extracted-public-evidence':'unreviewed-public-report',status:quote?x.outcome.label+'; machine extraction, not human reviewed':'Selected source text; claims and outcome unverified',question:'Does this exact version, environment and observed result match the current case?',versions:x.versions?.map(v=>v.value).join(', ').slice(0,100)||'Check original report',executor:'Any',stage:r.family};}

 close(){this.db.close();}
}
