import {additionalSources,additionalOutcomes,additionalCases,additionalCompanies} from './additional-cases.js';
export const sources = [
 ...additionalSources,
 {id:'GL-37242',title:'Kubernetes runner liveness check improvement',url:'https://gitlab.com/gitlab-org/gitlab-runner/-/issues/37242',type:'Public issue',verification:'Outcome comments verified in rendered public discussion, 27 Sep 2026. Support-staff reports; private tickets not accessed.',summary:'Separate customer episodes document a successful probe-timeout workaround. No universal affected-version range is established.'},
 {id:'GL-26869',title:'Artifact upload failure after a successful job',url:'https://gitlab.com/gitlab-org/gitlab-runner/-/issues/26869',type:'Public issue',verification:'Public discussion; use the August 2023 Kubernetes episode, not the original shell-runner report.',summary:'Different failure stage and environment from runner restarts. Cause is not established for the later helper-image workaround.'},
 {id:'INC-15997',title:'GitLab.com service interruption · 7 Jul 2023',url:'https://gitlab.com/gitlab-com/gl-infra/production/-/issues/15997',type:'Provider incident',verification:'Provider incident description documents impact and restored services.',summary:'Historical Web/API and registry impact on GitLab.com. This is not evidence of a self-managed configuration failure.'},
 {id:'DOC-HELM',title:'Runner Helm chart: configuration and versions',url:'https://docs.gitlab.com/runner/install/kubernetes/',type:'Official documentation',verification:'Current reference; not an archived 2023 snapshot.',summary:'Server, Runner and chart versions are distinct. Confirm each before using version-specific guidance.'},
 {id:'DOC-K8S',title:'Troubleshooting the Kubernetes executor',url:'https://docs.gitlab.com/runner/executors/kubernetes/troubleshooting/',type:'Official documentation',verification:'Current reference; narrow contextual guidance only.',summary:'Distinguish scheduling, API connectivity, runner health and job execution stages.'},
];
export const hiddenOutcomes = {
 ...additionalOutcomes,
 'CS-1044':{sourceId:'GL-26869',fix:'The reporter changed helper_image_flavor to ubuntu and reported successful artifact upload.',cause:'',verification:'The reporter reported success on 8 August 2023 in public comment note_1503687244.',limitations:'Reporter explicitly did not know why it worked. Do not treat this as a liveness fix or assume every HTTP 500 has this cause.'},
 'CS-1042': {fix:'Increase probeTimeoutSeconds to 70 in the Runner Helm values, after verifying that the liveness probe is timing out.',cause:'',verification:'The public support-staff report dated 21 December 2023 states that the customer’s random restarts stopped.',limitations:'Historical workaround. Exact affected chart and Runner versions are not public. Inspect the actual liveness script and probe events; do not apply universally.',sourceId:'GL-37242'},
 'CS-1043': {fix:'The later support report also records probeTimeoutSeconds = 70 stopping runner-pod restarts.',cause:'',verification:'Public support-staff confirmation dated 25 June 2024.',limitations:'Customer identity, complete logs and exact versions are not public.',sourceId:'GL-37242'},
};
const base = {status:'Open',priority:'High',hosting:'Self-managed',executor:'Kubernetes',serverVersion:'',runnerVersion:'',chartVersion:'',host:'',service:'CI runners',occurredAt:'',recentChanges:'Not provided',attempts:[],articleIds:[],incidentIds:[],timeline:[],resolution:null,proposal:null,drafts:null,analysis:null};
export function initialState() {
 const cases = [
  {...base,id:'CS-1042',companyId:'org-a',contact:'Contact not public',title:'Runner pods restart before work completes',description:'Our CI runner keeps restarting. We need help understanding what to check next.',symptom:'runner-restarts',stage:'Runner health',sourceId:'GL-37242',sourceDate:'2023-12-21',reconstructed:true},
  {...base,id:'CS-1043',companyId:'org-b',contact:'Contact not public',title:'Intermittent runner restarts are back',description:'Another team is seeing unexpected runner-pod restarts. Is there relevant experience from an earlier case?',symptom:'runner-restarts',stage:'Runner health',sourceId:'GL-37242',sourceDate:'2024-06-25',reconstructed:true},
  {...base,id:'CS-1044',companyId:'org-c',contact:'Public reporter',title:'Tests pass, but the artifact upload fails',description:'The job finishes its tests, then artifact upload returns HTTP 500. The failure is in the upload stage.',symptom:'artifact-upload',stage:'Artifact upload',serverVersion:'16.2.3',sourceId:'GL-26869',sourceDate:'2023-08-08',reconstructed:true},
  {...base,id:'CS-1045',companyId:'org-d',contact:'Reconstructed contact',title:'GitLab.com API returns 503',description:'Our workflow cannot reach GitLab.com. This is a reconstructed report aligned with the historical provider incident window.',symptom:'service-unavailable',stage:'API access',hosting:'GitLab.com',executor:'Unknown',host:'gitlab.com',service:'API',occurredAt:'2023-07-07T17:00:00Z',sourceId:'INC-15997',sourceDate:'2023-07-07',reconstructed:true},
 ];
 return {cases:[...cases,...additionalCases(base)],companies:[...additionalCompanies,{id:'org-a',name:'Anonymous public user A',note:'Anonymous source user · earlier public episode'},{id:'org-b',name:'Anonymous public user B',note:'Anonymous source user · later public episode'},{id:'org-c',name:'Anonymous public user C',note:'Anonymous source user · artifact-upload example'},{id:'org-d',name:'Anonymous public user D',note:'Anonymous source user · GitLab.com incident replay'}],articles:[],outbox:[],memories:[],events:[],incidents:[{id:'INC-15997',title:'GitLab.com Web/API outage',host:'gitlab.com',services:['API','Web'],start:'2023-07-07T16:25:00Z',end:'2023-07-07T18:42:00Z',status:'Resolved · historical',sourceId:'INC-15997',summary:'Provider-confirmed service restoration. Scope is GitLab.com Web/API within this window; registry recovery had a different time.'}]};
}
