// Curated reference guidance is separate from customer-confirmed knowledge.
// No reference is retained in Cloud or presented as a successful customer outcome.
const k8s='https://docs.gitlab.com/runner/executors/kubernetes/troubleshooting/';
const artifacts='https://docs.gitlab.com/ci/jobs/job_artifacts_troubleshooting/';
const tls='https://docs.gitlab.com/runner/configuration/tls-self-signed/';
export const references=[
 {id:'REF-01',title:'Build environment never starts',keywords:'pod pending scheduling timed out waiting start timeout resources capacity',executor:'Kubernetes',stage:'Environment setup',summary:'Inspect scheduling events and readiness before changing the wait limit.',question:'What do the pod events show while the job waits?',url:k8s+'#job-failed-system-failure-timed-out-waiting-for-pod-to-start'},
 {id:'REF-02',title:'Cluster requests exceed their deadline',keywords:'context deadline exceeded api latency etcd prepare environment',executor:'Kubernetes',stage:'Environment setup',summary:'Check cluster API latency and errors; a timeout alone does not identify the cause.',question:'Which API operation timed out, and what do its metrics show?',url:k8s+'#context-deadline-exceeded'},
 {id:'REF-03',title:'A cluster policy check times out',keywords:'admission webhook request timeout prepare credentials',executor:'Kubernetes',stage:'Environment setup',summary:'Inspect admission webhook timing and scope with the cluster owner.',question:'Which webhook intercepted the failing request?',url:k8s+'#request-did-not-complete-within-requested-timeout'},
 {id:'REF-04',title:'Repository hostname cannot be resolved',keywords:'dns hostname resolve alpine musl helper clone repository',executor:'Kubernetes',stage:'Repository checkout',summary:'Compare helper image and DNS behavior; Alpine resolver behavior may be relevant.',question:'Which helper image and resolver configuration are in use?',url:k8s+'#error-could-not-resolve-host-examplecom'},
 {id:'REF-05',title:'Cache files cannot be read or written',keywords:'cache permission denied ownership chmod chown user',executor:'Kubernetes',stage:'Cache',summary:'Compare archived file ownership with the helper user before changing permissions.',question:'Who owns the cache files, and which user extracts them?',url:k8s+'#cache-related-permission-denied-errors'},
 {id:'REF-06',title:'Job output files are missing',keywords:'artifacts no files upload missing path generated output',executor:'Any',stage:'Artifact upload',summary:'Check whether the expected files were generated and whether the artifact paths point to them. This differs from a server-side upload failure.',question:'What files exist at upload time, and what paths does the job specify?',url:artifacts+'#error-message-no-files-to-upload'},
 {id:'REF-07',title:'A later job cannot retrieve earlier output',keywords:'artifacts download retrieve dependencies needs pipeline previous stages',executor:'Any',stage:'Artifact download',summary:'Review the dependency selection and whether the requested artifacts are still available. Capture the producing job and requesting job separately.',question:'Which producer job and dependency declaration should supply these files?',url:artifacts+'#job-does-not-retrieve-certain-artifacts'},
 {id:'REF-08',title:'Connection fails certificate verification',keywords:'x509 certificate unknown authority self signed tls ca trust registration registry',executor:'Any',stage:'Connection security',summary:'Identify the failing connection and its trust store. Runner-to-server, helper-container and registry connections can require different certificate configuration. Preserve certificate verification.',question:'Which endpoint fails, and which component verifies its certificate?',url:tls},
 {id:'REF-09',title:'Shell profile interrupts environment preparation',keywords:'bash bashrc bash_logout clear_console profile logout',executor:'Shell',stage:'Shell initialization',summary:'Login-shell profiles can run during preparation. Inspect the failing profile command before changing the job script.',question:'Does the service user profile contain interactive commands or console cleanup?',url:'https://docs.gitlab.com/runner/shells/#shell-profile-loading'},
 {id:'REF-10',title:'Windows shell executable and job image disagree',keywords:'powershell pwsh windows createprocess executable',executor:'Any',stage:'Image compatibility',summary:'Check the configured shell and available executable. Defaults differ between shell, Docker-Windows and Kubernetes execution.',question:'Which shell executable exists inside the job environment?',url:'https://docs.gitlab.com/runner/shells/#powershell'},
 {id:'REF-11',title:'Cross-project job token lacks access',keywords:'ci_job_token allowlist registry denied unauthorized authentication',executor:'Any',stage:'Registry authentication',summary:'Check the source project job-token allowlist and the triggering user permissions. Keep access scoped to intended projects.',question:'Is the consuming project explicitly allowed to use the source project resource?',url:'https://docs.gitlab.com/ci/jobs/ci_job_token/'},
 {id:'REF-12',title:'Distributed cache credentials or configuration are missing',keywords:'cache gcs s3 credentialsfile bucket credential',executor:'Any',stage:'Cache',summary:'Inspect the effective cache backend configuration and credential source; local and distributed caches have different scopes.',question:'Which cache backend and credential source are in the generated Runner configuration?',url:'https://docs.gitlab.com/runner/configuration/advanced-configuration/'},
 {id:'REF-13',title:'Docker storage and service-container mounts need inspection',keywords:'disk space inode storage volume volumes mount mounts overlay2 service containers files configuration directory compose',executor:'Docker',stage:'Storage exhaustion',summary:'Inspect which directories are mounted into the job and its service containers. Compare service mounts with the local Compose setup. For storage exhaustion, check usage before considering cleanup; preserve active-job volumes.',question:'Which Docker host and mounts are used by the job and each service container?',url:'https://docs.gitlab.com/runner/executors/docker/'},
 {id:'REF-14',title:'Runner token type does not match registration flow',keywords:'register registration token verification verify',executor:'Any',stage:'Runner registration',summary:'Distinguish current authentication tokens from legacy registration tokens; use the instructions for the deployed version and installation method.',question:'What token type, Runner version and registration method are being used?',url:'https://docs.gitlab.com/runner/register/'},
 {id:'REF-15',title:'SSH credentials differ between interactive and CI sessions',keywords:'ssh scp publickey known_hosts ssh-agent',executor:'Any',stage:'SSH authentication',summary:'Load the intended private key securely in the CI environment and establish trusted host keys. Do not disable host verification.',question:'Which service user runs the job, and is its intended SSH identity available?',url:'https://docs.gitlab.com/ci/jobs/ssh_keys/'},
 {id:'REF-16',title:'Runner metrics endpoint is not being scraped',keywords:'metrics prometheus scrape observability monitor',executor:'Any',stage:'Observability',summary:'Check the Runner metrics listener and scrape reachability. Runner metrics and Kubernetes pod-label metrics are different sources.',question:'Which metrics endpoint and metric labels does the monitoring query expect?',url:'https://docs.gitlab.com/runner/monitoring/'},
 {id:'REF-17',title:'Kubernetes service account permissions do not cover the operation',keywords:'rbac forbidden serviceaccount authorization secrets pods attach',executor:'Kubernetes',stage:'Cluster authorization',summary:'Compare the failing Kubernetes verb/resource with the executor permissions and feature flags. Avoid blanket cluster-wide permissions.',question:'Which service account, verb and resource appear in the forbidden response?',url:'https://docs.gitlab.com/runner/executors/kubernetes/'},
 {id:'REF-18',title:'Artifact upload rejected with HTTP413',keywords:'413 artifacts upload entity large archive nginx proxy body limit size',executor:'Any',hosting:'Self-managed',stage:'Artifact upload',summary:'For self-managed artifact uploads returning413, GitLab documents two limits to inspect: the maximum artifact size and, when NGINX proxies the upload, its request-body limit. The source does not establish which component rejected this case or its effective configuration. Establish those facts before choosing a change.',question:'Which component produced413, and what artifact and proxy limits were effective for that request?',url:'https://docs.gitlab.com/administration/cicd/job_artifacts_troubleshooting/#413-request-entity-too-large-error',reviewedAt:'2026-09-28'},
 {id:'REF-19',title:'Applying an Omnibus NGINX body-size configuration',keywords:'413 nginx omnibus gitlab.rb client_max_body_size body size reconfigure configuration apply',executor:'Any',hosting:'Self-managed',stage:'Server configuration',summary:'For a self-managed Linux package installation reporting Request Entity Too Large in NGINX logs, the documentation describes editing client_max_body_size in gitlab.rb, reconfiguring GitLab and gracefully reloading NGINX. Kubernetes installations use proxyBodySize instead. A file edit is not evidence that the running setting changed; an unrecorded apply step remains unknown. Confirm installation method, deployed version and current effective settings before proposing an action.',question:'Was the edited setting applied to the component that rejected the request, and what evidence shows its effective value?',url:'https://docs.gitlab.com/omnibus/settings/nginx_troubleshooting/#request-entity-too-large',reviewedAt:'2026-09-28'},
].map(r=>({...r,kind:'Official documentation',reviewedAt:r.reviewedAt||'2026-09-27',versions:'Confirm the deployed versions; this is current documentation, not a historical version guarantee.',outcome:'Reference guidance only; no customer outcome verified.'}));
const stop=new Set('the and that this with from for are was has have our can not unknown'.split(' '));
export function tokens(value){return [...new Set(String(value).toLowerCase().replace(/[^a-z0-9]+/g,' ').split(' ').filter(t=>t.length>2&&!stop.has(t)).map(t=>t.replace(/s$/,'')))];}
export function rankDocuments(query,documents,textOf){const terms=tokens(query);return documents.map(item=>{const words=tokens(textOf(item));const matched=terms.filter(t=>words.includes(t));const score=matched.reduce((sum,t)=>sum+Math.log(1+documents.length/(1+documents.filter(d=>tokens(textOf(d)).includes(t)).length)),0);return {...item,retrieval:{score,matched}};}).filter(d=>d.retrieval.score>0).sort((a,b)=>b.retrieval.score-a.retrieval.score);}
export function referenceSearch(query,executor='Unknown'){const generic=new Set('runner job help issue relevant earlier another team seeing unexpected report experience current problem work need fail failed failure gitlab pipeline pod'.split(' '));const technical=tokens(query).filter(t=>!generic.has(t)).join(' ');return rankDocuments(technical,references,r=>r.keywords).map(r=>({...r,applicability:r.executor==='Any'||executor==='Unknown'||r.executor===executor?'Review environment before applying':'Different executor; reference only'})).slice(0,4);}

// Reference titles and keyword overlap are not sufficient applicability evidence.
export function referenceExclusion(c,r){
 if(r.executor&&r.executor!=='Any'&&c.executor&&c.executor!=='Unknown'&&r.executor!==c.executor)return 'Documentation describes a different executor';
 if(r.hosting&&c.hosting&&c.hosting!=='Unknown'&&r.hosting!==c.hosting)return 'Documentation requires a different hosting context';
 const report=`${c.title||''} ${c.description||''}`;
 if(r.id==='REF-06'&&/(?:(?:^|[^0-9])413(?:[^0-9]|$)|entity too large|too large archive)/i.test(report)&&!/(?:no files to upload|no matching files|found 0 matching)/i.test(report))return 'Missing-file guidance does not explain the observed HTTP413 upload rejection';
 return null;
}
