import {useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {api} from './api';

type CheckpointBudget={authorized:boolean;reservedUSD:number;remainingUSD:number;ingestionRemainingUSD:number;note:string};
type AutomaticForecast={missingDocuments:number;reusedDocuments:number;totalReservationUSD:number;note:string};
const dollars=(amount:number|undefined)=>typeof amount==='number'&&Number.isFinite(amount)?`$${amount.toFixed(2)}`:'Unavailable';
type Status={budget?:CheckpointBudget;workspaceId:string;ownerId:string;configured:boolean;localHash:string;status:{status:string;snapshotHash?:string;activeOwnerId?:string;note?:string;verifiedAt?:string;automaticForecast?:AutomaticForecast};pending:{snapshotHash:string;status:string;forecast:{uniqueDocuments:number;fullWriteReservationUSD:number}}[]};
type Preview={previewId:string;expectedLocalHash:string;snapshotHash:string;workspaceId:string;activeOwnerId:string;canEdit:boolean;counts:{cases:number;companies:number;articles:number;officialDocuments:number}};
export function CloudWorkspacePanel(){
 const client=useQueryClient(),query=useQuery<Status>({queryKey:['cloud-workspace'],queryFn:()=>api('/cloud-workspace'),retry:false,refetchInterval:q=>!q.state.error&&q.state.data?.configured&&['pending','processing','dispatched','unverified'].includes(q.state.data.status.status)?3000:false});
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[workspaceId,setWorkspaceId]=useState(''),[ownerId,setOwnerId]=useState(''),[nextOwnerId,setNextOwnerId]=useState(''),[preview,setPreview]=useState<Preview|null>(null),[replace,setReplace]=useState(false);
 const run=async(action:()=>Promise<void>)=>{if(busy)return;setBusy(true);setError('');setMessage('');try{await action();await Promise.all([client.invalidateQueries({queryKey:['cloud-workspace']}),client.invalidateQueries({queryKey:['workspace']})]);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const status=query.data,otherOwner=!!(status?.status.activeOwnerId&&status.status.activeOwnerId!==status.ownerId),forecast=status?.status.automaticForecast;
 const insufficient=!!(forecast&&status?.budget&&(!status.budget.authorized||forecast.totalReservationUSD>Math.min(status.budget.remainingUSD,status.budget.ingestionRemainingUSD)));
 return <section className="cloud-retention" aria-label="Cloud workspace recovery"><h3>Cloud workspace</h3><p>One active editor. Committed saves automatically queue a bounded Cloud checkpoint when the complete save fits the authorized allowance. Local changes remain pending until the complete checkpoint is read back and verified. Opening the app does not start a checkpoint or a paid retry.</p><p>Compression reduces storage size; it is not encryption.</p>
  {query.isPending?<p role="status">Loading checkpoint status…</p>:query.isError?<div role="alert">Checkpoint status could not be loaded. <button className="secondary" onClick={()=>void query.refetch()}>Retry checkpoint status</button></div>:status&&<>
   <dl><dt>Workspace ID</dt><dd>{status.workspaceId}</dd><dt>This editor</dt><dd>{status.ownerId}</dd><dt>Cloud status</dt><dd>{status.status.status}</dd><dt>Active editor</dt><dd>{status.status.activeOwnerId||'No verified handoff yet'}</dd></dl><p>{status.status.note}</p>
   <section aria-label="Cloud checkpoint allowance"><h4>Authorized allowance</h4><dl><dt>Paid checkpoint authority</dt><dd>{status.budget?status.budget.authorized?'Available for this workspace and connection':'Not authorized':'Status unavailable'}</dd><dt>Recorded reservations</dt><dd>{dollars(status.budget?.authorized?status.budget.reservedUSD:undefined)}</dd><dt>Remaining authorized credit</dt><dd>{dollars(status.budget?.authorized?status.budget.remainingUSD:undefined)}</dd><dt>Remaining ingestion allowance</dt><dd>{dollars(status.budget?.authorized?status.budget.ingestionRemainingUSD:undefined)}</dd></dl>{status.budget?.note&&<p>{status.budget.note}</p>}<p>Reservations are estimates, not billed charges or the Hindsight account balance. A complete save must fit both remaining allowances before new paid writes start.</p></section>
   {forecast&&<section aria-label="Automatic save estimate"><h4>Whole-save estimate</h4><p>Estimated reservation: <strong>{dollars(forecast.totalReservationUSD)}</strong> · {forecast.missingDocuments} new documents · {forecast.reusedDocuments} reusable documents.</p><p>{forecast.note}</p>{insufficient&&<p role="status">This save exceeds its current authorization. It remains pending; no new paid writes are authorized by this display.</p>}</section>}
   {otherOwner&&<p role="status">Another editor holds the active handoff. Publishing from this cache is disabled; recovery remains available.</p>}
   <p>While pending, this panel refreshes local status only. It does not start Cloud reads, writes or source verification.</p>
   {!status.configured&&<p>Save your Hindsight connection before publishing or recovering a checkpoint.</p>}
   <h4>Manual checkpoint and handoff</h4><p>Use these controls to reconcile a pending checkpoint or record an explicit editor handoff.</p>
   <button className="secondary" disabled={busy||!status.configured||status.pending.length>0||otherOwner} onClick={()=>void run(async()=>{const result=await api<{snapshotHash:string}>('/cloud-workspace/stage','POST',{expectedParentHash:status.status.snapshotHash||null,...(nextOwnerId.trim()?{nextOwnerId:nextOwnerId.trim()}:{})});setMessage(`Checkpoint prepared: ${result.snapshotHash.slice(0,12)}. Review its credit allowance before publishing.`);})}>Prepare Cloud checkpoint</button>
   <label>Handoff to editor ID (optional)<input value={nextOwnerId} onChange={e=>setNextOwnerId(e.target.value)} placeholder="Leave blank to keep this editor" disabled={busy}/></label>
   {status.pending.map(item=><div key={item.snapshotHash}><p>Checkpoint {item.snapshotHash.slice(0,12)} · {item.status} · up to {item.forecast.uniqueDocuments} documents · ${item.forecast.fullWriteReservationUSD.toFixed(2)} write reservation plus policy verification.</p><button className="primary" disabled={busy||!status.configured||otherOwner} onClick={()=>void run(async()=>{const result=await api<{status:string;note?:string}>('/cloud-workspace/publish','POST',{snapshotHash:item.snapshotHash,maxWrites:32});setMessage(result.note||`Checkpoint ${result.status}.`);})}>Publish or check checkpoint · uses credits for new writes</button></div>)}
  </>}
  <details><summary>Recover on this machine</summary><p>Enter the existing workspace ID and this machine’s editor ID. Recovery previews the saved records before replacing the local cache. Editing requires a recorded handoff to that editor.</p><label>Recovery workspace ID<input value={workspaceId} onChange={e=>{setWorkspaceId(e.target.value);setPreview(null);setReplace(false);}} disabled={busy}/></label><label>Recovery editor ID<input value={ownerId} onChange={e=>{setOwnerId(e.target.value);setPreview(null);setReplace(false);}} disabled={busy}/></label><button className="secondary" disabled={busy||!status?.configured||!workspaceId.trim()||!ownerId.trim()} onClick={()=>void run(async()=>{setPreview(await api<Preview>('/cloud-workspace/recovery-preview','POST',{workspaceId:workspaceId.trim(),ownerId:ownerId.trim()}));setReplace(false);})}>Preview Cloud recovery</button>
   {preview&&<div><p>Verified checkpoint: {preview.counts.cases} cases, {preview.counts.companies} organizations, {preview.counts.articles} knowledge articles and {preview.counts.officialDocuments} official sections.</p><p>{preview.canEdit?'This editor holds the recorded handoff.':'Recovery is read-only for this editor until a handoff is recorded.'}</p><label><input type="checkbox" checked={replace} onChange={e=>setReplace(e.target.checked)} disabled={busy}/>Replace this local cache with the previewed Cloud records; preserve a local backup.</label><button className="primary" disabled={busy||!replace} onClick={()=>void run(async()=>{await api('/cloud-workspace/recovery-apply','POST',{previewId:preview.previewId,expectedLocalHash:preview.expectedLocalHash,snapshotHash:preview.snapshotHash,confirmReplace:true});setPreview(null);setReplace(false);setMessage('Cloud checkpoint recovered. Knowledge sources need fresh verification before they can be used in investigations.');})}>Recover verified checkpoint</button></div>}
  </details>
  <button className="secondary" disabled={busy||!status?.configured} onClick={()=>void run(async()=>{
   const workspace=await api<{articles:{id:string;revision:number;cloudRetention?:{status:string;revision:number;connectionMismatch?:boolean}}[]}>('/workspace'),docs=await api<{id:string;cloudVerified:boolean}[]>('/official-documents');
   const ids=[...workspace.articles.filter(a=>a.cloudRetention?.status!=='succeeded'||a.cloudRetention.revision!==a.revision||a.cloudRetention.connectionMismatch).map(a=>a.id),...docs.filter(d=>!d.cloudVerified).map(d=>d.id)].slice(0,512);let verified=0;
   for(let i=0;i<ids.length;i+=32){const result=await api<{verified:number}>('/cloud-workspace/verify-sources','POST',{sourceIds:ids.slice(i,i+32)});verified+=result.verified;}
   setMessage(ids.length?`${verified} of ${ids.length} source documents freshly verified. Unverified sources remain unavailable to investigations.`:'Current source documents are already verified for this connection.');
  })}>Verify recovered knowledge sources · reads only</button>
  {busy&&<p role="status">Checking Cloud workspace…</p>}{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}
 </section>;
}
