import {useQuery} from '@tanstack/react-query';
import {api} from './api';

type OfficialDocument={id:string;title:string;url:string;component:string;version:string;sectionHeading:string;sectionText:string;executor:string;hosting:string;sourceHash:string;sectionHash:string;sourceRef:string;sourceCommit?:string;retrievedAt:string;cloudVerified:boolean;prerequisiteQuestions?:string[];limitations?:string};
export function HindsightDocuments(){
 const query=useQuery({queryKey:['official-documents'],queryFn:()=>api<OfficialDocument[]>('/official-documents')});
 if(query.isError)return <section className="article-card"><h2>Official documentation</h2><p role="alert">The documentation list could not be loaded.</p></section>;
 if(!query.data?.length)return null;
 return <section className="article-card"><div className="section-heading"><h2>Official versioned documentation</h2><span>{query.data.filter(d=>d.cloudVerified).length} of {query.data.length} verified in Hindsight</span></div><p>These are official source sections, separate from historical case lessons. Investigations require the matching product version and environment; an unknown version remains a prerequisite question.</p>{query.data.map(d=><details key={d.id} id={`document-${d.id}`}><summary><strong>{d.title}</strong> · {d.component} {d.version} · {d.cloudVerified?'Cloud source verified':'Cloud source not verified'}</summary><p>{d.executor} · {d.hosting}. Documentation describes supported behavior; it does not establish a diagnosis or a successful fix for the current case.</p><a href={d.url} target="_blank" rel="noreferrer">Read the exact official source ↗</a>{d.limitations&&<p>{d.limitations}</p>}{!!d.prerequisiteQuestions?.length&&<><h3>Prerequisites to establish</h3><ul>{d.prerequisiteQuestions.map(q=><li key={q}>{q}</li>)}</ul></>}<h3>{d.sectionHeading}</h3><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere',fontSize:'0.85rem'}}>{d.sectionText}</pre><p className="caption">{d.id} · Source {d.sourceRef} · Retrieved {new Date(d.retrievedAt).toLocaleDateString()}</p><details><summary>Source integrity</summary><p className="caption" style={{overflowWrap:'anywhere'}}>File SHA-256: {d.sourceHash}<br/>Section SHA-256: {d.sectionHash}{d.sourceCommit&&<><br/>Commit: {d.sourceCommit}</>}</p></details></details>)}</section>;
}
