import {useEffect,useRef,useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {ArrowUpRight,BookOpen,Loader2,Sparkles} from 'lucide-react';
import {api} from './api';
import type {Article,ReflectionResult,Case} from './types';
import './memory-tools.css';

export function MemoryProvenance({article,current}:{article:Article;current?:Article}){
 const memory=article.memoryEvidence;
 const stale=!current||current.revision!==article.revision;
 return <details className="memory-provenance"><summary>Why this memory?</summary>
  <p className="memory-meta">{article.id} · retrieved revision {article.revision} · {current?`current approved revision ${current.revision}`:'current approved article unavailable'}</p>
  {stale&&<p className="memory-tools-error">This result no longer matches the current approved article. Prepare the investigation again before reuse.</p>}
  <p className="memory-meta">{memory?.provider||'Local approved knowledge'}{memory?.factId&&<> · Fact {memory.factId}</>}</p>
  <p className="memory-meta">Retrieved facts explain why this article matched. The current article is eligible for AI drafting after revision and applicability checks; it may still be omitted for size. Check “Evidence provided to the AI” for the sources actually sent. Retrieved facts are generated claims; check the original sources before acting.</p>
  {memory?.retrievedAt&&<p className="memory-meta">Retrieved {new Date(memory.retrievedAt).toLocaleString()}</p>}
  {!!memory?.chunks?.length&&<><h5>Retrieved source excerpts</h5>{memory.chunks.map(chunk=><blockquote key={chunk.id}>{chunk.text}</blockquote>)}</>}
  {!!memory?.sourceFacts?.length&&<><h5>Supporting generated facts</h5><ul className="memory-evidence-list">{memory.sourceFacts.map(fact=><li key={fact.id}>{fact.text}</li>)}</ul></>}
  {memory?.truncated&&<p className="memory-meta">This is a bounded evidence preview. Additional provider content was omitted; read the original sources for context.</p>}
  {!memory?.chunks?.length&&!memory?.sourceFacts?.length&&<p className="memory-meta">No additional Cloud excerpts were stored with this result.</p>}
  {article.curation&&<p className="memory-meta">AI source inspection · no human review, independent reproduction or confirmed current resolution.</p>}<h5>Original sources</h5>{article.citations?.length?article.citations.map((c,index)=><a className="source-link" key={`${c.id}-${index}`} href={c.url} target="_blank" rel="noreferrer"><BookOpen size={14}/><span>{c.title}</span><ArrowUpRight size={13}/></a>):<p className="memory-meta">No linked source excerpts were returned with this result.</p>}
 </details>;
}

export function CloudRetentionControls({article}:{article:Article}){
 const client=useQueryClient();const [pending,setPending]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const retention=article.cloudRetention?.revision===article.revision?article.cloudRetention:undefined;
 const connectionMismatch=retention?.connectionMismatch===true,status=retention?.status;
 async function check(){setPending(true);setError('');setMessage('');try{await api(`/articles/${article.id}/cloud-status`,'POST',{expectedRevision:article.revision});await client.invalidateQueries({queryKey:['workspace']});setMessage('Cloud status checked.');}catch(e){setError((e as Error).message);}finally{setPending(false);}}
 return <section className="cloud-retention" aria-label={`Cloud retention for ${article.id}`}><div className="section-heading"><h3>Cloud retention</h3><span className="memory-status-label">{connectionMismatch?'Current connection not retained':status==='succeeded'?'Current revision retained':status==='unverified'?'Outcome unverified':status==='processing'||status==='dispatched'?'Processing':status||'Current revision is local'}</span></div><p>Revision {article.revision}{retention?.note?` · ${retention.note}`:''}</p><p className="memory-meta">Manual retention and retagging are paused. Reviewed batches use the shared credit allowance; current local articles remain available for review.</p>{retention?.checkedAt&&<p className="memory-meta">Last checked {new Date(retention.checkedAt).toLocaleString()}</p>}{error&&<p role="alert" className="memory-tools-error">{error}</p>}{message&&<p role="status" className="memory-tools-success">{message}</p>}{retention&&!connectionMismatch&&<button className="secondary" disabled={pending} onClick={check}>{pending?<Loader2 className="spin" size={15}/>:null}Check Cloud status</button>}{!!article.cloudHistory?.length&&<details className="memory-provenance"><summary>Previous Cloud revisions</summary><ul>{article.cloudHistory.map(r=><li key={r.docId}>Revision {r.revision} · {r.status}</li>)}</ul></details>}</section>;
}

export function ReflectionAction({caseId,onReady}:{caseId:string;onReady:()=>void}){
 const active=useRef(true);useEffect(()=>{active.current=true;return()=>{active.current=false;};},[]);const client=useQueryClient();const q=useQuery({queryKey:['reflection',caseId],queryFn:()=>api<ReflectionResult>(`/cases/${caseId}/reflection`),refetchInterval:5000});const [pending,setPending]=useState(false),[error,setError]=useState('');
 async function reflect(){setPending(true);setError('');try{const result=await api<ReflectionResult>(`/cases/${caseId}/reflection`,'POST',{acknowledgeCreditUse:true});client.setQueryData(['reflection',caseId],result);await client.invalidateQueries({queryKey:['workspace']});if(active.current)onReady();}catch(e){setError((e as Error).message);client.setQueryData<ReflectionResult>(['reflection',caseId],old=>old?{...old,stale:true}:old);await client.invalidateQueries({queryKey:['reflection',caseId]});}finally{setPending(false);}}
 return <div className="reflection-action"><button className="secondary" disabled={pending||!q.data?.canReflect||q.isFetching} onClick={reflect}>{pending?<Loader2 size={15} className="spin"/>:<Sparkles size={15}/>} {pending?'Reflecting…':'Reflect on this case · uses credit'}</button><p>Optional Hindsight synthesis of scoped memory. Creates a preview for review; it does not send a reply, save drafts or approve knowledge.</p>{q.isLoading&&<p role="status">Checking reflection availability…</p>}{q.data?.reason&&<p className="memory-meta">{q.data.reason}</p>}{(q.error||error)&&<p role="alert" className="memory-tools-error">{error||(q.error as Error).message}</p>}{q.error&&<button className="text-button" onClick={()=>q.refetch()}>Reload reflection status</button>}</div>;
}

export function ReflectionPreview({caseId,articles}:{caseId:string;articles:Article[]}){
 const q=useQuery({queryKey:['reflection',caseId],queryFn:()=>api<ReflectionResult>(`/cases/${caseId}/reflection`),refetchInterval:5000});
 if(q.isLoading)return <p className="memory-meta" role="status">Loading saved reflection…</p>;
 if(q.error)return <p className="memory-tools-error" role="alert">Saved reflection could not load. <button className="text-button" onClick={()=>q.refetch()}>Try again</button></p>;
 const result=q.data,preview=result?.preview;if(!preview)return null;
 const stale=result.stale||preview.evidence.some(e=>!articles.some(a=>a.id===e.articleId&&a.revision===e.revision));
 return <section className={`reflection-preview${stale?' stale':''}`} aria-label="Reflection preview"><div className="reflection-heading"><Sparkles size={19}/><h3>Reflection preview</h3></div><p className="reflection-disclaimer">Unreviewed generated draft. Validate evidence and applicability before using any advice. This preview has not changed the case outcome, reply drafts or approved knowledge.</p><p className="memory-meta">{preview.provider} · {new Date(preview.generatedAt).toLocaleString()}</p>{stale&&<p className="reflection-warning" role="status">Out of date: the case or supporting article has changed. This saved preview must not be used as current advice. Review the latest evidence and explicitly run reflection again.</p>}<h4>Finding</h4><p>{preview.finding}</p><h4>Evidence</h4>{preview.evidence.length?preview.evidence.map((e,i)=><div key={`${e.articleId}-${i}`}><p><strong>{e.articleId} · r{e.revision}</strong> — {e.summary}</p>{articles.find(a=>a.id===e.articleId)?.citations?.map((c,index)=><a className="source-link" key={`${c.id}-${index}`} href={c.url} target="_blank" rel="noreferrer"><BookOpen size={14}/><span>{c.title}</span><ArrowUpRight size={13}/></a>)}</div>):<p>No supporting article references returned.</p>}<div className="reflection-grid">{([['Conflicts',preview.conflicts],['Missing facts',preview.missingFacts],['Next steps',preview.nextSteps]] as [string,string[]][]).map(([title,items])=><section key={title}><h4>{title}</h4>{items.length?<ul className="memory-evidence-list">{items.map((item,i)=><li key={i}>{item}</li>)}</ul>:<p className="memory-meta">None reported by the model.</p>}</section>)}</div></section>;
}

export function InvestigationEvidence({result}:{result:NonNullable<NonNullable<Case['analysis']>['modelResult']>}){
 return <details className="memory-provenance"><summary>Evidence provided to the AI</summary>{result.auditReview&&<div role="note"><h5>Diagnostic review · two reasoning steps</h5><p>{result.auditReview.message}</p><p>The candidate fix draft was withheld. These questions still need review; the evidence check does not verify a resolution or guarantee factual correctness.</p><p>{result.auditReview.claimCount} candidate claims reviewed · {result.auditReview.unsupportedCount} unsupported · {result.auditReview.uncertainCount} uncertain.</p>{result.auditReview.limitations.map((limit,i)=><p key={`audit-limit-${i}`}>{limit}</p>)}</div>}<p>Sources sent: {result.evidenceIds?.join(', ')||'None recorded.'}</p><p>Sources cited in the draft: {result.citations.join(', ')||'None'}. Attribution does not establish that the advice is correct.</p>{result.searchDepth&&<p>{result.searchDepth==='high'?'Deep':'Balanced'} Hindsight search · {result.traceSummary?.toolCalls||0} search/tool steps recorded. Generated memory facts are checked against their source revisions; they are not independent corroboration.</p>}{result.provenance&&<><h5>How memory contributed</h5>{result.provenance.records.length?result.provenance.records.map((r,i)=><div key={`${r.factId}-${i}`}><p><strong>{r.sourceId||r.articleId} · revision {r.revision}</strong>{r.sourceType==='official-document'&&<> · Official documentation {r.version}{r.url&&<> · <a href={r.url} target="_blank" rel="noreferrer">Exact source ↗</a></>}</>} · {r.type==='observation'?'Combined source observation':'Retrieved source fact'}</p><blockquote>{r.text}</blockquote>{r.sourceFacts?.length&&<p className="memory-meta">Checked against {r.sourceFacts.length} source facts from this revision.</p>}</div>):<p>No stored memory facts were used by Reflect. Review the supplied case and reference evidence.</p>}<p className="memory-meta">Source inspection by AI and Hindsight retention do not mean human review, independent reproduction or confirmation of this case.</p></>}{result.evidenceSelection?.omitted.map((item,i)=><p key={`omitted-${i}`}>{item.id} omitted: {item.reason}</p>)}{result.evidenceSelection?.rejected.map((item,i)=><p key={`rejected-${i}`}>{item.id} excluded: {item.reasons.join(' ')}</p>)}</details>;
}
