export type Event={id:string;at:string;text:string;caseId:string|null};
export type Attempt={id:string;step:string;result:string;evidence:string;articleId?:string};
export type Article={learningCloseout?:{key:string;articleId:string;revision:number;status:string;note:string;checks:number;checkedAt?:string};associatedHistoricalReports?:{reportId:string;sourceHash:string;reviewDepth:string;rationale?:string;reviewedAt:string;method:string;reviewer:string;humanReviewed:false;confirmed:false;independentlyReproduced:false}[];curation?:{key:string;contentHash:string;method:string;reviewer:string;reviewedAt:string;humanReviewed:false;confirmed:false;independentlyReproduced:false;immutable:true};historicalReportIds?:string[];sourceReports?:{reportId:string;sourceHash:string;reviewDepth:string}[];diagnostics?:string[];failedAlternatives?:{step:string;evidence:string;url:string}[];retentionPolicy?:string;cloudRetention?:CloudRetention;cloudHistory?:{revision:number;docId:string;status:string;retiredAt?:string}[];id:string;title:string;revision:number;fix:string;cause:string;verification:string;limitations:string;symptom:string;executor:string;hosting:string;serverVersion:string;runnerVersion:string;chartVersion:string;sourceIds:string[];citations?:{id:string;title:string;url:string;status:string;excerpt:string}[];sourceCases:string[];history:Article[];reviewer:string;sync:string;updatedAt:string;match?:{status:string;reasons:string[]};memoryEvidence?:{provider:string;factId:string;revision:number;documentId?:string;retrievedAt?:string;chunks?:{id:string;text:string}[];sourceFacts?:{id:string;text:string}[];truncated?:boolean}};
export type Incident={id:string;title:string;host:string;services:string[];start:string;end:string;status:string;sourceId:string|null;summary:string;hosting?:string;evidence?:string;reviewer?:string;revision?:number};
export type Case={evidenceReportId?:string;id:string;owner?:string;tasks?:{id:string;title:string;completed:boolean;evidence:string;sourceId:string|null;createdAt:string;completedAt:string|null}[];companyId:string;contact:string;title:string;description:string;status:string;priority:string;hosting:string;executor:string;serverVersion:string;runnerVersion:string;chartVersion:string;host:string;service:string;occurredAt:string;recentChanges:string;stage:string;symptom:string;sourceId:string|null;sourceDate:string|null;reconstructed:boolean;hasReplay?:boolean;attempts:Attempt[];articleIds:string[];incidentIds:string[];incidentLinks?:{incidentId:string;state:'proposed'|'confirmed'|'needs-review';evidence:string;revision?:number}[];timeline:Event[];resolution:null|{fix:string;cause:string;evidence:string;limitations:string;engineer:string};proposal:null|{title:string;fix:string;cause:string;verification:string;limitations:string;approvedArticleId?:string};drafts:null|{customer:string;engineering:string;provider:string};analysis:null|{modelResult?:null|{provider?:string;investigationId?:string;searchDepth?:'mid'|'high';mode?:'diagnostic-questions'|'conditional-investigation-plan';sourceEvidence?:{handle:string;sourceId:string;sourceKind:string;title:string;url?:string;authority:string;applicability?:unknown;source:Record<string,unknown>}[];caseEvidence?:Record<string,unknown>;auditReview?:{status:string;message:string;claimCount:number;unsupportedCount:number;uncertainCount:number;limitations:string[]};provenance?:{readCount:number;records:{factId:string;articleId?:string;sourceId?:string;sourceType?:string;version?:string;url?:string;revision:number;documentId:string;text:string;type:string;sourceFacts?:{factId:string;text:string;documentId:string}[]}[];selectionFacts?:{factId:string;articleId:string;revision:number;text:string}[]};traceSummary?:{toolCalls:number;llmCalls:number};evidenceIds?:string[];evidenceSelection?:null|{omitted:{id:string;reason:string}[];rejected:{id:string;reasons:string[]}[]};citations:string[];nextQuestions:string[];usage?:null|{inputTokens?:number;outputTokens?:number;estimatedUSD?:number;input_tokens?:number;output_tokens?:number}};useMemory:boolean;provider:string;at:string;references?:Reference[];questions:{field:string;text:string;reason:string;sourceId:string}[];candidates:Article[];incidentCandidates:Incident[];finding:string}};
export type Source={id:string;title:string;url:string;type:string;verification:string;summary:string};
export type Workspace={cases:Case[];companies:{id:string;name:string;note:string;kind?:string}[];articles:Article[];incidents:Incident[];events:Event[];outbox:{id:string;articleId:string;revision:number;status:string;attempts:number;error:string|null}[];sources:Source[];config:{cloudRequired?:boolean;cloudMemoryAvailable?:boolean;supportModel?:string|null;verificationScope?:string;appName:string;memoryMode:string;agentMode:string;externalEnabled:boolean;liveVerified:boolean}};
export type CloudStatus={configured:boolean;baseUrl:string;bank:string;running:boolean;lastResult:null|{verified:boolean;retain:string;recall:string;note:string;elapsedMs:number}};

export type Reference={retrievedAt?:string;versionStatus?:string;versionEvidence?:{version:string;sha256:string;fetchedAt:string};status?:string;id:string;title:string;summary:string;question:string;executor:string;stage:string;url:string;kind:string;reviewedAt:string;versions:string;outcome:string;applicability?:string;retrieval?:{score:number;matched:string[]}};

export type CloudRetention={batchManaged?:boolean;revision:number;status:string;connectionMismatch?:boolean;providerOperationId?:string;checkedAt?:string;retryable?:boolean;note?:string};
export type ReflectionResult={preview:null|{finding:string;evidence:{articleId:string;revision:number;summary:string}[];conflicts:string[];missingFacts:string[];nextSteps:string[];generatedAt:string;provider:string;reviewRequired:true};stale:boolean;canReflect:boolean;reason?:string};
